// Темы для модуля Hören A1 — все 4 Teile.
// Поля: {situation, sceneHint} — основные для промптов.

import type { TopicData } from '@/lib/topic-sampler'

// Teil 1 — kurze Durchsagen / Ansagen (Mono)
export const HOREN_A1_T1: TopicData[] = [
  { situation: 'Durchsage am Bahnhof', sceneHint: 'Zugverspätung, Gleiswechsel', durchsageContext: 'Hauptbahnhof' },
  { situation: 'Anrufbeantworter eines Freundes', sceneHint: 'Treffen verschieben', durchsageContext: 'Mobiltelefon' },
  { situation: 'Ansage im Supermarkt', sceneHint: 'Sonderangebot, Schließzeit', durchsageContext: 'Supermarkt' },
  { situation: 'Ansage im Kaufhaus', sceneHint: 'Fundkind bei der Information', durchsageContext: 'Kaufhaus' },
  { situation: 'Ansage in der Schule', sceneHint: 'Schulschluss früher', durchsageContext: 'Schule' },
  { situation: 'Ansage im Museum', sceneHint: 'Schließzeit erinnert', durchsageContext: 'Museum' },
  { situation: 'Durchsage im Flughafen', sceneHint: 'Gate-Wechsel', durchsageContext: 'Flughafen' },
  { situation: 'Radiowerbung für Kinoabend', sceneHint: 'Neue Filme', durchsageContext: 'Radio' },
  { situation: 'Durchsage in der Straßenbahn', sceneHint: 'Nächste Haltestelle', durchsageContext: 'Straßenbahn' },
  { situation: 'Nachricht vom Zahnarzt', sceneHint: 'Termin abgesagt', durchsageContext: 'Anrufbeantworter Arzt' },
  { situation: 'Ansage in der Bibliothek', sceneHint: 'Schließzeit', durchsageContext: 'Stadtbibliothek' },
  { situation: 'Anrufbeantworter der Oma', sceneHint: 'Besuch absagen', durchsageContext: 'Festnetz' },
  { situation: 'Ansage im Freibad', sceneHint: 'Gewitter — Evakuierung', durchsageContext: 'Freibad' },
  { situation: 'Durchsage im Bus', sceneHint: 'Umleitung', durchsageContext: 'Stadtbus' },
  { situation: 'Radio-Wettervorhersage', sceneHint: 'heute sonnig, morgen Regen', durchsageContext: 'Radio' },
  { situation: 'Ansage im Kino', sceneHint: 'Film verspätet', durchsageContext: 'Kino' },
  { situation: 'Ansage am Bahnhof wegen Gleis', sceneHint: 'Gleis 7 statt 5', durchsageContext: 'Regionalbahnhof' },
  { situation: 'Anrufbeantworter einer Freundin', sceneHint: 'Essen verschieben', durchsageContext: 'Mobil' },
  { situation: 'Ansage im Schwimmbad', sceneHint: 'Schwimmkurs-Info', durchsageContext: 'Schwimmbad' },
  { situation: 'Ansage in der U-Bahn', sceneHint: 'Verspätung wegen Bauarbeiten', durchsageContext: 'U-Bahn' },
  { situation: 'Ansage im Kindergarten', sceneHint: 'Abholzeit verändert', durchsageContext: 'Kita' },
  { situation: 'Durchsage im Stadion', sceneHint: 'Parkplatz-Hinweis', durchsageContext: 'Fußballstadion' },
  { situation: 'Radio-Ansage zu einem Stadtfest', sceneHint: 'Beginn um 14 Uhr', durchsageContext: 'Radio' },
  { situation: 'Ansage in der Arztpraxis', sceneHint: 'Wartezeit', durchsageContext: 'Hausarztpraxis' },
  { situation: 'Anrufbeantworter Kollege', sceneHint: 'Meeting verschieben', durchsageContext: 'Büro-Telefon' },
  { situation: 'Ansage am Flughafen wegen Koffer', sceneHint: 'Fundstück', durchsageContext: 'Flughafen' },
  { situation: 'Ansage im Zoo', sceneHint: 'Tierfütterung', durchsageContext: 'Zoo' },
  { situation: 'Ansage im Einkaufszentrum', sceneHint: 'Auto umparken', durchsageContext: 'Einkaufszentrum' },
  { situation: 'Durchsage im ICE', sceneHint: 'Bordbistro geschlossen', durchsageContext: 'ICE' },
  { situation: 'Radio zu einer Verkehrslage', sceneHint: 'Stau auf A8', durchsageContext: 'Radio' },
  { situation: 'Ansage bei einer Tankstelle', sceneHint: 'Zapfsäule defekt', durchsageContext: 'Tankstelle' },
  { situation: 'Ansage im Baumarkt', sceneHint: 'Aktion am Werkzeug', durchsageContext: 'Baumarkt' },
  { situation: 'Ansage in einer Apotheke', sceneHint: 'Wartezeit', durchsageContext: 'Apotheke' },
  { situation: 'Ansage in der Schwimmhalle', sceneHint: 'Schwimmkurs Ausfall', durchsageContext: 'Schwimmhalle' },
  { situation: 'Radio-Termine am Wochenende', sceneHint: 'Marktkalender', durchsageContext: 'Radio' },
  { situation: 'Ansage Postfiliale', sceneHint: 'Schließzeit früher', durchsageContext: 'Post' },
  { situation: 'Durchsage in der Schule zur Feuerübung', sceneHint: 'Übung um 10 Uhr', durchsageContext: 'Schule' },
  { situation: 'Ansage im Sportstudio', sceneHint: 'Kursausfall', durchsageContext: 'Fitnessstudio' },
  { situation: 'Durchsage im Stadtbus', sceneHint: 'neue Linie', durchsageContext: 'Stadtbus' },
  { situation: 'Radio-Meldung zu einem Konzert', sceneHint: 'Tickets frei', durchsageContext: 'Radio' },
  { situation: 'Ansage bei einer Bank', sceneHint: 'Geldautomat defekt', durchsageContext: 'Bank' },
  { situation: 'Ansage im Freizeitbad', sceneHint: 'Rutsche kurz gesperrt', durchsageContext: 'Freizeitbad' },
  { situation: 'Ansage in einer Jugendherberge', sceneHint: 'Frühstücksraum', durchsageContext: 'Jugendherberge' },
  { situation: 'Anrufbeantworter Fahrradladen', sceneHint: 'Fahrrad fertig', durchsageContext: 'Fahrradladen' },
  { situation: 'Ansage im Parkhaus', sceneHint: 'Öffnungszeit', durchsageContext: 'Parkhaus' },
  { situation: 'Durchsage im Volkshochschulgebäude', sceneHint: 'Raumwechsel', durchsageContext: 'VHS' },
  { situation: 'Ansage im Stadion zur Anstoßzeit', sceneHint: 'Verzögerung', durchsageContext: 'Stadion' },
  { situation: 'Radiowerbung für Reisen', sceneHint: 'Last-Minute-Angebot', durchsageContext: 'Radio' },
  { situation: 'Ansage in der Bahnhofsapotheke', sceneHint: 'Notdienst', durchsageContext: 'Apotheke' },
  { situation: 'Durchsage im IC wegen Speisewagen', sceneHint: 'Speisewagen geschlossen', durchsageContext: 'IC' },
  { situation: 'Ansage in der Stadtbücherei', sceneHint: 'neue Öffnungszeit', durchsageContext: 'Bücherei' },
  { situation: 'Ansage Rathaus', sceneHint: 'Terminvergabe', durchsageContext: 'Rathaus' },
  { situation: 'Ansage Einkaufszentrum zur Pause', sceneHint: 'Mittagspause', durchsageContext: 'Einkaufszentrum' },
  { situation: 'Radio-Angebot aus der Bäckerei', sceneHint: 'Sonderbrot', durchsageContext: 'Radio' },
  { situation: 'Ansage im Freizeitpark', sceneHint: 'Show beginnt', durchsageContext: 'Freizeitpark' },
  { situation: 'Ansage in einem Elektromarkt', sceneHint: 'Angebot Handy', durchsageContext: 'Elektromarkt' },
  { situation: 'Ansage am Flughafen zur Passkontrolle', sceneHint: 'Schlange lang', durchsageContext: 'Flughafen' },
  { situation: 'Ansage beim Schwimmkurs', sceneHint: 'Trainer krank', durchsageContext: 'Schwimmhalle' },
  { situation: 'Anrufbeantworter Hausarzt', sceneHint: 'Vertretung', durchsageContext: 'Hausarzt' },
  { situation: 'Ansage im Sportverein zur Versammlung', sceneHint: 'Termin Versammlung', durchsageContext: 'Sportverein' },
]

// Teil 2 — Dialog mit 5 Szenen
export const HOREN_A1_T2: TopicData[] = [
  { situation: 'Tag an der Uni', sceneHint: 'Mensa, Bibliothek, Seminar, Kiosk, Bushaltestelle', dialogSituation: 'Universitätsalltag', roles: ['casual_male', 'casual_female'] },
  { situation: 'Wochenende in der Stadt', sceneHint: 'Markt, Café, Museum, Park, Straßenbahn', dialogSituation: 'Stadtbummel', roles: ['casual_female', 'casual_male'] },
  { situation: 'Ausflug zum See', sceneHint: 'Bahnhof, Imbiss, Bootsverleih, Restaurant, Supermarkt', dialogSituation: 'Seetag', roles: ['casual_male', 'casual_female'] },
  { situation: 'Einkaufstour', sceneHint: 'Bäckerei, Obsthändler, Drogerie, Kleidungsgeschäft, Schuhladen', dialogSituation: 'Einkaufen', roles: ['casual_female', 'casual_male'] },
  { situation: 'Familien-Sonntag', sceneHint: 'Zoo, Eisdiele, Spielplatz, Café, Heimweg', dialogSituation: 'Familie', roles: ['casual_female', 'child'] },
  { situation: 'Freundinnenwochenende', sceneHint: 'Café, Shopping, Kino, Restaurant, Hotel', dialogSituation: 'Mädels-Trip', roles: ['casual_female', 'casual_female'] },
  { situation: 'Tag in der Kita-Nähe', sceneHint: 'Kita, Kinderwagen-Laden, Café, Spielplatz, Supermarkt', dialogSituation: 'Mit Kind unterwegs', roles: ['casual_female', 'casual_male'] },
  { situation: 'Ausflug in die Altstadt', sceneHint: 'Rathaus, Bäckerei, Galerie, Brunnen, Bushaltestelle', dialogSituation: 'Stadtführung', roles: ['casual_male', 'casual_female'] },
  { situation: 'Sporttag', sceneHint: 'Schwimmbad, Kiosk, Sportplatz, Umkleide, Nachhauseweg', dialogSituation: 'Sport am Samstag', roles: ['casual_male', 'casual_male'] },
  { situation: 'Tag bei Oma', sceneHint: 'Oma-Haus, Garten, Bäcker, Park, Bushaltestelle', dialogSituation: 'Oma-Besuch', roles: ['child', 'elderly_female'] },
  { situation: 'Einkauf fürs Abendessen', sceneHint: 'Supermarkt, Bäcker, Weinladen, Parkplatz, Heimweg', dialogSituation: 'Kochen zu Hause', roles: ['casual_female', 'casual_male'] },
  { situation: 'Ferientag in der Stadt', sceneHint: 'Freibad, Eisdiele, Spielplatz, Bäckerei, Stadtbahn', dialogSituation: 'Sommerferien', roles: ['casual_female', 'child'] },
  { situation: 'Nachmittag im Stadtteil', sceneHint: 'Drogerie, Floristen, Café, Bücherei, Haltestelle', dialogSituation: 'Besorgungen', roles: ['casual_female', 'casual_female'] },
  { situation: 'Tag mit dem Opa', sceneHint: 'Metzger, Café, Park, Brücke, Heimweg', dialogSituation: 'Opa-Besuch', roles: ['child', 'casual_male'] },
  { situation: 'Ein Abend zu zweit', sceneHint: 'Restaurant, Kino, Eisdiele, Taxi, Wohnung', dialogSituation: 'Date-Abend', roles: ['casual_female', 'casual_male'] },
  { situation: 'Reise mit dem Zug', sceneHint: 'Bahnhof, Bistro im Zug, Ankunft, Taxi, Hotel', dialogSituation: 'Zugreise', roles: ['casual_male', 'casual_female'] },
  { situation: 'Ausflug in den Wald', sceneHint: 'Bushaltestelle, Waldweg, Grillplatz, Hütte, Rückweg', dialogSituation: 'Waldtag', roles: ['casual_male', 'casual_female'] },
  { situation: 'Wochenmarkt-Runde', sceneHint: 'Gemüsehändler, Bäcker, Käsestand, Blumen, Heimweg', dialogSituation: 'Marktbesuch', roles: ['casual_female', 'casual_male'] },
  { situation: 'Nachmittag im Freibad', sceneHint: 'Kasse, Umkleide, Schwimmbecken, Imbiss, Liegewiese', dialogSituation: 'Freibadtag', roles: ['child', 'casual_female'] },
  { situation: 'Ein Tag als Tourist', sceneHint: 'Hotel, Stadtführung, Souvenirladen, Restaurant, Taxi', dialogSituation: 'Tourist in Berlin', roles: ['casual_male', 'casual_female'] },
  { situation: 'Erstes Training im Verein', sceneHint: 'Sportplatz, Umkleide, Kiosk, Bus, Heimweg', dialogSituation: 'Sportverein', roles: ['casual_male', 'casual_female'] },
  { situation: 'Tag in der Bücherei', sceneHint: 'Empfang, Leseecke, Schulungsraum, Kaffeeautomat, Ausgang', dialogSituation: 'Bibliothek', roles: ['casual_female', 'casual_male'] },
  { situation: 'Sonntag mit Freunden', sceneHint: 'Brunch, Park, Spielplatz, Eisdiele, Heimweg', dialogSituation: 'Sonntagsrunde', roles: ['casual_female', 'casual_male'] },
  { situation: 'Ein Tag beim Fahrradkauf', sceneHint: 'Fahrradladen, Café, Reparaturservice, Taxi, Heimweg', dialogSituation: 'Fahrradkauf', roles: ['casual_male', 'casual_female'] },
  { situation: 'Tag mit Tieren', sceneHint: 'Tierheim, Park, Supermarkt, Tierarzt, Heimweg', dialogSituation: 'Hund begleiten', roles: ['casual_female', 'casual_male'] },
  { situation: 'Kinderbesuch im Museum', sceneHint: 'Kasse, Kinderbereich, Café, Workshop, Ausgang', dialogSituation: 'Museumstag', roles: ['casual_female', 'child'] },
  { situation: 'Essen mit der Familie', sceneHint: 'Restaurant, Spielplatz vorher, Eisdiele, Taxi, Wohnung', dialogSituation: 'Familienessen', roles: ['casual_female', 'casual_male'] },
  { situation: 'Einweihung der Wohnung', sceneHint: 'Möbelhaus, Café, Baumarkt, Wohnung, Heimweg', dialogSituation: 'Einzug', roles: ['casual_female', 'casual_male'] },
  { situation: 'Ausflug zur Eisbahn', sceneHint: 'Eingang, Umkleide, Eisfläche, Imbiss, Heimweg', dialogSituation: 'Eislaufen', roles: ['child', 'casual_male'] },
  { situation: 'Deutschkurs-Tag', sceneHint: 'Sprachschule, Mensa, Tandem-Café, Bücherei, Heimweg', dialogSituation: 'Sprachkurs-Alltag', roles: ['casual_female', 'casual_male'] },
  { situation: 'Ausflug in den Botanischen Garten', sceneHint: 'Eingang, Gewächshaus, Café, Souvenirshop, Bus', dialogSituation: 'Botanischer Garten', roles: ['casual_female', 'casual_female'] },
  { situation: 'Tag mit Senioren', sceneHint: 'Treffpunkt, Park, Café, Bibliothek, Heimfahrt', dialogSituation: 'Seniorenausflug', roles: ['elderly_female', 'casual_female'] },
  { situation: 'Sonntag mit Kindern', sceneHint: 'Spielplatz, Bäckerei, Zoo, Imbiss, Wohnung', dialogSituation: 'Kindertag', roles: ['casual_male', 'child'] },
  { situation: 'Ausflug in den Tierpark', sceneHint: 'Kasse, Affenhaus, Streichelzoo, Imbiss, Ausgang', dialogSituation: 'Tierparktag', roles: ['casual_female', 'child'] },
  { situation: 'Tag im Einkaufszentrum', sceneHint: 'Info, Modeladen, Elektromarkt, Café, Parkhaus', dialogSituation: 'Shoppingtag', roles: ['casual_male', 'casual_female'] },
  { situation: 'Winterfest-Tag', sceneHint: 'Eiscafé, Glühweinstand, Bühne, Imbiss, Heimweg', dialogSituation: 'Winterfest', roles: ['casual_female', 'casual_male'] },
  { situation: 'Tag am Strand', sceneHint: 'Promenade, Strandkorb, Kiosk, Restaurant, Hotel', dialogSituation: 'Strandtag', roles: ['casual_male', 'casual_female'] },
  { situation: 'Sonntag im Wald', sceneHint: 'Parkplatz, Waldweg, Aussicht, Hütte, Rückweg', dialogSituation: 'Waldspaziergang', roles: ['casual_male', 'casual_female'] },
  { situation: 'Ausflug zum Schloss', sceneHint: 'Ticketkasse, Führung, Café, Schlosspark, Bus', dialogSituation: 'Schlossbesuch', roles: ['casual_female', 'casual_male'] },
  { situation: 'Großer Einkauf vor dem Urlaub', sceneHint: 'Drogerie, Kleidung, Apotheke, Supermarkt, Bank', dialogSituation: 'Urlaubsshopping', roles: ['casual_female', 'casual_male'] },
  { situation: 'Tag in der Arztpraxis', sceneHint: 'Empfang, Wartezimmer, Sprechzimmer, Apotheke, Heimweg', dialogSituation: 'Arztbesuch', roles: ['casual_female', 'professional_female'] },
  { situation: 'Ausflug zum Wochenmarkt der Stadt', sceneHint: 'Marktstand, Café, Blumen, Metzger, Straßenbahn', dialogSituation: 'Marktbesuch', roles: ['casual_male', 'casual_female'] },
  { situation: 'Familientag am Fluss', sceneHint: 'Bootsverleih, Uferbahn, Kiosk, Spielplatz, Auto', dialogSituation: 'Flussausflug', roles: ['casual_male', 'casual_female'] },
  { situation: 'Nachmittag in der Bibliothek', sceneHint: 'Eingang, Kinderbereich, Lernzone, Café, Ausgang', dialogSituation: 'Bibliothekstag', roles: ['casual_female', 'child'] },
  { situation: 'Ein Tag in der Musikschule', sceneHint: 'Empfang, Übungsraum, Aula, Café, Heimweg', dialogSituation: 'Musikschule', roles: ['casual_female', 'child'] },
  { situation: 'Ausflug zum Freizeitpark', sceneHint: 'Kasse, Karussell, Imbiss, Achterbahn, Ausgang', dialogSituation: 'Freizeitpark', roles: ['casual_male', 'child'] },
  { situation: 'Geburtstagstour', sceneHint: 'Kino, Restaurant, Eisdiele, Park, Heimweg', dialogSituation: 'Geburtstag', roles: ['casual_female', 'casual_male'] },
  { situation: 'Hochzeitstag', sceneHint: 'Standesamt, Restaurant, Park, Fotos, Heimweg', dialogSituation: 'Hochzeit', roles: ['casual_female', 'casual_male'] },
  { situation: 'Ein Tag an der Ostsee', sceneHint: 'Fähre, Strand, Hafen, Fischrestaurant, Hotel', dialogSituation: 'Küstentag', roles: ['casual_male', 'casual_female'] },
  { situation: 'Stadttour mit Fahrrad', sceneHint: 'Fahrradverleih, Park, Brücke, Café, Rückgabestation', dialogSituation: 'Fahrradtour', roles: ['casual_male', 'casual_female'] },
  { situation: 'Besuch bei Freunden in anderer Stadt', sceneHint: 'Bahnhof, Wohnung, Park, Restaurant, Bar', dialogSituation: 'Freunde besuchen', roles: ['casual_female', 'casual_male'] },
  { situation: 'Urlaubsvorbereitung', sceneHint: 'Reisebüro, Apotheke, Supermarkt, Bank, Heimweg', dialogSituation: 'Urlaubsvorbereitung', roles: ['casual_female', 'casual_male'] },
  { situation: 'Ein Tag im Hafen', sceneHint: 'Hafenpromenade, Schiff, Museum, Fischbude, Bus', dialogSituation: 'Hafentag', roles: ['casual_male', 'casual_female'] },
  { situation: 'Ein Tag im Schnee', sceneHint: 'Bahn, Schlittenhang, Hütte, Glühwein, Rückfahrt', dialogSituation: 'Wintertag', roles: ['casual_female', 'casual_male'] },
  { situation: 'Ein Nachmittag im Stadtpark', sceneHint: 'Spielplatz, Kiosk, Teich, Biergarten, Heimweg', dialogSituation: 'Parktag', roles: ['casual_female', 'child'] },
  { situation: 'Besuch beim Optiker und mehr', sceneHint: 'Optiker, Café, Buchladen, Bäckerei, Bus', dialogSituation: 'Augen-Termin', roles: ['casual_female', 'casual_female'] },
  { situation: 'Tag im Hallenbad', sceneHint: 'Kasse, Umkleide, Becken, Kiosk, Heimweg', dialogSituation: 'Hallenbad', roles: ['casual_male', 'child'] },
  { situation: 'Nachmittag in der Stadt mit Oma', sceneHint: 'Modeladen, Café, Apotheke, Park, Bus', dialogSituation: 'Oma in der Stadt', roles: ['casual_female', 'elderly_female'] },
  { situation: 'Ein Tag auf dem Bauernhof', sceneHint: 'Stall, Bäckerei, Traktor, Hofladen, Rückweg', dialogSituation: 'Bauernhof', roles: ['casual_male', 'child'] },
  { situation: 'Ein Tag als Praktikant', sceneHint: 'Empfang, Büro, Pausenraum, Meeting, Heimweg', dialogSituation: 'Erster Tag Praktikum', roles: ['casual_male', 'professional_female'] },
]

// Teil 3 — Interview/Gespräch
export const HOREN_A1_T3: TopicData[] = [
  { situation: 'Radio-Interview mit einer Studentin', sceneHint: 'über Hobbys', interviewTopic: 'Hobbys', intervieweeProfession: 'Studentin' },
  { situation: 'Gespräch mit einem Koch', sceneHint: 'Lieblingsgericht', interviewTopic: 'Kochen', intervieweeProfession: 'Koch' },
  { situation: 'Interview mit einem Sportler', sceneHint: 'Trainingsalltag', interviewTopic: 'Sport', intervieweeProfession: 'Leichtathlet' },
  { situation: 'Interview mit einer Bäckerin', sceneHint: 'Brotsorten', interviewTopic: 'Backen', intervieweeProfession: 'Bäckerin' },
  { situation: 'Interview mit einem Busfahrer', sceneHint: 'Arbeitstag', interviewTopic: 'Busfahrer-Alltag', intervieweeProfession: 'Busfahrer' },
  { situation: 'Gespräch mit einer Musiklehrerin', sceneHint: 'Unterricht', interviewTopic: 'Musikunterricht', intervieweeProfession: 'Musiklehrerin' },
  { situation: 'Interview mit einer Verkäuferin', sceneHint: 'Arbeit im Laden', interviewTopic: 'Kundengespräche', intervieweeProfession: 'Verkäuferin' },
  { situation: 'Interview mit einem Tierpfleger', sceneHint: 'Zooarbeit', interviewTopic: 'Tiere pflegen', intervieweeProfession: 'Tierpfleger' },
  { situation: 'Gespräch mit einer Bibliothekarin', sceneHint: 'Bücher empfehlen', interviewTopic: 'Bücher', intervieweeProfession: 'Bibliothekarin' },
  { situation: 'Interview mit einer Malerin', sceneHint: 'Farben und Motive', interviewTopic: 'Kunst', intervieweeProfession: 'Malerin' },
  { situation: 'Gespräch mit einem Friseur', sceneHint: 'Haarpflege', interviewTopic: 'Haare', intervieweeProfession: 'Friseur' },
  { situation: 'Interview mit einem Floristen', sceneHint: 'Blumen binden', interviewTopic: 'Blumen', intervieweeProfession: 'Florist' },
  { situation: 'Interview mit einer Kellnerin', sceneHint: 'Arbeitsalltag', interviewTopic: 'Kellnern', intervieweeProfession: 'Kellnerin' },
  { situation: 'Gespräch mit einem Fotografen', sceneHint: 'schönstes Foto', interviewTopic: 'Fotografie', intervieweeProfession: 'Fotograf' },
  { situation: 'Interview mit einer Krankenpflegerin', sceneHint: 'Schichtdienst', interviewTopic: 'Pflege', intervieweeProfession: 'Pflegerin' },
  { situation: 'Interview mit einer Erzieherin', sceneHint: 'Kita-Alltag', interviewTopic: 'Kita', intervieweeProfession: 'Erzieherin' },
  { situation: 'Gespräch mit einer Sportlehrerin', sceneHint: 'Schulsport', interviewTopic: 'Schulsport', intervieweeProfession: 'Sportlehrerin' },
  { situation: 'Interview mit einem Schreiner', sceneHint: 'Holzarbeit', interviewTopic: 'Möbelbau', intervieweeProfession: 'Schreiner' },
  { situation: 'Interview mit einem Taxifahrer', sceneHint: 'ungewöhnliche Gäste', interviewTopic: 'Taxifahrten', intervieweeProfession: 'Taxifahrer' },
  { situation: 'Gespräch mit einer Fahrradverkäuferin', sceneHint: 'Trends im Laden', interviewTopic: 'Fahrräder', intervieweeProfession: 'Fahrradverkäuferin' },
  { situation: 'Interview mit einem Bäckereichef', sceneHint: 'Familienbetrieb', interviewTopic: 'Backen', intervieweeProfession: 'Bäckereichef' },
  { situation: 'Gespräch mit einer Modedesignerin', sceneHint: 'Sommerkollektion', interviewTopic: 'Mode', intervieweeProfession: 'Designerin' },
  { situation: 'Interview mit einer Physiotherapeutin', sceneHint: 'Patient-Alltag', interviewTopic: 'Physiotherapie', intervieweeProfession: 'Physiotherapeutin' },
  { situation: 'Interview mit einem Apotheker', sceneHint: 'Sommer-Beschwerden', interviewTopic: 'Apothekenalltag', intervieweeProfession: 'Apotheker' },
  { situation: 'Interview mit einer Yogalehrerin', sceneHint: 'Kurse', interviewTopic: 'Yoga', intervieweeProfession: 'Yogalehrerin' },
  { situation: 'Gespräch mit einem Feuerwehrmann', sceneHint: 'Berufswahl', interviewTopic: 'Feuerwehr', intervieweeProfession: 'Feuerwehrmann' },
  { situation: 'Interview mit einem Gärtner', sceneHint: 'Frühling im Garten', interviewTopic: 'Garten', intervieweeProfession: 'Gärtner' },
  { situation: 'Interview mit einer Krankenhausverwalterin', sceneHint: 'Büroalltag', interviewTopic: 'Verwaltung', intervieweeProfession: 'Verwaltungsangestellte' },
  { situation: 'Gespräch mit einem Maler und Lackierer', sceneHint: 'Farben in Wohnungen', interviewTopic: 'Farben', intervieweeProfession: 'Maler' },
  { situation: 'Interview mit einer Lehrerin', sceneHint: 'Deutschkurs', interviewTopic: 'Sprachen lehren', intervieweeProfession: 'Deutschlehrerin' },
  { situation: 'Interview mit einem Fahrradkurier', sceneHint: 'Routen durch die Stadt', interviewTopic: 'Fahrradkurier', intervieweeProfession: 'Fahrradkurier' },
  { situation: 'Interview mit einer Bäckerin über Brezeln', sceneHint: 'bayerische Brezel', interviewTopic: 'Brezel', intervieweeProfession: 'Bäckerin' },
  { situation: 'Interview mit einem Koch-Azubi', sceneHint: 'Ausbildungsjahr', interviewTopic: 'Ausbildung Kochen', intervieweeProfession: 'Azubi-Koch' },
  { situation: 'Gespräch mit einer Köchin aus einem Kindergarten', sceneHint: 'Kinderküche', interviewTopic: 'Kitaküche', intervieweeProfession: 'Köchin Kita' },
  { situation: 'Interview mit einer Tanzlehrerin', sceneHint: 'Tanzschule', interviewTopic: 'Tanzen', intervieweeProfession: 'Tanzlehrerin' },
  { situation: 'Gespräch mit einem Schwimmlehrer', sceneHint: 'Schwimmkurse für Kinder', interviewTopic: 'Schwimmen', intervieweeProfession: 'Schwimmlehrer' },
  { situation: 'Interview mit einer Bäuerin', sceneHint: 'Hofladen', interviewTopic: 'Bauernhof', intervieweeProfession: 'Bäuerin' },
  { situation: 'Interview mit einem Handwerker', sceneHint: 'typischer Tag', interviewTopic: 'Handwerk', intervieweeProfession: 'Handwerker' },
  { situation: 'Gespräch mit einer Kellnerin aus dem Biergarten', sceneHint: 'Sommerjob', interviewTopic: 'Biergarten', intervieweeProfession: 'Kellnerin' },
  { situation: 'Interview mit einer Kassiererin', sceneHint: 'Supermarkt', interviewTopic: 'Supermarktalltag', intervieweeProfession: 'Kassiererin' },
  { situation: 'Interview mit einem Buchladen-Inhaber', sceneHint: 'Buchtipps', interviewTopic: 'Bücher', intervieweeProfession: 'Buchhändler' },
  { situation: 'Gespräch mit einem Musiker', sceneHint: 'Straßenmusik', interviewTopic: 'Straßenmusik', intervieweeProfession: 'Straßenmusiker' },
  { situation: 'Interview mit einem Segelmacher', sceneHint: 'Segel nähen', interviewTopic: 'Segel', intervieweeProfession: 'Segelmacher' },
  { situation: 'Interview mit einer Lehrerin aus der Grundschule', sceneHint: 'erste Klasse', interviewTopic: 'Grundschule', intervieweeProfession: 'Grundschullehrerin' },
  { situation: 'Gespräch mit einem Busschaffner', sceneHint: 'Berufsschule', interviewTopic: 'Busschaffner', intervieweeProfession: 'Busschaffner' },
  { situation: 'Interview mit einem Hausmeister', sceneHint: 'Schulgebäude', interviewTopic: 'Hausmeister', intervieweeProfession: 'Hausmeister' },
  { situation: 'Gespräch mit einer Bibliothekarin einer Kinderbibliothek', sceneHint: 'Leseförderung', interviewTopic: 'Kinderbücher', intervieweeProfession: 'Kinderbibliothekarin' },
  { situation: 'Interview mit einer Sportlerin aus der Schule', sceneHint: 'Schulmeisterschaften', interviewTopic: 'Schulsport', intervieweeProfession: 'Schülerin-Sportlerin' },
  { situation: 'Gespräch mit einem Bademeister', sceneHint: 'Freibad-Alltag', interviewTopic: 'Bademeister', intervieweeProfession: 'Bademeister' },
  { situation: 'Interview mit einem Kinderchor-Leiter', sceneHint: 'Proben', interviewTopic: 'Kinderchor', intervieweeProfession: 'Chorleiter' },
  { situation: 'Interview mit einer Deutsch-Kursleiterin', sceneHint: 'Integrationskurs', interviewTopic: 'Deutschkurs', intervieweeProfession: 'Kursleiterin' },
  { situation: 'Gespräch mit einem Bäcker aus Hamburg', sceneHint: 'Franzbrötchen', interviewTopic: 'Franzbrötchen', intervieweeProfession: 'Bäcker Hamburg' },
  { situation: 'Interview mit einer Kuchenbäckerin', sceneHint: 'Konditorei', interviewTopic: 'Torten', intervieweeProfession: 'Konditorin' },
  { situation: 'Interview mit einem Lehrling in der Metzgerei', sceneHint: 'Ausbildung', interviewTopic: 'Metzgerei', intervieweeProfession: 'Azubi-Metzger' },
  { situation: 'Gespräch mit einer Studentin im Dualstudium', sceneHint: 'Lernen und Arbeit', interviewTopic: 'Duales Studium', intervieweeProfession: 'Duale Studentin' },
  { situation: 'Interview mit einem Koch aus dem Café', sceneHint: 'tagsüber', interviewTopic: 'Café-Gerichte', intervieweeProfession: 'Café-Koch' },
  { situation: 'Gespräch mit einem Schuhmacher', sceneHint: 'Reparatur', interviewTopic: 'Schuhe', intervieweeProfession: 'Schuhmacher' },
  { situation: 'Interview mit einer Drogistin', sceneHint: 'Alltagsprodukte', interviewTopic: 'Drogerie', intervieweeProfession: 'Drogistin' },
  { situation: 'Interview mit einer Tierärztin für Kleintiere', sceneHint: 'Haustiere', interviewTopic: 'Tierarzt', intervieweeProfession: 'Tierärztin' },
  { situation: 'Gespräch mit einer Aushilfe im Café', sceneHint: 'Wochenendjob', interviewTopic: 'Wochenendjob', intervieweeProfession: 'Café-Aushilfe' },
]

// Teil 4 — 5 getrennte kurze Dialoge
export const HOREN_A1_T4: TopicData[] = [
  { situation: 'Fünf Alltagsdialoge', sceneHint: 'Bäcker, Bus, Bank, Büro, Bibliothek', fiveDialoguesTheme: 'Stadtleben' },
  { situation: 'Fünf kurze Gespräche', sceneHint: 'Arztpraxis, Apotheke, Schule, Sportplatz, Café', fiveDialoguesTheme: 'Alltag mit Kindern' },
  { situation: 'Fünf typische Szenen', sceneHint: 'Kaufhaus, Fahrradladen, Post, Kino, Restaurant', fiveDialoguesTheme: 'Einkauf und Freizeit' },
  { situation: 'Fünf Dialoge am Wochenende', sceneHint: 'Markt, Sportverein, Café, Schwimmbad, Theater', fiveDialoguesTheme: 'Wochenende' },
  { situation: 'Fünf Begegnungen unterwegs', sceneHint: 'Bus, Bahnhof, Imbiss, Hotel, Taxi', fiveDialoguesTheme: 'Unterwegs' },
  { situation: 'Fünf Dialoge im Viertel', sceneHint: 'Bäcker, Drogerie, Reinigung, Gemüseladen, Blumenstand', fiveDialoguesTheme: 'Viertelrundgang' },
  { situation: 'Fünf Gespräche rund ums Essen', sceneHint: 'Café, Restaurant, Bäcker, Eisdiele, Supermarkt', fiveDialoguesTheme: 'Essen und Trinken' },
  { situation: 'Fünf Dialoge bei Behörden', sceneHint: 'Bürgeramt, Post, Bank, Arbeitsagentur, Stadtkasse', fiveDialoguesTheme: 'Behördengänge' },
  { situation: 'Fünf Dialoge im Sport', sceneHint: 'Fitnessstudio, Sportgeschäft, Verein, Schwimmbad, Park', fiveDialoguesTheme: 'Sportalltag' },
  { situation: 'Fünf Dialoge bei Terminen', sceneHint: 'Arzt, Friseur, Fotograf, Kinderarzt, Autowerkstatt', fiveDialoguesTheme: 'Termine' },
  { situation: 'Fünf Alltagsszenen im Büro', sceneHint: 'Empfang, Pausenraum, Meetingraum, Büro, Aufzug', fiveDialoguesTheme: 'Büro' },
  { situation: 'Fünf Dialoge in der Schule', sceneHint: 'Klassenraum, Mensa, Schulhof, Lehrerzimmer, Flur', fiveDialoguesTheme: 'Schulalltag' },
  { situation: 'Fünf Dialoge bei Freunden', sceneHint: 'Wohnzimmer, Küche, Balkon, Flur, Auto', fiveDialoguesTheme: 'Freunde zu Hause' },
  { situation: 'Fünf kurze Dialoge im Kaufhaus', sceneHint: 'Mode, Elektro, Haushalt, Spielwaren, Kasse', fiveDialoguesTheme: 'Kaufhaus' },
  { situation: 'Fünf Dialoge im ICE-Alltag', sceneHint: 'Gepäck, Bordbistro, Reservierung, Toilette, Ankunft', fiveDialoguesTheme: 'Bahnreise' },
  { situation: 'Fünf Dialoge im Hotel', sceneHint: 'Rezeption, Zimmer, Frühstücksraum, Tagungsraum, Lobby', fiveDialoguesTheme: 'Hotel' },
  { situation: 'Fünf Dialoge in der Kita', sceneHint: 'Gruppenraum, Garten, Küche, Eltern-Gespräch, Flur', fiveDialoguesTheme: 'Kita-Alltag' },
  { situation: 'Fünf Dialoge im Supermarkt', sceneHint: 'Obst, Kühlregal, Wein, Kasse, Information', fiveDialoguesTheme: 'Supermarkt' },
  { situation: 'Fünf Dialoge beim Umzug', sceneHint: 'Wohnung, Treppenhaus, Transporter, Baumarkt, Nachbar', fiveDialoguesTheme: 'Umzug' },
  { situation: 'Fünf Alltagsdialoge mit Nachbarn', sceneHint: 'Treppenhaus, Müll, Aufzug, Garten, Hof', fiveDialoguesTheme: 'Nachbarn' },
  { situation: 'Fünf Dialoge in der Freizeit', sceneHint: 'Fußballplatz, Schrebergarten, See, Café, Bus', fiveDialoguesTheme: 'Freizeit' },
  { situation: 'Fünf Dialoge am Flughafen', sceneHint: 'Check-in, Security, Gate, Lounge, Gepäckband', fiveDialoguesTheme: 'Flughafen' },
  { situation: 'Fünf Dialoge im Café', sceneHint: 'Theke, Terrasse, Innenraum, Kasse, Parkplatz', fiveDialoguesTheme: 'Café' },
  { situation: 'Fünf Dialoge im Reisebüro', sceneHint: 'Empfang, Angebot, Buchung, Bezahlung, Abschied', fiveDialoguesTheme: 'Reisebüro' },
  { situation: 'Fünf Dialoge am Bahnhof', sceneHint: 'Schalter, Automat, Gleis, Wartesaal, Imbiss', fiveDialoguesTheme: 'Bahnhof' },
  { situation: 'Fünf Dialoge in der Apotheke', sceneHint: 'Beratung, Rezept, Kasse, Wartebereich, Notdienst', fiveDialoguesTheme: 'Apotheke' },
  { situation: 'Fünf Dialoge in der Tanzschule', sceneHint: 'Empfang, Saal, Umkleide, Café, Garderobe', fiveDialoguesTheme: 'Tanzschule' },
  { situation: 'Fünf Dialoge im Zoo', sceneHint: 'Kasse, Affenhaus, Streichelzoo, Eiscafé, Ausgang', fiveDialoguesTheme: 'Zoo' },
  { situation: 'Fünf Dialoge am Strand', sceneHint: 'Strandkorb, Kiosk, Promenade, Bootsverleih, Lokal', fiveDialoguesTheme: 'Strand' },
  { situation: 'Fünf Dialoge in der Schwimmhalle', sceneHint: 'Kasse, Becken, Sauna, Umkleide, Café', fiveDialoguesTheme: 'Schwimmhalle' },
  { situation: 'Fünf Dialoge im Fitnessstudio', sceneHint: 'Rezeption, Kurs, Sauna, Umkleide, Bar', fiveDialoguesTheme: 'Fitnessstudio' },
  { situation: 'Fünf Dialoge im Freibad', sceneHint: 'Kasse, Liegewiese, Kiosk, Becken, Parkplatz', fiveDialoguesTheme: 'Freibad' },
  { situation: 'Fünf Dialoge auf dem Kindergeburtstag', sceneHint: 'Wohnzimmer, Garten, Küche, Spielecke, Abschied', fiveDialoguesTheme: 'Kindergeburtstag' },
  { situation: 'Fünf Dialoge am Wochenmarkt', sceneHint: 'Obst, Fisch, Brot, Blumen, Käse', fiveDialoguesTheme: 'Wochenmarkt' },
  { situation: 'Fünf Dialoge am Bahnhofsapothekenkiosk', sceneHint: 'Zeitschrift, Snack, Getränk, Bäckerei, Abflug', fiveDialoguesTheme: 'Kioskwege' },
  { situation: 'Fünf Dialoge beim Kinderschwimmkurs', sceneHint: 'Empfang, Becken, Dusche, Elternbereich, Parkplatz', fiveDialoguesTheme: 'Kinderschwimmkurs' },
  { situation: 'Fünf Dialoge im Seniorenzentrum', sceneHint: 'Empfang, Aufenthaltsraum, Garten, Café, Flur', fiveDialoguesTheme: 'Seniorenzentrum' },
  { situation: 'Fünf Dialoge im Umzugsunternehmen', sceneHint: 'Büro, Transporter, Baumarkt, Wohnung, Parkplatz', fiveDialoguesTheme: 'Umzugsfirma' },
  { situation: 'Fünf Dialoge bei einem Straßenfest', sceneHint: 'Bühne, Grill, Getränkestand, Hüpfburg, Parkplatz', fiveDialoguesTheme: 'Straßenfest' },
  { situation: 'Fünf Dialoge beim Sommerfest der Kita', sceneHint: 'Empfang, Spielplatz, Grillstation, Kaffeebar, Ausgang', fiveDialoguesTheme: 'Kita-Sommerfest' },
  { situation: 'Fünf Dialoge im Museum', sceneHint: 'Kasse, Sonderausstellung, Café, Kindertisch, Museumsshop', fiveDialoguesTheme: 'Museum' },
  { situation: 'Fünf Dialoge in der Reinigung', sceneHint: 'Annahme, Kasse, Abholung, Flur, Stadtbus', fiveDialoguesTheme: 'Reinigung' },
  { situation: 'Fünf Dialoge am Elternabend', sceneHint: 'Flur, Klassenzimmer, Turnhalle, Schulhof, Parkplatz', fiveDialoguesTheme: 'Elternabend' },
  { situation: 'Fünf Dialoge im Gartenmarkt', sceneHint: 'Kasse, Pflanzenabteilung, Werkzeug, Kinderecke, Parkplatz', fiveDialoguesTheme: 'Gartenmarkt' },
  { situation: 'Fünf Dialoge im Fitnessklub', sceneHint: 'Kurs, Sauna, Bar, Rezeption, Parkplatz', fiveDialoguesTheme: 'Fitnessklub' },
  { situation: 'Fünf Dialoge am Kinderarzt', sceneHint: 'Rezeption, Wartebereich, Sprechzimmer, Labor, Parkplatz', fiveDialoguesTheme: 'Kinderarzt' },
  { situation: 'Fünf Dialoge im Heimatmuseum', sceneHint: 'Empfang, Ausstellungsraum, Café, Werkstatt, Ausgang', fiveDialoguesTheme: 'Heimatmuseum' },
  { situation: 'Fünf Dialoge in der Sprachschule', sceneHint: 'Empfang, Klassenzimmer, Pausenraum, Büro, Flur', fiveDialoguesTheme: 'Sprachschule' },
  { situation: 'Fünf Dialoge im Spielzeugladen', sceneHint: 'Eingang, Kuscheltiere, Spiele, Kasse, Geschenkverpackung', fiveDialoguesTheme: 'Spielzeugladen' },
  { situation: 'Fünf Dialoge im Kaufhaus zum Weihnachten', sceneHint: 'Empfang, Deko, Kleidung, Café, Kasse', fiveDialoguesTheme: 'Weihnachten im Kaufhaus' },
  { situation: 'Fünf Dialoge in der Fahrschule', sceneHint: 'Theorie, Auto, Parkplatz, Büro, Café', fiveDialoguesTheme: 'Fahrschule' },
  { situation: 'Fünf Dialoge im Weinladen', sceneHint: 'Beratung, Probe, Kasse, Lieferung, Ausgang', fiveDialoguesTheme: 'Weinladen' },
  { situation: 'Fünf Dialoge bei einem Wohnungswechsel', sceneHint: 'Kartons, Flur, Umzugsauto, Nachbarn, Schlüsselübergabe', fiveDialoguesTheme: 'Wohnungswechsel' },
  { situation: 'Fünf Dialoge im Bürgeramt', sceneHint: 'Info, Wartebereich, Schalter, Warteraum, Ausgang', fiveDialoguesTheme: 'Bürgeramt' },
  { situation: 'Fünf Dialoge beim Optiker', sceneHint: 'Beratung, Sehtest, Brillenauswahl, Kasse, Abholung', fiveDialoguesTheme: 'Optiker' },
  { situation: 'Fünf Dialoge im Laden für Haustiere', sceneHint: 'Futter, Spielzeug, Aquarium, Beratung, Kasse', fiveDialoguesTheme: 'Tierhandlung' },
  { situation: 'Fünf Dialoge am Flughafen-Imbiss', sceneHint: 'Kasse, Theke, Tisch, Ausgang, Toilette', fiveDialoguesTheme: 'Flughafen-Imbiss' },
  { situation: 'Fünf Dialoge in einer Eisdiele', sceneHint: 'Theke, Außenbereich, Kinderbereich, Kasse, Bestellung', fiveDialoguesTheme: 'Eisdiele' },
  { situation: 'Fünf Dialoge im Blumenladen', sceneHint: 'Beratung, Strauß, Kasse, Lieferung, Verpackung', fiveDialoguesTheme: 'Blumenladen' },
  { situation: 'Fünf Dialoge in einer Bar', sceneHint: 'Eingang, Tresen, Tisch, Musik, Toilette', fiveDialoguesTheme: 'Bar' },
]
