// Темы для модуля Hören A2 — все 4 Teile.
// Поля: {situation, sceneHint} — основные для промптов.

import type { TopicData } from '@/lib/topic-sampler'

// Teil 1 — kurze Durchsagen / Ansagen / Nachrichten (Mono)
export const HOREN_A2_T1: TopicData[] = [
  { situation: 'Durchsage Hauptbahnhof: Zug fällt aus', sceneHint: 'ICE nach München fällt aus, Ersatz ab Gleis 12', durchsageContext: 'Deutsche Bahn Hauptbahnhof' },
  { situation: 'Anrufbeantworter Volkshochschule', sceneHint: 'Kurs wegen Feiertag verschoben', durchsageContext: 'VHS Sekretariat' },
  { situation: 'Durchsage im Kaufhaus', sceneHint: 'Parkhaus schließt in 30 Minuten', durchsageContext: 'Kaufhaus Zentrum' },
  { situation: 'Nachricht der Krankenkasse', sceneHint: 'Unterlagen fehlen, bitte zurückrufen', durchsageContext: 'AOK Kundenservice' },
  { situation: 'Ansage im Freibad', sceneHint: 'Saisonende am Sonntag', durchsageContext: 'Städtisches Freibad' },
  { situation: 'Durchsage im Flughafen', sceneHint: 'Gate-Wechsel wegen Wetter', durchsageContext: 'Frankfurt Flughafen' },
  { situation: 'Ansage beim Supermarkt-Ausverkauf', sceneHint: 'Obst und Gemüse 50% Rabatt', durchsageContext: 'Supermarkt Edeka' },
  { situation: 'Anrufbeantworter Bürgeramt', sceneHint: 'Termin-Hotline am Montag', durchsageContext: 'Bürgeramt Stadt' },
  { situation: 'Radio-Verkehrsnachrichten', sceneHint: 'Stau auf der A5, Umleitung B3', durchsageContext: 'SWR3 Radio' },
  { situation: 'Durchsage in der S-Bahn', sceneHint: 'Bauarbeiten, Schienenersatzverkehr', durchsageContext: 'S-Bahn München' },
  { situation: 'Ansage im Museum', sceneHint: 'Sonderführung kostenlos', durchsageContext: 'Deutsches Museum' },
  { situation: 'Nachricht vom Handwerker', sceneHint: 'Heizungstermin bestätigen', durchsageContext: 'Handwerksbetrieb' },
  { situation: 'Durchsage am Bahnhof Gleiswechsel', sceneHint: 'ICE 523 jetzt Gleis 9', durchsageContext: 'DB Hauptbahnhof' },
  { situation: 'Anrufbeantworter Arzt', sceneHint: 'Praxis Urlaub, Vertretung Dr. Müller', durchsageContext: 'Hausarztpraxis' },
  { situation: 'Radio-Wetterbericht', sceneHint: 'Glatteiswarnung morgens', durchsageContext: 'Bayern 3' },
  { situation: 'Ansage im Schwimmbad', sceneHint: 'Kurzbahn wegen Kurs gesperrt', durchsageContext: 'Hallenbad' },
  { situation: 'Durchsage Flixbus', sceneHint: 'Fahrer-Wechsel 30 Minuten Pause', durchsageContext: 'Flixbus Fernbus' },
  { situation: 'Anrufbeantworter Fitnessstudio', sceneHint: 'Öffnungszeiten Feiertag', durchsageContext: 'FitnessFirst' },
  { situation: 'Ansage in der Straßenbahn', sceneHint: 'Endstation früher, Weiterfahrt mit Bus', durchsageContext: 'KVG Straßenbahn' },
  { situation: 'Radio-Werbung Stadtfest', sceneHint: 'Programm am Wochenende', durchsageContext: 'NDR Radio' },
  { situation: 'Nachricht vom Vermieter', sceneHint: 'Wasser wird abgestellt Dienstag', durchsageContext: 'Hausverwaltung' },
  { situation: 'Durchsage im Hotel', sceneHint: 'Frühstück ab 7 Uhr', durchsageContext: 'Hotel Lobby' },
  { situation: 'Ansage im Zoo', sceneHint: 'Pinguinfütterung um 15 Uhr', durchsageContext: 'Zoologischer Garten' },
  { situation: 'Anrufbeantworter Friseursalon', sceneHint: 'Termin absagen wegen Krankheit', durchsageContext: 'Friseur Schneider' },
  { situation: 'Durchsage im Möbelhaus', sceneHint: 'Kasse 3 geöffnet', durchsageContext: 'Möbel Höffner' },
  { situation: 'Radio-Staunachrichten', sceneHint: 'Unfall auf A8, 20 Minuten Verzögerung', durchsageContext: 'hr3 Radio' },
  { situation: 'Anrufbeantworter Schule', sceneHint: 'Elternabend verschoben', durchsageContext: 'Grundschule' },
  { situation: 'Ansage im Kino', sceneHint: 'Film mit Untertiteln', durchsageContext: 'CineStar' },
  { situation: 'Durchsage Flughafen', sceneHint: 'Boarding Gate B12', durchsageContext: 'Flughafen Hamburg' },
  { situation: 'Nachricht vom Nachbarn', sceneHint: 'Paket angenommen', durchsageContext: 'Anrufbeantworter privat' },
  { situation: 'Ansage im Stadion', sceneHint: 'Spiel beginnt in 10 Minuten', durchsageContext: 'Fußballstadion' },
  { situation: 'Durchsage im Baumarkt', sceneHint: 'Aktion auf Gartenpflanzen', durchsageContext: 'OBI Baumarkt' },
  { situation: 'Anrufbeantworter Zahnarzt', sceneHint: 'Notfall-Nummer am Wochenende', durchsageContext: 'Zahnarztpraxis' },
  { situation: 'Radio-Konzertankündigung', sceneHint: 'Klassik im Park am Samstag', durchsageContext: 'Kulturradio' },
  { situation: 'Ansage im Reisebüro', sceneHint: 'Kollege in Pause, bitte warten', durchsageContext: 'Reisebüro TUI' },
  { situation: 'Durchsage in der Apotheke', sceneHint: 'Rezept fertig zur Abholung', durchsageContext: 'Apotheke' },
  { situation: 'Nachricht vom Elektriker', sceneHint: 'Termin um 9 Uhr bestätigt', durchsageContext: 'Handwerksbetrieb Elektro' },
  { situation: 'Ansage im Kindergarten', sceneHint: 'Sommerfest Freitag', durchsageContext: 'Kita Sonnenblume' },
  { situation: 'Radio-Programminfo', sceneHint: 'Abendsendung geändert', durchsageContext: 'Deutschlandfunk' },
  { situation: 'Durchsage im Einkaufszentrum', sceneHint: 'Kinder-Spielecke jetzt offen', durchsageContext: 'Shopping-Center' },
  { situation: 'Anrufbeantworter Fahrlehrerin', sceneHint: 'Fahrstunde verschoben', durchsageContext: 'Fahrschule' },
  { situation: 'Ansage im Konzertsaal', sceneHint: 'Beginn 5 Minuten später', durchsageContext: 'Philharmonie' },
  { situation: 'Durchsage am Busbahnhof', sceneHint: 'Flixbus nach Berlin, Bussteig 4', durchsageContext: 'ZOB Busbahnhof' },
  { situation: 'Nachricht der Bibliothek', sceneHint: 'Buch überfällig, Gebühr', durchsageContext: 'Stadtbibliothek' },
  { situation: 'Radio-Aktion Blutspende', sceneHint: 'Termine morgen im DRK-Haus', durchsageContext: 'Regional-Radio' },
  { situation: 'Ansage im Theater', sceneHint: 'Pause 20 Minuten', durchsageContext: 'Stadttheater' },
  { situation: 'Durchsage am Gleis', sceneHint: 'ICE hat Verspätung 25 Minuten', durchsageContext: 'Bahnhof' },
  { situation: 'Anrufbeantworter Tierarzt', sceneHint: 'Urlaubsvertretung Dr. Weber', durchsageContext: 'Tierarztpraxis' },
  { situation: 'Ansage im Park', sceneHint: 'Rasenbereich frisch gesät', durchsageContext: 'Stadtpark' },
  { situation: 'Nachricht der Werkstatt', sceneHint: 'Auto fertig, bitte abholen', durchsageContext: 'KFZ-Werkstatt' },
  { situation: 'Durchsage im Hallenbad', sceneHint: 'Schwimmkurs jetzt', durchsageContext: 'Schwimmhalle' },
  { situation: 'Radio-Ansage Stau', sceneHint: 'Ring Autobahn voll', durchsageContext: 'Radio-Verkehr' },
  { situation: 'Ansage Reinigung', sceneHint: 'Boden nass, vorsichtig', durchsageContext: 'Einkaufszentrum' },
  { situation: 'Anrufbeantworter Reiseleiter', sceneHint: 'Treffpunkt Hotelhalle 8 Uhr', durchsageContext: 'Reiseleitung' },
  { situation: 'Durchsage im Regionalzug', sceneHint: 'Nächster Halt Hauptbahnhof', durchsageContext: 'Regio-Bahn' },
  { situation: 'Nachricht Lieferdienst', sceneHint: 'Paket morgen, bitte zu Hause', durchsageContext: 'DHL Lieferdienst' },
  { situation: 'Ansage Fitnessstudio', sceneHint: 'Sauna heute geschlossen', durchsageContext: 'McFit Fitnessstudio' },
  { situation: 'Durchsage im Autohaus', sceneHint: 'Sonderangebote diese Woche', durchsageContext: 'Autohaus Meyer' },
  { situation: 'Radio-Info Feiertag', sceneHint: 'Geschäfte morgen geschlossen', durchsageContext: 'Lokalradio' },
  { situation: 'Anrufbeantworter Optiker', sceneHint: 'Brille fertig, Abholung ab Mittwoch', durchsageContext: 'Fielmann Optiker' },
  { situation: 'Durchsage im Impfzentrum', sceneHint: 'Wartezeit 20 Minuten', durchsageContext: 'Impfzentrum' },
]

// Teil 2 — Dialog mit 5 Szenen (A2-specific)
export const HOREN_A2_T2: TopicData[] = [
  { situation: 'Paar plant Wochenend-Ausflug nach Köln', sceneHint: 'Zug, Hotel, Museum, Essen, Rückfahrt', dialogSituation: 'Paar plant Wochenende', roles: ['casual_male', 'casual_female'] },
  { situation: 'Zwei Kolleginnen planen Abteilungs-Ausflug', sceneHint: 'Wohin, wann, Budget, Transport, Essen', dialogSituation: 'Kolleginnen Büro', roles: ['professional_female', 'professional_female'] },
  { situation: 'Familie diskutiert Sommerurlaub an der Nordsee', sceneHint: 'Ort, Unterkunft, Tagesplan, Anreise, Kinderwunsch', dialogSituation: 'Familie zu Hause', roles: ['casual_female', 'casual_male'] },
  { situation: 'Freunde planen Geburtstagsparty für gemeinsame Freundin', sceneHint: 'Datum, Ort, Gäste, Geschenk, Torte', dialogSituation: 'Café am Nachmittag', roles: ['casual_male', 'casual_female'] },
  { situation: 'WG-Mitbewohner planen Einzug neuer Person', sceneHint: 'Zimmer, Kaution, Regeln, Mietvertrag, Einzugstermin', dialogSituation: 'WG-Küche', roles: ['casual_male', 'casual_female'] },
  { situation: 'Mutter und Tochter organisieren Schulanfang', sceneHint: 'Schulsachen, Ranzen, Kleidung, Schulweg, Mittag', dialogSituation: 'zu Hause vor Schulanfang', roles: ['casual_female', 'child'] },
  { situation: 'Zwei Freundinnen planen VHS-Kurs gemeinsam', sceneHint: 'Kurs, Termine, Preis, Anmeldung, Fahrt', dialogSituation: 'Telefongespräch', roles: ['casual_female', 'casual_female'] },
  { situation: 'Ehepaar plant Umzug in andere Stadt', sceneHint: 'Umzugsfirma, Kartons, Ummeldung, Einzug, Kosten', dialogSituation: 'Wohnzimmer am Abend', roles: ['casual_male', 'casual_female'] },
  { situation: 'Arbeitskollegen planen Betriebsausflug', sceneHint: 'Ziel, Teilnehmer, Programm, Essen, Fahrgemeinschaft', dialogSituation: 'Pause im Büro', roles: ['professional_male', 'professional_female'] },
  { situation: 'Mutter und Sohn gehen zur Einschulung einkaufen', sceneHint: 'Schulranzen, Hefte, Stifte, Schultüte, Preis', dialogSituation: 'Schreibwarenladen', roles: ['casual_female', 'child'] },
  { situation: 'Paar plant Hochzeitsfeier klein', sceneHint: 'Datum, Ort, Gäste, Essen, Musik', dialogSituation: 'zu Hause am Esstisch', roles: ['casual_male', 'casual_female'] },
  { situation: 'Freunde planen Ski-Urlaub in Österreich', sceneHint: 'Datum, Hütte, Anreise, Skikurs, Budget', dialogSituation: 'Café Treffen', roles: ['casual_male', 'casual_male'] },
  { situation: 'Eltern planen Kindergeburtstag im Kletterpark', sceneHint: 'Ort, Kinder, Einladung, Torte, Heimweg', dialogSituation: 'Küche', roles: ['casual_female', 'casual_male'] },
  { situation: 'Studenten planen Abschlussparty', sceneHint: 'Location, Gäste, DJ, Catering, Budget', dialogSituation: 'Universität Mensa', roles: ['casual_male', 'casual_female'] },
  { situation: 'Nachbarn organisieren Straßenfest', sceneHint: 'Datum, Erlaubnis, Essen, Getränke, Aufbau', dialogSituation: 'im Hof', roles: ['casual_male', 'elderly_female'] },
  { situation: 'Paar plant Renovierung der Wohnung', sceneHint: 'Räume, Farbe, Handwerker, Zeitplan, Kosten', dialogSituation: 'Wohnzimmer', roles: ['casual_male', 'casual_female'] },
  { situation: 'Frauen planen Wellness-Wochenende', sceneHint: 'Ort, Datum, Sauna, Massage, Anfahrt', dialogSituation: 'Telefon', roles: ['casual_female', 'casual_female'] },
  { situation: 'Vater und Tochter planen Besuch im Freizeitpark', sceneHint: 'Park, Karten, Essen, Fahrten, Uhrzeit', dialogSituation: 'zu Hause', roles: ['casual_male', 'child'] },
  { situation: 'Arbeitskollegen planen Weihnachtsfeier', sceneHint: 'Datum, Lokal, Menü, Geschenke, Programm', dialogSituation: 'Büroküche', roles: ['professional_female', 'professional_male'] },
  { situation: 'Eltern besprechen Kinderbetreuung', sceneHint: 'Kita, Oma, Ferien, Abholzeit, Kosten', dialogSituation: 'Abendessen zu Hause', roles: ['casual_male', 'casual_female'] },
  { situation: 'Paar plant Renovierung Küche', sceneHint: 'Möbel, Elektro, Handwerker, Zeit, Budget', dialogSituation: 'alte Küche', roles: ['casual_male', 'casual_female'] },
  { situation: 'Freunde planen Kino-Abend mit Essen', sceneHint: 'Film, Restaurant, Uhrzeit, Tickets, Treffpunkt', dialogSituation: 'WhatsApp-Anruf', roles: ['casual_male', 'casual_female'] },
  { situation: 'Paar organisiert Einzug der Schwiegereltern', sceneHint: 'Zimmer, Termin, Umzug, Regeln, Finanzen', dialogSituation: 'Wohnzimmer', roles: ['casual_female', 'casual_male'] },
  { situation: 'Kolleginnen planen Mittagspause gemeinsam', sceneHint: 'Restaurant, Menü, Preis, Uhrzeit, Rückkehr', dialogSituation: 'Büro', roles: ['professional_female', 'professional_female'] },
  { situation: 'Familie plant Besuch bei Oma', sceneHint: 'Datum, Mitbringen, Anreise, Übernachtung, Programm', dialogSituation: 'Küche zu Hause', roles: ['casual_male', 'casual_female'] },
  { situation: 'Freunde planen Fahrradtour am Wochenende', sceneHint: 'Strecke, Treffpunkt, Proviant, Wetter, Reparatur', dialogSituation: 'Park', roles: ['casual_male', 'casual_male'] },
  { situation: 'Paar plant Sprachreise nach Spanien', sceneHint: 'Schule, Dauer, Unterkunft, Preis, Flug', dialogSituation: 'Wohnzimmer', roles: ['casual_female', 'casual_male'] },
  { situation: 'Vater und Sohn besprechen neue Schule', sceneHint: 'Schulweg, Lehrer, Freunde, Mittag, Sport', dialogSituation: 'nach dem ersten Tag', roles: ['casual_male', 'child'] },
  { situation: 'Paar plant Renovierung Bad', sceneHint: 'Fliesen, Dusche, Handwerker, Dauer, Budget', dialogSituation: 'Bad', roles: ['casual_male', 'casual_female'] },
  { situation: 'Eltern besprechen Ferienlager für Kind', sceneHint: 'Ort, Datum, Preis, Programm, Anreise', dialogSituation: 'zu Hause', roles: ['casual_female', 'casual_male'] },
  { situation: 'Freundinnen planen Brunch am Sonntag', sceneHint: 'Café, Uhrzeit, Gäste, Geschenk, Fahrt', dialogSituation: 'Telefon', roles: ['casual_female', 'casual_female'] },
  { situation: 'Ehepaar plant Anschaffung eines Autos', sceneHint: 'Modell, Budget, Gebraucht/Neu, Versicherung, Probefahrt', dialogSituation: 'zu Hause am Laptop', roles: ['casual_male', 'casual_female'] },
  { situation: 'Freunde planen Besuch im Stadion', sceneHint: 'Spiel, Tickets, Anreise, Essen, Rückweg', dialogSituation: 'Kneipe', roles: ['casual_male', 'casual_male'] },
  { situation: 'Paar organisiert Umzug in WG', sceneHint: 'Zimmer, Möbel, Kaution, Regeln, Einzug', dialogSituation: 'Café', roles: ['casual_female', 'casual_male'] },
  { situation: 'Schwestern planen Geburtstagsgeschenk für Mutter', sceneHint: 'Idee, Preis, Versand, Karte, Feier', dialogSituation: 'Telefon', roles: ['casual_female', 'casual_female'] },
  { situation: 'Paar plant Spaziergang im Schwarzwald', sceneHint: 'Route, Dauer, Picknick, Anreise, Wetter', dialogSituation: 'Küche', roles: ['casual_male', 'casual_female'] },
  { situation: 'Familie plant Weihnachten bei Oma', sceneHint: 'Anreise, Essen, Geschenke, Übernachtung, Heimfahrt', dialogSituation: 'Wohnzimmer', roles: ['casual_female', 'casual_male'] },
  { situation: 'Freunde planen Escape-Room-Besuch', sceneHint: 'Raum, Uhrzeit, Gruppe, Preis, Treffpunkt', dialogSituation: 'Kneipe', roles: ['casual_male', 'casual_female'] },
  { situation: 'Eltern planen Zahnarztbesuche der Kinder', sceneHint: 'Termin, Praxis, Angst, Mittag, Schule', dialogSituation: 'zu Hause', roles: ['casual_female', 'casual_male'] },
  { situation: 'Paar plant Restaurantbesuch zum Jahrestag', sceneHint: 'Lokal, Reservierung, Menü, Kleidung, Uhrzeit', dialogSituation: 'am Abend zu Hause', roles: ['casual_male', 'casual_female'] },
  { situation: 'Kolleginnen planen VHS-Kochkurs', sceneHint: 'Kurs, Termin, Preis, Zutaten, Fahrt', dialogSituation: 'Büro', roles: ['professional_female', 'professional_female'] },
  { situation: 'Familie organisiert Besuch bei Opa im Krankenhaus', sceneHint: 'Besuchszeit, Mitbringsel, Auto, Kinder, Rückweg', dialogSituation: 'Flur', roles: ['casual_female', 'casual_male'] },
  { situation: 'Freunde planen Segeln am Bodensee', sceneHint: 'Schein, Boot, Wetter, Anreise, Proviant', dialogSituation: 'Restaurant', roles: ['casual_male', 'casual_male'] },
  { situation: 'Paar plant Besuch im Tierpark', sceneHint: 'Parkplatz, Tickets, Essen, Fahrt, Wetter', dialogSituation: 'zu Hause', roles: ['casual_male', 'casual_female'] },
  { situation: 'Arbeitskollegen planen Abschiedsfeier für Kollegin', sceneHint: 'Datum, Geschenk, Rede, Ort, Karte', dialogSituation: 'Büro', roles: ['professional_female', 'professional_male'] },
  { situation: 'Paar plant Besuch der Schwiegereltern', sceneHint: 'Datum, Mitbringsel, Essen, Übernachtung, Rückfahrt', dialogSituation: 'Abendessen', roles: ['casual_male', 'casual_female'] },
  { situation: 'Eltern planen Schulwahl für Kind', sceneHint: 'Gymnasium, Realschule, Probetag, Fahrt, Freunde', dialogSituation: 'zu Hause', roles: ['casual_female', 'casual_male'] },
  { situation: 'Kolleginnen planen Yoga-Kurs nach Feierabend', sceneHint: 'Studio, Termin, Preis, Matte, Fahrt', dialogSituation: 'Büro', roles: ['professional_female', 'professional_female'] },
  { situation: 'Paar plant Besuch des Christkindlmarkts', sceneHint: 'Stadt, Anreise, Essen, Geschenke, Heimfahrt', dialogSituation: 'Wohnzimmer', roles: ['casual_male', 'casual_female'] },
  { situation: 'Familie plant Sommerfest im Garten', sceneHint: 'Gäste, Grill, Musik, Getränke, Regenplan', dialogSituation: 'Garten', roles: ['casual_female', 'casual_male'] },
  { situation: 'Freunde planen Besuch eines Konzerts', sceneHint: 'Band, Tickets, Anreise, Stehplatz, Treffen', dialogSituation: 'Kneipe', roles: ['casual_male', 'casual_female'] },
  { situation: 'Paar plant Renovierung Kinderzimmer', sceneHint: 'Farbe, Möbel, Handwerker, Zeit, Kinderzimmer', dialogSituation: 'zu Hause', roles: ['casual_male', 'casual_female'] },
  { situation: 'Kolleginnen planen Ausflug in den Europapark', sceneHint: 'Datum, Gruppe, Tickets, Anreise, Essen', dialogSituation: 'Büro', roles: ['professional_female', 'professional_female'] },
  { situation: 'Familie organisiert Einschulung der Tochter', sceneHint: 'Feier, Gäste, Schultüte, Fotos, Essen', dialogSituation: 'Küche', roles: ['casual_female', 'casual_male'] },
  { situation: 'Paar plant Besuch im Theater', sceneHint: 'Stück, Tickets, Kleidung, Essen, Parkplatz', dialogSituation: 'Wohnzimmer', roles: ['casual_male', 'casual_female'] },
  { situation: 'Freundinnen planen Flohmarkt-Stand', sceneHint: 'Datum, Anmeldung, Waren, Preise, Aufbau', dialogSituation: 'Café', roles: ['casual_female', 'casual_female'] },
  { situation: 'Eltern besprechen Ausbildung des Sohnes', sceneHint: 'Beruf, Bewerbung, Lehrstellen, Umzug, Geld', dialogSituation: 'Wohnzimmer', roles: ['casual_female', 'casual_male'] },
  { situation: 'Paar plant Umzug nach Berlin', sceneHint: 'Job, Wohnung, Möbel, Umzugsfirma, Termin', dialogSituation: 'zu Hause', roles: ['casual_male', 'casual_female'] },
  { situation: 'Freunde planen gemeinsamen Schrebergarten', sceneHint: 'Parzelle, Kosten, Regeln, Zeit, Aufgaben', dialogSituation: 'im Garten', roles: ['casual_male', 'casual_male'] },
  { situation: 'Eltern planen Familienfotos', sceneHint: 'Fotograf, Ort, Kleidung, Termin, Preis', dialogSituation: 'Wohnzimmer', roles: ['casual_female', 'casual_male'] },
]

// Teil 3 — Interview (Moderator + eine Person)
export const HOREN_A2_T3: TopicData[] = [
  { situation: 'Radiointerview mit einer VHS-Dozentin', sceneHint: 'Sprachkurs, Teilnehmer, Motivation', interviewTopic: 'Deutschkurse für Neuankömmlinge', intervieweeProfession: 'VHS-Sprachdozentin' },
  { situation: 'Podcast-Interview mit einem Azubi', sceneHint: 'Ausbildung, Betrieb, Berufsschule', interviewTopic: 'Duale Ausbildung als Kfz-Mechatroniker', intervieweeProfession: 'Auszubildender Kfz-Mechatroniker' },
  { situation: 'Lokalradio mit einer Hebamme', sceneHint: 'Arbeit, Geburt, Familien', interviewTopic: 'Alltag einer Hebamme', intervieweeProfession: 'Hebamme' },
  { situation: 'Podcast mit einer Floristin', sceneHint: 'Laden, Aufträge, Kunden', interviewTopic: 'Beruf Floristin im Wandel', intervieweeProfession: 'Floristin' },
  { situation: 'Interview mit einem Taxifahrer', sceneHint: 'Schichten, Kunden, Stadt', interviewTopic: 'Arbeit als Taxifahrer in Berlin', intervieweeProfession: 'Taxifahrer' },
  { situation: 'Radiointerview mit einer Krankenschwester', sceneHint: 'Krankenhaus, Schicht, Patienten', interviewTopic: 'Pflegeberuf aktuell', intervieweeProfession: 'Krankenschwester' },
  { situation: 'Podcast mit einer Bäckerin', sceneHint: 'Morgens, Teig, Kunden', interviewTopic: 'Handwerksberuf Bäckerin', intervieweeProfession: 'Bäckerin' },
  { situation: 'Interview mit einem Altenpfleger', sceneHint: 'Heim, Bewohner, Alltag', interviewTopic: 'Arbeit in der Altenpflege', intervieweeProfession: 'Altenpfleger' },
  { situation: 'Lokalradio mit einer Erzieherin', sceneHint: 'Kita, Kinder, Team', interviewTopic: 'Beruf Erzieherin', intervieweeProfession: 'Erzieherin' },
  { situation: 'Podcast mit einem Bus-Fahrer', sceneHint: 'Linien, Fahrgäste, Wetter', interviewTopic: 'Alltag im Linienbus', intervieweeProfession: 'Busfahrer' },
  { situation: 'Interview mit einer Tierärztin', sceneHint: 'Praxis, Tiere, Besitzer', interviewTopic: 'Arbeit einer Tierärztin', intervieweeProfession: 'Tierärztin' },
  { situation: 'Podcast mit einem Postboten', sceneHint: 'Touren, Wetter, Kunden', interviewTopic: 'Arbeit als Postbote', intervieweeProfession: 'Postbote' },
  { situation: 'Radiointerview mit einer Grundschullehrerin', sceneHint: 'Klasse, Eltern, Unterricht', interviewTopic: 'Beruf Grundschullehrerin', intervieweeProfession: 'Grundschullehrerin' },
  { situation: 'Interview mit einem Hobby-Imker', sceneHint: 'Bienen, Honig, Hobby', interviewTopic: 'Imkern als Hobby', intervieweeProfession: 'Hobby-Imker' },
  { situation: 'Podcast mit einer Yogalehrerin', sceneHint: 'Kurse, Teilnehmer, Alltag', interviewTopic: 'Yoga als Beruf', intervieweeProfession: 'Yogalehrerin' },
  { situation: 'Interview mit einem Jugendtrainer', sceneHint: 'Verein, Kinder, Training', interviewTopic: 'Fußballtraining für Kinder', intervieweeProfession: 'Jugendtrainer Fußball' },
  { situation: 'Radiointerview mit einer Tänzerin', sceneHint: 'Ballett, Proben, Aufführung', interviewTopic: 'Alltag einer Balletttänzerin', intervieweeProfession: 'Balletttänzerin' },
  { situation: 'Podcast mit einer Bibliothekarin', sceneHint: 'Bibliothek, Bücher, Leser', interviewTopic: 'Beruf Bibliothekarin', intervieweeProfession: 'Bibliothekarin' },
  { situation: 'Interview mit einer Schneiderin', sceneHint: 'Atelier, Kunden, Nähen', interviewTopic: 'Handwerksberuf Schneiderin', intervieweeProfession: 'Schneiderin' },
  { situation: 'Podcast mit einem Landwirt', sceneHint: 'Hof, Tiere, Saison', interviewTopic: 'Leben auf einem Bauernhof', intervieweeProfession: 'Landwirt' },
  { situation: 'Interview mit einer Reiseleiterin', sceneHint: 'Gruppen, Länder, Alltag', interviewTopic: 'Beruf Reiseleiterin', intervieweeProfession: 'Reiseleiterin' },
  { situation: 'Radiointerview mit einem Gärtner', sceneHint: 'Park, Pflanzen, Saison', interviewTopic: 'Arbeit eines Stadtgärtners', intervieweeProfession: 'Stadtgärtner' },
  { situation: 'Podcast mit einer Fitnesstrainerin', sceneHint: 'Studio, Kurse, Kunden', interviewTopic: 'Beruf Fitnesstrainerin', intervieweeProfession: 'Fitnesstrainerin' },
  { situation: 'Interview mit einem Musiklehrer', sceneHint: 'Schule, Schüler, Instrument', interviewTopic: 'Musikunterricht heute', intervieweeProfession: 'Musiklehrer' },
  { situation: 'Podcast mit einer Fotografin', sceneHint: 'Hochzeiten, Portraits, Technik', interviewTopic: 'Selbstständig als Fotografin', intervieweeProfession: 'Fotografin' },
  { situation: 'Interview mit einem Koch', sceneHint: 'Restaurant, Menü, Team', interviewTopic: 'Arbeit in der Gastronomie', intervieweeProfession: 'Koch' },
  { situation: 'Radiointerview mit einer Kassiererin', sceneHint: 'Supermarkt, Schicht, Kunden', interviewTopic: 'Alltag im Einzelhandel', intervieweeProfession: 'Kassiererin' },
  { situation: 'Podcast mit einem Maler', sceneHint: 'Baustellen, Farben, Team', interviewTopic: 'Handwerk Maler', intervieweeProfession: 'Maler' },
  { situation: 'Interview mit einer Tierpflegerin im Zoo', sceneHint: 'Tiere, Fütterung, Besucher', interviewTopic: 'Arbeit mit Tieren im Zoo', intervieweeProfession: 'Tierpflegerin' },
  { situation: 'Podcast mit einer Kellnerin', sceneHint: 'Café, Gäste, Schicht', interviewTopic: 'Alltag als Kellnerin', intervieweeProfession: 'Kellnerin' },
  { situation: 'Interview mit einem Rentner und Ehrenamt', sceneHint: 'Verein, Freizeit, Hilfe', interviewTopic: 'Ehrenamt im Rentenalter', intervieweeProfession: 'Rentner im Ehrenamt' },
  { situation: 'Podcast mit einer Studentin', sceneHint: 'Studium, Nebenjob, WG', interviewTopic: 'Studium und Nebenjob', intervieweeProfession: 'Studentin' },
  { situation: 'Interview mit einem Fahrradkurier', sceneHint: 'Stadt, Touren, Wetter', interviewTopic: 'Arbeit als Fahrradkurier', intervieweeProfession: 'Fahrradkurier' },
  { situation: 'Radiointerview mit einer Zahnarzthelferin', sceneHint: 'Praxis, Patienten, Team', interviewTopic: 'Beruf Zahnarzthelferin', intervieweeProfession: 'Zahnarzthelferin' },
  { situation: 'Podcast mit einem Schornsteinfeger', sceneHint: 'Häuser, Kontrollen, Tradition', interviewTopic: 'Traditionsberuf Schornsteinfeger', intervieweeProfession: 'Schornsteinfeger' },
  { situation: 'Interview mit einer Hundetrainerin', sceneHint: 'Kurse, Hunde, Besitzer', interviewTopic: 'Beruf Hundetrainerin', intervieweeProfession: 'Hundetrainerin' },
  { situation: 'Podcast mit einem Rentner über Hobby', sceneHint: 'Modellbau, Zeit, Garten', interviewTopic: 'Hobbys im Ruhestand', intervieweeProfession: 'Rentner' },
  { situation: 'Interview mit einer Studentin im Auslandssemester', sceneHint: 'Spanien, Universität, Alltag', interviewTopic: 'Erasmus-Erfahrungen', intervieweeProfession: 'Erasmus-Studentin' },
  { situation: 'Podcast mit einem Barbier', sceneHint: 'Laden, Kunden, Trend', interviewTopic: 'Beruf Barbier heute', intervieweeProfession: 'Barbier' },
  { situation: 'Radiointerview mit einer Bloggerin', sceneHint: 'Texte, Themen, Leser', interviewTopic: 'Reiseblog als Nebenjob', intervieweeProfession: 'Reisebloggerin' },
  { situation: 'Interview mit einer Physiotherapeutin', sceneHint: 'Praxis, Patienten, Übungen', interviewTopic: 'Beruf Physiotherapeutin', intervieweeProfession: 'Physiotherapeutin' },
  { situation: 'Podcast mit einem Lebensmittelhändler', sceneHint: 'Laden, Waren, Kunden', interviewTopic: 'Kleiner Laden im Viertel', intervieweeProfession: 'Lebensmittelhändler' },
  { situation: 'Interview mit einer Optikerin', sceneHint: 'Geschäft, Kunden, Brillen', interviewTopic: 'Beruf Augenoptikerin', intervieweeProfession: 'Augenoptikerin' },
  { situation: 'Podcast mit einem Rettungssanitäter', sceneHint: 'Einsätze, Team, Stress', interviewTopic: 'Alltag im Rettungsdienst', intervieweeProfession: 'Rettungssanitäter' },
  { situation: 'Radiointerview mit einer Buchhändlerin', sceneHint: 'Laden, Lesungen, Kunden', interviewTopic: 'Buchladen im Viertel', intervieweeProfession: 'Buchhändlerin' },
  { situation: 'Interview mit einem Schwimmlehrer', sceneHint: 'Kurse, Kinder, Bad', interviewTopic: 'Schwimmunterricht heute', intervieweeProfession: 'Schwimmlehrer' },
  { situation: 'Podcast mit einer Pizzabäckerin', sceneHint: 'Ofen, Teig, Stress', interviewTopic: 'Pizzeria im Stadtviertel', intervieweeProfession: 'Pizzabäckerin' },
  { situation: 'Interview mit einer Briefmarken-Sammlerin', sceneHint: 'Sammlung, Tausch, Treffen', interviewTopic: 'Hobby Briefmarken sammeln', intervieweeProfession: 'Sammlerin (Hobby)' },
  { situation: 'Radiointerview mit einem Vater in Elternzeit', sceneHint: 'Kind, Alltag, Job', interviewTopic: 'Elternzeit für Väter', intervieweeProfession: 'Vater in Elternzeit' },
  { situation: 'Podcast mit einer Studentin nebenbei Nachhilfe', sceneHint: 'Schüler, Fach, Verdienst', interviewTopic: 'Nachhilfe als Nebenjob', intervieweeProfession: 'Nachhilfe-Studentin' },
  { situation: 'Interview mit einem Freiwilligen im FSJ', sceneHint: 'Krankenhaus, Kollegen, Erfahrung', interviewTopic: 'Freiwilliges soziales Jahr', intervieweeProfession: 'FSJ-Teilnehmer' },
  { situation: 'Podcast mit einer Hobbygärtnerin', sceneHint: 'Schrebergarten, Gemüse, Saison', interviewTopic: 'Eigenes Gemüse im Schrebergarten', intervieweeProfession: 'Hobbygärtnerin' },
  { situation: 'Radiointerview mit einem Rentner im Chor', sceneHint: 'Chor, Proben, Konzert', interviewTopic: 'Singen im Seniorenchor', intervieweeProfession: 'Rentner im Chor' },
  { situation: 'Interview mit einer Hausmeisterin', sceneHint: 'Haus, Bewohner, Aufgaben', interviewTopic: 'Beruf Hausmeisterin', intervieweeProfession: 'Hausmeisterin' },
  { situation: 'Podcast mit einer Influencerin', sceneHint: 'Posts, Follower, Alltag', interviewTopic: 'Influencerin als Beruf', intervieweeProfession: 'Social-Media-Influencerin' },
  { situation: 'Interview mit einem Bademeister', sceneHint: 'Freibad, Sicherheit, Kinder', interviewTopic: 'Beruf Bademeister im Sommer', intervieweeProfession: 'Bademeister' },
  { situation: 'Podcast mit einer Kinderbuchautorin', sceneHint: 'Schreiben, Kinder, Lesungen', interviewTopic: 'Kinderbücher schreiben', intervieweeProfession: 'Kinderbuchautorin' },
  { situation: 'Radiointerview mit einem Buslehrer', sceneHint: 'Fahrschule, Schüler, Prüfung', interviewTopic: 'Beruf Fahrlehrer', intervieweeProfession: 'Fahrlehrer' },
  { situation: 'Interview mit einer Caterer', sceneHint: 'Hochzeit, Team, Essen', interviewTopic: 'Catering für Veranstaltungen', intervieweeProfession: 'Caterer-Chefin' },
  { situation: 'Podcast mit einem Grundschulkind über Hobby', sceneHint: 'Fußball, Training, Freunde', interviewTopic: 'Fußball in der dritten Klasse', intervieweeProfession: 'Schulkind' },
]

// Teil 4 — 5 getrennte Dialoge (Thema übergreifend)
export const HOREN_A2_T4: TopicData[] = [
  { situation: 'Smalltalk im Büro-Alltag', sceneHint: 'Kaffee, Meeting, Feierabend, Projekt, Urlaub', fiveDialoguesTheme: 'Arbeitsalltag' },
  { situation: 'Einkaufen in verschiedenen Geschäften', sceneHint: 'Bäckerei, Apotheke, Metzgerei, Buchladen, Supermarkt', fiveDialoguesTheme: 'Einkaufen im Alltag' },
  { situation: 'Mit Behörden und Service sprechen', sceneHint: 'Bürgeramt, Krankenkasse, Bank, Post, Ausländerbehörde', fiveDialoguesTheme: 'Behörden-Kontakte' },
  { situation: 'Gespräche rund um die Wohnung', sceneHint: 'Vermieter, Nachbar, Handwerker, Putzplan, Strom', fiveDialoguesTheme: 'Wohnen und Nachbarschaft' },
  { situation: 'Im Kurs der Volkshochschule', sceneHint: 'Sprachkurs, Anmeldung, Material, Pause, Nachfragen', fiveDialoguesTheme: 'VHS-Alltag' },
  { situation: 'Im Krankenhaus und bei Ärzten', sceneHint: 'Hausarzt, Termin, Rezept, Krankschreibung, Apotheke', fiveDialoguesTheme: 'Gesundheit' },
  { situation: 'Freizeit am Wochenende', sceneHint: 'Kino, Café, Sport, Ausflug, Telefon', fiveDialoguesTheme: 'Wochenende' },
  { situation: 'Unterwegs mit der Bahn', sceneHint: 'Ticket, Anschluss, Sitzplatz, Verspätung, Ankunft', fiveDialoguesTheme: 'Bahnreise' },
  { situation: 'Gespräche rund um Essen', sceneHint: 'Restaurant, Lieferung, Kochen, Einkauf, Rezept', fiveDialoguesTheme: 'Essen und Trinken' },
  { situation: 'Schule und Kinder', sceneHint: 'Lehrerin, Schulweg, Hausaufgaben, Pausenbrot, Elternabend', fiveDialoguesTheme: 'Schulalltag' },
  { situation: 'Reiseplanung und Urlaub', sceneHint: 'Reisebüro, Hotel, Flug, Koffer, Rückkehr', fiveDialoguesTheme: 'Urlaub' },
  { situation: 'Rund um das Auto', sceneHint: 'Tanken, Werkstatt, Parkplatz, Versicherung, Unfall', fiveDialoguesTheme: 'Auto und Verkehr' },
  { situation: 'Freundschaften und Verabredungen', sceneHint: 'Treffen, Absage, Geburtstag, Anruf, Café', fiveDialoguesTheme: 'Freundschaften' },
  { situation: 'Familie und Verwandte', sceneHint: 'Oma, Geburtstag, Umzug, Kinder, Weihnachten', fiveDialoguesTheme: 'Familie' },
  { situation: 'Sport und Fitness', sceneHint: 'Fitnessstudio, Lauf, Verein, Verletzung, Training', fiveDialoguesTheme: 'Sport' },
  { situation: 'Geldangelegenheiten', sceneHint: 'Bankkonto, Überweisung, Sparen, Rechnung, Karte', fiveDialoguesTheme: 'Geld' },
  { situation: 'Telefongespräche privat', sceneHint: 'Absage, Einladung, Termin, Auskunft, Glückwunsch', fiveDialoguesTheme: 'Telefonieren' },
  { situation: 'Einkauf von Elektronik', sceneHint: 'Laptop, Handy, Garantie, Rückgabe, Akku', fiveDialoguesTheme: 'Elektronik kaufen' },
  { situation: 'Handwerker rund ums Haus', sceneHint: 'Heizung, Wasser, Fenster, Strom, Wand', fiveDialoguesTheme: 'Handwerker' },
  { situation: 'Büro und Homeoffice', sceneHint: 'Videokonferenz, Pause, E-Mail, Drucker, Kollegen', fiveDialoguesTheme: 'Homeoffice' },
  { situation: 'Kleidung und Mode', sceneHint: 'Anprobe, Größe, Rückgabe, Farbe, Sale', fiveDialoguesTheme: 'Kleidung' },
  { situation: 'Haustiere im Alltag', sceneHint: 'Tierarzt, Futter, Spaziergang, Urlaub, Nachbar', fiveDialoguesTheme: 'Haustiere' },
  { situation: 'Unterwegs zur Arbeit', sceneHint: 'Bus, Stau, Termin, Büro, Kaffee', fiveDialoguesTheme: 'Arbeitsweg' },
  { situation: 'Wetter und Aktivitäten', sceneHint: 'Regen, Sonne, Spaziergang, Ausflug, Kleidung', fiveDialoguesTheme: 'Wetter' },
  { situation: 'Einkauf auf dem Markt', sceneHint: 'Obst, Gemüse, Preis, Bio, Saison', fiveDialoguesTheme: 'Wochenmarkt' },
  { situation: 'Reparieren und Kaufen', sceneHint: 'Schuhe, Uhr, Fahrrad, Handy, Computer', fiveDialoguesTheme: 'Reparaturen' },
  { situation: 'Gespräche im Café', sceneHint: 'Bestellung, Bezahlen, Wifi, Freunde, Laptop', fiveDialoguesTheme: 'Café-Besuch' },
  { situation: 'Kultur und Veranstaltungen', sceneHint: 'Museum, Theater, Konzert, Kino, Lesung', fiveDialoguesTheme: 'Kultur' },
  { situation: 'Nachbarschaftliche Hilfe', sceneHint: 'Paket, Pflanzen, Kind, Schlüssel, Leiter', fiveDialoguesTheme: 'Nachbarn helfen' },
  { situation: 'Lernen und Hobbys', sceneHint: 'Sprache, Gitarre, Tanzen, Lesen, Malen', fiveDialoguesTheme: 'Hobbys' },
  { situation: 'Rund um die Geburt', sceneHint: 'Hebamme, Baby, Kurs, Kita, Elternzeit', fiveDialoguesTheme: 'Baby und Familie' },
  { situation: 'Freundschaften pflegen', sceneHint: 'Geburtstag, Umzug, Hochzeit, Karte, Anruf', fiveDialoguesTheme: 'Soziale Kontakte' },
  { situation: 'Kleine Probleme lösen', sceneHint: 'verlorener Schlüssel, Zug verpasst, Handy leer, Regen, Pass', fiveDialoguesTheme: 'Alltagsprobleme' },
  { situation: 'Im Restaurant bestellen', sceneHint: 'Reservierung, Karte, Allergie, Bezahlen, Kritik', fiveDialoguesTheme: 'Restaurant' },
  { situation: 'Behördliche Termine', sceneHint: 'Anmeldung, Pass, Steuer, Führerschein, Arbeitsamt', fiveDialoguesTheme: 'Ämter' },
  { situation: 'Fahrradausflüge', sceneHint: 'Route, Picknick, Reparatur, Wetter, Rückkehr', fiveDialoguesTheme: 'Fahrradfahren' },
  { situation: 'Geburtstagsvorbereitung', sceneHint: 'Torte, Einladung, Geschenke, Deko, Gäste', fiveDialoguesTheme: 'Geburtstag' },
  { situation: 'Umzugstag', sceneHint: 'Kisten, Helfer, Schlüssel, Vermieter, Pizza', fiveDialoguesTheme: 'Umzug' },
  { situation: 'Kleine Katastrophen im Haushalt', sceneHint: 'Waschmaschine, Milch, Ofen, Licht, Tür', fiveDialoguesTheme: 'Haushaltspannen' },
  { situation: 'Urlaubsvorbereitung', sceneHint: 'Koffer, Haustier, Nachbarn, Pass, Flug', fiveDialoguesTheme: 'Vor der Reise' },
  { situation: 'Zusammenleben in der WG', sceneHint: 'Küche, Putzen, Müll, Besuch, Bad', fiveDialoguesTheme: 'WG-Leben' },
  { situation: 'Kinder und Schule', sceneHint: 'Hausaufgaben, Streit, Sport, Freunde, Noten', fiveDialoguesTheme: 'Kinder und Schule' },
  { situation: 'Alltag mit Baby', sceneHint: 'Stillen, Schlaf, Windeln, Kinderwagen, Arzt', fiveDialoguesTheme: 'Baby-Alltag' },
  { situation: 'Kleine Einkäufe', sceneHint: 'Brot, Milch, Obst, Blumen, Zeitung', fiveDialoguesTheme: 'Kleinkauf' },
  { situation: 'Gespräche beim Sport', sceneHint: 'Lauftreff, Tennis, Schwimmen, Joggen, Fußball', fiveDialoguesTheme: 'Sport-Gespräche' },
  { situation: 'Rund um den Verein', sceneHint: 'Sitzung, Mitgliedsbeitrag, Turnier, Fest, Ehrung', fiveDialoguesTheme: 'Vereinsleben' },
  { situation: 'Babysitter organisieren', sceneHint: 'Abend, Kinder, Schlafen, Bezahlung, Kontakte', fiveDialoguesTheme: 'Babysitten' },
  { situation: 'Online-Einkauf', sceneHint: 'Bestellung, Paket, Rückgabe, Zahlung, Bewertung', fiveDialoguesTheme: 'Online-Shopping' },
  { situation: 'Gebrauchtwaren verkaufen', sceneHint: 'Kleinanzeigen, Treffen, Preis, Abholung, Geld', fiveDialoguesTheme: 'Gebrauchtverkauf' },
  { situation: 'Im Freizeitbad', sceneHint: 'Schließfach, Rutsche, Sauna, Snackbar, Eltern', fiveDialoguesTheme: 'Freizeitbad' },
  { situation: 'Internetprobleme zu Hause', sceneHint: 'Router, Provider, WLAN, Homeoffice, Fernsehen', fiveDialoguesTheme: 'Internet' },
  { situation: 'Regionale Feste', sceneHint: 'Stadtfest, Weinfest, Karneval, Weihnachtsmarkt, Kirmes', fiveDialoguesTheme: 'Feste' },
  { situation: 'Anrufe zu Dienstleistungen', sceneHint: 'Strom, Gas, Versicherung, Internet, Zeitung', fiveDialoguesTheme: 'Kundenservice' },
  { situation: 'Essen zum Mitnehmen', sceneHint: 'Dönerladen, Pizza, Sushi, Burger, Salat', fiveDialoguesTheme: 'To-go' },
  { situation: 'Wellness und Entspannung', sceneHint: 'Massage, Sauna, Yoga, Pediküre, Friseur', fiveDialoguesTheme: 'Wellness' },
  { situation: 'Erste Hilfe und Notfälle', sceneHint: 'Wunde, Fieber, Notruf, Apotheke, Krankenwagen', fiveDialoguesTheme: 'Notfälle' },
  { situation: 'Rund ums Rad', sceneHint: 'Reifen, Helm, Schloss, Reparatur, Diebstahl', fiveDialoguesTheme: 'Fahrrad' },
  { situation: 'Begegnungen auf Reisen', sceneHint: 'Zug, Hotel, Taxi, Restaurant, Flughafen', fiveDialoguesTheme: 'Reise-Begegnungen' },
  { situation: 'Geburtstagsanrufe', sceneHint: 'Glückwunsch, Geschenk, Einladung, Dank, Erinnerung', fiveDialoguesTheme: 'Geburtstagsanrufe' },
  { situation: 'Rund um Haustiere', sceneHint: 'Hund, Katze, Fisch, Vogel, Urlaub', fiveDialoguesTheme: 'Tiere' },
]
