// Темы для модуля Hören B1 — все 4 Teile.
// Поля: {situation, sceneHint} — основные для промптов.

import type { TopicData } from '@/lib/topic-sampler'

// Teil 1 — kurze Durchsagen / Nachrichten / Mono-Texte
export const HOREN_B1_T1: TopicData[] = [
  { situation: 'Anrufbeantworter eines potenziellen Arbeitgebers', sceneHint: 'Einladung zum Vorstellungsgespräch', durchsageContext: 'Personalabteilung' },
  { situation: 'Durchsage im ICE nach Stuttgart', sceneHint: 'Verspätung durch Signalstörung, Anschluss', durchsageContext: 'Deutsche Bahn' },
  { situation: 'Nachricht der Krankenkasse', sceneHint: 'Beitragsanpassung, Online-Portal', durchsageContext: 'Techniker Krankenkasse' },
  { situation: 'Anrufbeantworter Immobilienmakler', sceneHint: 'Besichtigungstermin, Unterlagen', durchsageContext: 'Maklerbüro' },
  { situation: 'Durchsage Flughafen Frankfurt', sceneHint: 'Gate-Änderung, Boarding-Prozedur', durchsageContext: 'Flughafen Frankfurt' },
  { situation: 'Radio-Wirtschaftsnachrichten', sceneHint: 'Fachkräftemangel in Handwerk', durchsageContext: 'Deutschlandfunk' },
  { situation: 'Nachricht einer Behörde', sceneHint: 'Antrag unvollständig, Nachreichung', durchsageContext: 'Ausländerbehörde' },
  { situation: 'Anrufbeantworter des Vermieters', sceneHint: 'Nebenkostenabrechnung, Nachzahlung', durchsageContext: 'Hausverwaltung' },
  { situation: 'Durchsage in der Universität', sceneHint: 'Prüfungstermin verschoben', durchsageContext: 'Universität Prüfungsamt' },
  { situation: 'Radio-Umweltnachrichten', sceneHint: 'Feinstaubbelastung, Fahrverbot', durchsageContext: 'MDR Aktuell' },
  { situation: 'Nachricht Jobcenter', sceneHint: 'Termin mit Fallmanager verschieben', durchsageContext: 'Arbeitsagentur' },
  { situation: 'Anrufbeantworter der Elternvertreterin', sceneHint: 'Elternabend, Themen', durchsageContext: 'Gymnasium' },
  { situation: 'Durchsage Hauptbahnhof', sceneHint: 'Generalstreik, Ausfälle', durchsageContext: 'DB-Hauptbahnhof' },
  { situation: 'Nachricht Versicherung', sceneHint: 'Schadenbearbeitung, Gutachter', durchsageContext: 'Allianz' },
  { situation: 'Radio-Kulturtipps', sceneHint: 'Theaterpremiere, Lesung', durchsageContext: 'WDR5' },
  { situation: 'Anrufbeantworter Steuerberater', sceneHint: 'Fristen Steuererklärung', durchsageContext: 'Steuerkanzlei' },
  { situation: 'Durchsage in der Klinik', sceneHint: 'Besuchszeiten geändert', durchsageContext: 'Universitätsklinikum' },
  { situation: 'Nachricht der Bank', sceneHint: 'Kreditrate, Rückfrage', durchsageContext: 'Sparkasse' },
  { situation: 'Radio-Debattenreihe', sceneHint: 'Ankündigung Thema Klimawandel', durchsageContext: 'Deutschlandfunk Kultur' },
  { situation: 'Anrufbeantworter Autowerkstatt', sceneHint: 'Reparatur teurer als erwartet', durchsageContext: 'Werkstatt' },
  { situation: 'Durchsage Uni-Bibliothek', sceneHint: 'verlängerte Öffnungszeiten', durchsageContext: 'UB Ausleihe' },
  { situation: 'Nachricht des Fitnessstudios', sceneHint: 'Mitgliedschaft Verlängerung', durchsageContext: 'Fitnessstudio' },
  { situation: 'Radio-Nachrichten Verkehrspolitik', sceneHint: 'Deutschlandticket Preisanhebung', durchsageContext: 'NDR Info' },
  { situation: 'Anrufbeantworter Physiotherapie', sceneHint: 'Rezept abgelaufen, Neuverordnung', durchsageContext: 'Praxis Physiotherapie' },
  { situation: 'Durchsage Einwohnermeldeamt', sceneHint: 'Wartezeit reduziert durch Online-Termine', durchsageContext: 'Bürgeramt' },
  { situation: 'Nachricht einer Immobilienverwaltung', sceneHint: 'Modernisierung, Mieterhöhung', durchsageContext: 'Hausverwaltung' },
  { situation: 'Radio-Verbraucherinfo', sceneHint: 'Rückruf Waschmaschine', durchsageContext: 'SWR Aktuell' },
  { situation: 'Anrufbeantworter Kita-Leitung', sceneHint: 'Betreuungsengpass Streik', durchsageContext: 'Kita Verwaltung' },
  { situation: 'Durchsage im Flughafen', sceneHint: 'Verloren-Found, Gepäck', durchsageContext: 'Flughafen Düsseldorf' },
  { situation: 'Nachricht Kraftfahrtbundesamt', sceneHint: 'Rückruf Airbags', durchsageContext: 'KBA' },
  { situation: 'Radio-Wissenschaftsnachrichten', sceneHint: 'Fortschritt E-Autos', durchsageContext: 'rbb Radio' },
  { situation: 'Anrufbeantworter Anwaltskanzlei', sceneHint: 'Termin Mandantengespräch', durchsageContext: 'Rechtsanwalt' },
  { situation: 'Durchsage Messegelände', sceneHint: 'Messeende, Eingänge', durchsageContext: 'Messe Hannover' },
  { situation: 'Nachricht Studienberatung', sceneHint: 'Beratungstermin', durchsageContext: 'Universität Studienberatung' },
  { situation: 'Radio-Wetterbericht', sceneHint: 'Unwetter-Warnung, Sturzfluten', durchsageContext: 'Bayern 3' },
  { situation: 'Anrufbeantworter IT-Support', sceneHint: 'Ticket bearbeitet, Lösung', durchsageContext: 'Kundensupport' },
  { situation: 'Durchsage im Theater', sceneHint: 'Verlegung Vorstellung', durchsageContext: 'Schauspielhaus' },
  { situation: 'Nachricht Elterngeldstelle', sceneHint: 'Antrag genehmigt, Auszahlung', durchsageContext: 'Elterngeldstelle' },
  { situation: 'Radio-Gesundheitstipps', sceneHint: 'Grippewelle, Impfen', durchsageContext: 'hr3' },
  { situation: 'Anrufbeantworter Zeitschriftenverlag', sceneHint: 'Abonnement-Verlängerung', durchsageContext: 'Abo-Service' },
  { situation: 'Durchsage im Prüfungszentrum', sceneHint: 'Ablauf der Prüfung', durchsageContext: 'TELC-Prüfungszentrum' },
  { situation: 'Nachricht der GEZ', sceneHint: 'Rundfunkbeitrag, Online-Anmeldung', durchsageContext: 'Beitragsservice' },
  { situation: 'Radio-Berufswelt', sceneHint: 'Homeoffice vs. Büro', durchsageContext: 'Deutschlandfunk Kultur' },
  { situation: 'Anrufbeantworter Reiseveranstalter', sceneHint: 'Umbuchung wegen Streik', durchsageContext: 'Reisebüro' },
  { situation: 'Durchsage bei Streik', sceneHint: 'öffentlicher Nahverkehr', durchsageContext: 'Verkehrsbetriebe' },
  { situation: 'Nachricht Handwerker', sceneHint: 'Kostenvoranschlag, Termin', durchsageContext: 'Sanitärbetrieb' },
  { situation: 'Radio-Politikdiskussion', sceneHint: 'Bundestagsdebatte zu Rente', durchsageContext: 'Deutschlandfunk' },
  { situation: 'Anrufbeantworter einer Kollegin', sceneHint: 'Projekt-Frage, Rückruf', durchsageContext: 'Mobiltelefon' },
  { situation: 'Durchsage Flughafen', sceneHint: 'Annullierung wegen Wetter', durchsageContext: 'Flughafen München' },
  { situation: 'Nachricht Sozialamt', sceneHint: 'Nachweise fehlen', durchsageContext: 'Sozialamt' },
  { situation: 'Radio-Debatte Digitalisierung', sceneHint: 'Homeoffice-Trends', durchsageContext: 'Kulturradio' },
  { situation: 'Anrufbeantworter Berufsberatung', sceneHint: 'Umschulungstermin', durchsageContext: 'Agentur für Arbeit' },
  { situation: 'Durchsage im Uni-Klinikum', sceneHint: 'Corona-Regeln neu', durchsageContext: 'Klinikum' },
  { situation: 'Nachricht Schornsteinfeger', sceneHint: 'Kontrolle angekündigt', durchsageContext: 'Bezirksschornsteinfeger' },
  { situation: 'Radio-Reisebericht', sceneHint: 'Sommerurlaub teurer', durchsageContext: 'SWR2' },
  { situation: 'Anrufbeantworter Psychotherapeut', sceneHint: 'Warteliste, Ersttermin', durchsageContext: 'Psychotherapie' },
  { situation: 'Durchsage im Uni-Hörsaal', sceneHint: 'Raumwechsel Vorlesung', durchsageContext: 'Universität Gebäude H' },
  { situation: 'Nachricht Finanzamt', sceneHint: 'Bescheid verfügbar, Elster', durchsageContext: 'Finanzamt' },
  { situation: 'Radio-Politikkommentar', sceneHint: 'Energiewende-Debatte', durchsageContext: 'Deutschlandfunk' },
  { situation: 'Anrufbeantworter Notar', sceneHint: 'Termin Erbschaftsurkunde', durchsageContext: 'Notariat' },
  { situation: 'Durchsage in der Volkshochschule', sceneHint: 'Prüfungen TELC B1', durchsageContext: 'Volkshochschule' },
]

// Teil 2 — Monolog oder Vortrag (Führung, Präsentation, Vorlesung)
export const HOREN_B1_T2: TopicData[] = [
  { situation: 'Stadtführung durch die Hamburger Speicherstadt', sceneHint: 'Geschichte, UNESCO, Gebäude', dialogSituation: 'geführte Stadttour', roles: ['professional_female'] },
  { situation: 'Werksführung in einer Brauerei in Franken', sceneHint: 'Brauprozess, Rohstoffe, Tradition', dialogSituation: 'Werksbesichtigung', roles: ['professional_male'] },
  { situation: 'Kurzvortrag zu Mietrecht in Deutschland', sceneHint: 'Kaution, Kündigung, Schönheitsreparaturen', dialogSituation: 'Mieterbund-Info', roles: ['professional_male'] },
  { situation: 'Führung durch das Deutsche Museum München', sceneHint: 'Luftfahrt, Technik, Ausstellungen', dialogSituation: 'Museumsführung', roles: ['professional_female'] },
  { situation: 'Vortrag zum Rundfunkbeitrag', sceneHint: 'Anmeldung, Befreiung, Gebühr', dialogSituation: 'Bürgerinformation', roles: ['professional_female'] },
  { situation: 'Präsentation Studienangebot Fachhochschule', sceneHint: 'Studiengänge, Bewerbung, NC', dialogSituation: 'Informationsveranstaltung', roles: ['professional_male'] },
  { situation: 'Stadtführung Weimar auf Goethes Spuren', sceneHint: 'Schlösser, Dichter, Park', dialogSituation: 'Literaturtour', roles: ['professional_female'] },
  { situation: 'Vortrag Krankenkasse: gesetzlich vs. privat', sceneHint: 'Beiträge, Leistungen, Wechsel', dialogSituation: 'Aufklärung im Betriebsratsaal', roles: ['professional_male'] },
  { situation: 'Werksführung bei einem Autohersteller', sceneHint: 'Produktion, Roboter, E-Autos', dialogSituation: 'Werkshalle', roles: ['professional_male'] },
  { situation: 'Vortrag zum dualen Studium', sceneHint: 'Partnerunternehmen, Praxis, Gehalt', dialogSituation: 'Karriere-Messe', roles: ['professional_female'] },
  { situation: 'Führung im Bundestag', sceneHint: 'Parlament, Plenarsaal, Fraktionen', dialogSituation: 'Reichstagsgebäude', roles: ['professional_male'] },
  { situation: 'Vortrag Elterngeld und Elternzeit', sceneHint: 'Antrag, Dauer, Partnermonate', dialogSituation: 'Familienzentrum', roles: ['professional_female'] },
  { situation: 'Führung durch eine Glashütte', sceneHint: 'Tradition, Arbeit, Verkauf', dialogSituation: 'Handwerksbetrieb', roles: ['professional_male'] },
  { situation: 'Kurzvortrag zum Deutschland-Ticket', sceneHint: 'Preis, Gültigkeit, Buchung', dialogSituation: 'Bürgerinfo', roles: ['professional_female'] },
  { situation: 'Vorlesung Soziologie', sceneHint: 'Digitalisierung der Arbeitswelt', dialogSituation: 'Universität Hörsaal', roles: ['professional_male'] },
  { situation: 'Führung durch den Zoo Berlin', sceneHint: 'Artenvielfalt, Schutzprogramme, Pandas', dialogSituation: 'Zooführung', roles: ['professional_female'] },
  { situation: 'Vortrag Bewerbung in Deutschland', sceneHint: 'Lebenslauf, Anschreiben, Vorstellung', dialogSituation: 'Jobcenter-Workshop', roles: ['professional_female'] },
  { situation: 'Werksführung Schokoladenfabrik', sceneHint: 'Kakao, Produktion, Sorten', dialogSituation: 'Fabrikbesichtigung', roles: ['professional_male'] },
  { situation: 'Vortrag Altersvorsorge', sceneHint: 'Rente, Riester, private Vorsorge', dialogSituation: 'Verbraucherzentrale', roles: ['professional_male'] },
  { situation: 'Führung durch das Schloss Sanssouci', sceneHint: 'Potsdam, Friedrich II., Gärten', dialogSituation: 'Schlosstour', roles: ['professional_female'] },
  { situation: 'Präsentation zu Homeoffice-Regeln', sceneHint: 'Gesetz, Arbeitszeit, Ausstattung', dialogSituation: 'Betriebsrat', roles: ['professional_female'] },
  { situation: 'Vorlesung Medizin', sceneHint: 'Prävention Herz-Kreislauf', dialogSituation: 'Uniklinik Hörsaal', roles: ['professional_male'] },
  { situation: 'Stadtführung Bamberg', sceneHint: 'Altstadt UNESCO, Brauereien', dialogSituation: 'Altstadt', roles: ['professional_female'] },
  { situation: 'Vortrag zu Ausbildung vs. Studium', sceneHint: 'Gehalt, Dauer, Perspektive', dialogSituation: 'Berufsinformationszentrum', roles: ['professional_male'] },
  { situation: 'Werksführung Bäckerei-Großbetrieb', sceneHint: 'Backstraßen, Logistik, Team', dialogSituation: 'Backstube', roles: ['professional_female'] },
  { situation: 'Vortrag Umwelt und Recycling', sceneHint: 'Gelbe Tonne, Pfand, Biomüll', dialogSituation: 'Stadtwerke-Veranstaltung', roles: ['professional_female'] },
  { situation: 'Führung durch das Pergamonmuseum', sceneHint: 'Babylonisches Tor, Restaurierung', dialogSituation: 'Museum', roles: ['professional_male'] },
  { situation: 'Vortrag zum deutschen Schulsystem', sceneHint: 'Gymnasium, Realschule, Gesamtschule', dialogSituation: 'Elternabend', roles: ['professional_female'] },
  { situation: 'Werksführung Maschinenbau', sceneHint: 'CNC, Industrie 4.0, Fachkräfte', dialogSituation: 'Produktionshalle', roles: ['professional_male'] },
  { situation: 'Vorlesung Klimawandel', sceneHint: 'CO2, Verkehr, Energie', dialogSituation: 'TU Hörsaal', roles: ['professional_male'] },
  { situation: 'Stadtführung Quedlinburg', sceneHint: 'Fachwerk, Welterbe, Geschichte', dialogSituation: 'Altstadttour', roles: ['professional_female'] },
  { situation: 'Vortrag Arbeitsvertrag', sceneHint: 'Probezeit, Kündigung, Urlaub', dialogSituation: 'IHK-Veranstaltung', roles: ['professional_male'] },
  { situation: 'Führung durch eine Käserei', sceneHint: 'Milch, Reifung, Regional', dialogSituation: 'Hofbesichtigung', roles: ['professional_female'] },
  { situation: 'Vortrag Wohnungssuche', sceneHint: 'WBS, Makler, Besichtigung', dialogSituation: 'Mieterberatung', roles: ['professional_female'] },
  { situation: 'Vorlesung Psychologie Stress', sceneHint: 'Arbeit, Familie, Gesundheit', dialogSituation: 'Universität', roles: ['professional_male'] },
  { situation: 'Werksführung Windkraftanlage', sceneHint: 'Energie, Technik, Umwelt', dialogSituation: 'Windpark', roles: ['professional_male'] },
  { situation: 'Vortrag zur Einbürgerung', sceneHint: 'Voraussetzungen, Test, Ablauf', dialogSituation: 'Integrationskurs', roles: ['professional_female'] },
  { situation: 'Führung Bundesrat', sceneHint: 'Länderkammer, Beschlüsse', dialogSituation: 'Politische Bildung', roles: ['professional_male'] },
  { situation: 'Vortrag Verbraucherrechte', sceneHint: 'Rückgabe, Widerruf, Online', dialogSituation: 'Verbraucherzentrale', roles: ['professional_female'] },
  { situation: 'Werksführung Textilfabrik', sceneHint: 'Stoffe, Produktion, Design', dialogSituation: 'Fabrikhalle', roles: ['professional_female'] },
  { situation: 'Vorlesung BWL Unternehmensgründung', sceneHint: 'Businessplan, Finanzierung, Markt', dialogSituation: 'Hochschule', roles: ['professional_male'] },
  { situation: 'Stadtführung Görlitz', sceneHint: 'Grenzstadt, Filmkulisse', dialogSituation: 'Altstadttour', roles: ['professional_female'] },
  { situation: 'Vortrag Kreditverträge', sceneHint: 'Zinsen, Laufzeit, Risiken', dialogSituation: 'Bankberatung', roles: ['professional_male'] },
  { situation: 'Führung durch ein Kloster', sceneHint: 'Tradition, Alltag, Herstellung', dialogSituation: 'Klosterführung', roles: ['professional_male'] },
  { situation: 'Vortrag Steuererklärung', sceneHint: 'Elster, Werbungskosten, Pauschale', dialogSituation: 'VHS-Kurs', roles: ['professional_female'] },
  { situation: 'Vorlesung Geschichte DDR', sceneHint: 'Mauer, Alltag, Wende', dialogSituation: 'Universität Geschichte', roles: ['professional_male'] },
  { situation: 'Werksführung Glasbläserei', sceneHint: 'Tradition, Handwerk, Besucher', dialogSituation: 'Glashütte', roles: ['professional_male'] },
  { situation: 'Vortrag Familienplanung', sceneHint: 'Kita, Elternzeit, Job', dialogSituation: 'Familienzentrum', roles: ['professional_female'] },
  { situation: 'Führung KZ-Gedenkstätte', sceneHint: 'Geschichte, Verantwortung, Erinnern', dialogSituation: 'Gedenkstätte', roles: ['professional_female'] },
  { situation: 'Vortrag Digitalisierung', sceneHint: 'Homeoffice, KI, Datenschutz', dialogSituation: 'IHK-Vortragsreihe', roles: ['professional_male'] },
  { situation: 'Werksführung Solarfabrik', sceneHint: 'Energie, Zukunft, Arbeitsplätze', dialogSituation: 'Solarpark', roles: ['professional_female'] },
  { situation: 'Vortrag Integration im Beruf', sceneHint: 'Anerkennung, Sprache, Kollegen', dialogSituation: 'Integrationsbeauftragte', roles: ['professional_female'] },
  { situation: 'Vorlesung Pädagogik', sceneHint: 'Kinder und Medien', dialogSituation: 'PH Hörsaal', roles: ['professional_female'] },
  { situation: 'Stadtführung Lübeck Hanse', sceneHint: 'Backstein, Marzipan, Hafen', dialogSituation: 'Altstadtführung', roles: ['professional_male'] },
  { situation: 'Vortrag Mülltrennung', sceneHint: 'Regeln, Tipps, Umwelt', dialogSituation: 'Stadtwerke', roles: ['professional_female'] },
  { situation: 'Führung Automuseum', sceneHint: 'Oldtimer, Marken, Geschichte', dialogSituation: 'Museum', roles: ['professional_male'] },
  { situation: 'Vortrag Bewerbung für Azubis', sceneHint: 'Unterlagen, Vorstellungsgespräch', dialogSituation: 'Schule', roles: ['professional_female'] },
  { situation: 'Werksführung Recyclinghof', sceneHint: 'Prozess, Umwelt, Besucher', dialogSituation: 'Wertstoffhof', roles: ['professional_male'] },
  { situation: 'Vortrag E-Mobilität', sceneHint: 'Ladeinfrastruktur, Kosten, Zukunft', dialogSituation: 'Stadtwerke', roles: ['professional_male'] },
  { situation: 'Führung durch das Jüdische Museum', sceneHint: 'Geschichte, Ausstellung, Dialog', dialogSituation: 'Museum Berlin', roles: ['professional_female'] },
]

// Teil 3 — Diskussion oder Alltagsdialog (B1: Meinungsaustausch, Beratung)
export const HOREN_B1_T3: TopicData[] = [
  { situation: 'Diskussion im Familienrat zu Umzug nach Berlin', sceneHint: 'Pro-Kontra, Kinder, Job, Wohnung, Schule', interviewTopic: 'Umzug wegen Jobangebot', intervieweeProfession: 'Familienvater und Mutter' },
  { situation: 'Talk-Runde zum Thema Homeoffice', sceneHint: 'Produktivität, Sozialkontakte, Kinderbetreuung', interviewTopic: 'Homeoffice vs. Büroarbeit', intervieweeProfession: 'Unternehmensberaterin' },
  { situation: 'Diskussion Studienfachwahl', sceneHint: 'Leidenschaft vs. Sicherheit, Eltern, Freunde', interviewTopic: 'Studienwahl nach dem Abi', intervieweeProfession: 'Studienberater' },
  { situation: 'Gespräch in der Mieterberatung', sceneHint: 'Kündigung, Fristen, Rechte', interviewTopic: 'Kündigung durch Vermieter', intervieweeProfession: 'Mieterbund-Berater' },
  { situation: 'Radio-Diskussion Digitalisierung', sceneHint: 'Datenschutz, KI, Arbeitswelt', interviewTopic: 'Künstliche Intelligenz am Arbeitsplatz', intervieweeProfession: 'Medienforscher' },
  { situation: 'Elterngespräch mit Lehrerin', sceneHint: 'Noten, Motivation, Nachhilfe', interviewTopic: 'Leistungsschwäche des Kindes', intervieweeProfession: 'Gymnasiallehrerin' },
  { situation: 'Diskussion zu Elterngeld und Karriere', sceneHint: 'Aufteilung, Karriere, Finanzen', interviewTopic: 'Elternzeit für Väter', intervieweeProfession: 'Vater in Elternzeit' },
  { situation: 'Kundengespräch Krankenkasse', sceneHint: 'Tarifwechsel, Leistungen, Beitrag', interviewTopic: 'Beitragsanpassung GKV', intervieweeProfession: 'Kundenberater AOK' },
  { situation: 'Radio-Diskussion Fachkräftemangel', sceneHint: 'Ausbildung, Zuwanderung, Image', interviewTopic: 'Handwerk sucht Azubis', intervieweeProfession: 'Handwerkskammerpräsident' },
  { situation: 'Gespräch in der Verbraucherzentrale', sceneHint: 'Stromanbieter, Rückerstattung', interviewTopic: 'Strompreiserhöhung', intervieweeProfession: 'Verbraucherberater' },
  { situation: 'Talk-Runde über Ehrenamt', sceneHint: 'Motivation, Zeit, Gesellschaft', interviewTopic: 'Ehrenamt bei der Feuerwehr', intervieweeProfession: 'Freiwillige Feuerwehrfrau' },
  { situation: 'Studienberatung an der Uni', sceneHint: 'Wechsel Studiengang, BAföG', interviewTopic: 'Studienfachwechsel', intervieweeProfession: 'Studienberaterin' },
  { situation: 'Beratungsgespräch Jobcenter', sceneHint: 'Umschulung, Weiterbildung, Geld', interviewTopic: 'Umschulung im mittleren Alter', intervieweeProfession: 'Fallmanagerin Jobcenter' },
  { situation: 'Diskussion Klimaschutz im Alltag', sceneHint: 'Auto, Konsum, Wohnen', interviewTopic: 'Klimafreundliche Lebensweise', intervieweeProfession: 'Klimaforscherin' },
  { situation: 'Radio-Talk Ausbildung im Wandel', sceneHint: 'Handwerk, Digital, Gehalt', interviewTopic: 'Attraktivität der dualen Ausbildung', intervieweeProfession: 'Ausbildungsleiter' },
  { situation: 'Gespräch beim Immobilienmakler', sceneHint: 'Wohnungssuche Großstadt', interviewTopic: 'Wohnungssuche München', intervieweeProfession: 'Immobilienmaklerin' },
  { situation: 'Beratung Schuldnerberatung', sceneHint: 'Schulden, Haushaltsplan, Insolvenz', interviewTopic: 'Verbraucherinsolvenz', intervieweeProfession: 'Schuldnerberater' },
  { situation: 'Diskussion Schulpolitik', sceneHint: 'G8/G9, Noten, Digitalisierung', interviewTopic: 'Digitalisierung in Schulen', intervieweeProfession: 'Bildungsforscherin' },
  { situation: 'Gespräch Bafög-Amt', sceneHint: 'Anspruch, Nachweise, Rückzahlung', interviewTopic: 'BAföG-Antrag', intervieweeProfession: 'BAföG-Sachbearbeiterin' },
  { situation: 'Radio-Talk Arbeit 4.0', sceneHint: 'Vier-Tage-Woche, Produktivität', interviewTopic: '4-Tage-Woche Testergebnisse', intervieweeProfession: 'Arbeitssoziologe' },
  { situation: 'Diskussion über Pflegenotstand', sceneHint: 'Gehalt, Wertschätzung, Zuwanderung', interviewTopic: 'Pflegekräftemangel', intervieweeProfession: 'Pflegedienstleiterin' },
  { situation: 'Gespräch Ausländerbehörde', sceneHint: 'Aufenthaltstitel, Verlängerung, Arbeit', interviewTopic: 'Blaue Karte EU', intervieweeProfession: 'Sachbearbeiter Ausländerbehörde' },
  { situation: 'Kundengespräch Bank', sceneHint: 'Baufinanzierung, Zinsen, Laufzeit', interviewTopic: 'Immobilienkredit', intervieweeProfession: 'Bankberater' },
  { situation: 'Talk-Runde Ernährung', sceneHint: 'Vegan, Regional, Bio', interviewTopic: 'Nachhaltige Ernährung', intervieweeProfession: 'Ernährungsberaterin' },
  { situation: 'Diskussion Integration', sceneHint: 'Sprache, Arbeit, Gesellschaft', interviewTopic: 'Gelungene Integration', intervieweeProfession: 'Integrationsbeauftragte' },
  { situation: 'Beratung Rentenversicherung', sceneHint: 'Rentenhöhe, Zeiten, Frühverrentung', interviewTopic: 'Rente mit 63', intervieweeProfession: 'Rentenberater DRV' },
  { situation: 'Radio-Diskussion Miete', sceneHint: 'Mietpreisbremse, Spekulation, Neubau', interviewTopic: 'Wohnungskrise in Städten', intervieweeProfession: 'Stadtplanerin' },
  { situation: 'Gespräch Arbeitgeberin zu Teilzeit', sceneHint: 'Antrag, Stunden, Projekte', interviewTopic: 'Brückenteilzeit nach Elternzeit', intervieweeProfession: 'Personalleiterin' },
  { situation: 'Diskussion Digitale Bildung', sceneHint: 'Tablets, Lehrer, Eltern', interviewTopic: 'Digitalpakt Schule', intervieweeProfession: 'Schulleiterin Gesamtschule' },
  { situation: 'Talk-Runde Nachhaltigkeit', sceneHint: 'Kleidung, Reisen, Konsum', interviewTopic: 'Fast Fashion und Umwelt', intervieweeProfession: 'Nachhaltigkeits-Bloggerin' },
  { situation: 'Beratung Versicherung', sceneHint: 'Haftpflicht, Hausrat, Berufsunfähigkeit', interviewTopic: 'Wichtigste Versicherungen', intervieweeProfession: 'Versicherungsberater' },
  { situation: 'Diskussion Mobilität', sceneHint: 'Auto, ÖPNV, Fahrrad', interviewTopic: 'Verkehrswende in Städten', intervieweeProfession: 'Mobilitätsexpertin' },
  { situation: 'Gespräch in der Kita-Anmeldung', sceneHint: 'Wartelisten, Eingewöhnung, Kosten', interviewTopic: 'Kita-Platzmangel', intervieweeProfession: 'Kita-Leitung' },
  { situation: 'Radio-Talk Psychische Gesundheit', sceneHint: 'Burnout, Therapie, Prävention', interviewTopic: 'Burnout am Arbeitsplatz', intervieweeProfession: 'Arbeitspsychologin' },
  { situation: 'Diskussion Rentenpolitik', sceneHint: 'Generationenvertrag, Beiträge, Rentenalter', interviewTopic: 'Rentenreform', intervieweeProfession: 'Wirtschaftsprofessor' },
  { situation: 'Beratung Existenzgründung', sceneHint: 'Businessplan, Förderung, Risiken', interviewTopic: 'Selbstständigkeit als Friseurin', intervieweeProfession: 'Gründungsberaterin IHK' },
  { situation: 'Gespräch Hebamme Schwangerschaft', sceneHint: 'Vorsorge, Geburt, Wochenbett', interviewTopic: 'Hebammenbetreuung', intervieweeProfession: 'Hebamme' },
  { situation: 'Radio-Talk Tourismus', sceneHint: 'Massentourismus, Regionen, Umwelt', interviewTopic: 'Urlaub in Deutschland', intervieweeProfession: 'Tourismusforscher' },
  { situation: 'Diskussion Handwerk vs. Studium', sceneHint: 'Gehalt, Perspektive, Image', interviewTopic: 'Wert der Ausbildung', intervieweeProfession: 'Handwerksmeisterin' },
  { situation: 'Talk-Runde Generationen', sceneHint: 'Familie, Werte, Technik', interviewTopic: 'Boomer und Generation Z', intervieweeProfession: 'Generationenforscherin' },
  { situation: 'Beratung Elternberater', sceneHint: 'Pubertät, Streit, Grenzen', interviewTopic: 'Pubertät zu Hause', intervieweeProfession: 'Familientherapeut' },
  { situation: 'Diskussion Bürgerbeteiligung', sceneHint: 'Gemeinde, Bauvorhaben, Mitsprache', interviewTopic: 'Bürgerentscheid zu Bauprojekt', intervieweeProfession: 'Bürgermeister' },
  { situation: 'Gespräch Steuerberater', sceneHint: 'Freiberufler, Pauschalen, Elster', interviewTopic: 'Steuererklärung für Freiberufler', intervieweeProfession: 'Steuerberaterin' },
  { situation: 'Radio-Debatte Social Media', sceneHint: 'Jugend, Sucht, Regulierung', interviewTopic: 'TikTok und Jugendliche', intervieweeProfession: 'Medienpädagogin' },
  { situation: 'Beratung Paartherapie', sceneHint: 'Konflikte, Kinder, Kommunikation', interviewTopic: 'Paartherapie bei Stress', intervieweeProfession: 'Paartherapeut' },
  { situation: 'Diskussion Klimaschutz Stadt', sceneHint: 'Mobilität, Häuser, Natur', interviewTopic: 'Klimaneutrale Stadt', intervieweeProfession: 'Umweltdezernent' },
  { situation: 'Gespräch Lehrerin Oberstufe', sceneHint: 'Abi-Stress, Wahl, Zukunft', interviewTopic: 'Abi-Vorbereitung', intervieweeProfession: 'Oberstufenkoordinatorin' },
  { situation: 'Talk-Runde Ernährungsumstellung', sceneHint: 'Motivation, Familie, Budget', interviewTopic: 'Vegetarisch leben', intervieweeProfession: 'Ernährungsberaterin' },
  { situation: 'Beratung Pflege zu Hause', sceneHint: 'Pflegegrad, Geld, Kraft', interviewTopic: 'Pflege Angehörige', intervieweeProfession: 'Pflegeberater' },
  { situation: 'Diskussion E-Scooter Städte', sceneHint: 'Unfälle, Regeln, Umwelt', interviewTopic: 'E-Scooter-Chaos', intervieweeProfession: 'Verkehrsplaner' },
  { situation: 'Gespräch Elternzeit-Beratung', sceneHint: 'Wechsel, Aufteilung, Job', interviewTopic: 'Elterngeld Plus', intervieweeProfession: 'Familienkasse-Beraterin' },
  { situation: 'Radio-Diskussion Energiewende', sceneHint: 'Solar, Wind, Heizung', interviewTopic: 'Heizungsgesetz', intervieweeProfession: 'Energieberaterin' },
  { situation: 'Beratung Auslandsaufenthalt', sceneHint: 'Erasmus, Praktikum, Sprache', interviewTopic: 'Auslandssemester in Spanien', intervieweeProfession: 'International Office Uni' },
  { situation: 'Diskussion Jugendschutz', sceneHint: 'Alkohol, Medien, Party', interviewTopic: 'Jugendschutz-Regeln', intervieweeProfession: 'Jugendamt' },
  { situation: 'Talk-Runde Arbeit und Familie', sceneHint: 'Vereinbarkeit, Homeoffice, Kita', interviewTopic: 'Familie und Karriere', intervieweeProfession: 'Gleichstellungsbeauftragte' },
  { situation: 'Beratung Senioren', sceneHint: 'Wohnen, Pflege, Gemeinschaft', interviewTopic: 'Wohnen im Alter', intervieweeProfession: 'Seniorenberater' },
  { situation: 'Diskussion Lebensmittelpreise', sceneHint: 'Inflation, Bio, Regional', interviewTopic: 'Teurer Einkauf', intervieweeProfession: 'Landwirt' },
  { situation: 'Radio-Talk Lebensmittel retten', sceneHint: 'Foodsharing, Reste, Gesetze', interviewTopic: 'Foodsharing Initiative', intervieweeProfession: 'Foodsharing-Aktivistin' },
  { situation: 'Gespräch Schulwahl Eltern', sceneHint: 'Gymnasium vs. Gesamtschule', interviewTopic: 'Übergang Grundschule', intervieweeProfession: 'Schulleiterin Grundschule' },
  { situation: 'Beratung Erbrecht', sceneHint: 'Testament, Erbengemeinschaft, Pflicht', interviewTopic: 'Testament aufsetzen', intervieweeProfession: 'Notarin' },
]

// Teil 4 — Vortrag oder Diskussion mit 2 Experten
export const HOREN_B1_T4: TopicData[] = [
  { situation: 'Podium zu Digitalisierung der Schule', sceneHint: 'Tablets, Lehrer, Eltern', fiveDialoguesTheme: 'Digitalisierung Schule — zwei Expertinnen' },
  { situation: 'Podium zu Wohnungsmarkt', sceneHint: 'Bauen, Mietpreise, Spekulation', fiveDialoguesTheme: 'Wohnungskrise' },
  { situation: 'Podium zum dualen Studium', sceneHint: 'Gehalt, Praxis, Perspektive', fiveDialoguesTheme: 'Ausbildung vs. Studium' },
  { situation: 'Diskussion Elternzeit und Karriere', sceneHint: 'Partner, Job, Kita', fiveDialoguesTheme: 'Elternzeit für Väter' },
  { situation: 'Podium Fachkräftemangel Pflege', sceneHint: 'Gehalt, Bedingungen, Nachwuchs', fiveDialoguesTheme: 'Pflegenotstand' },
  { situation: 'Podium Klimawandel und Verkehr', sceneHint: 'Auto, Bahn, Rad', fiveDialoguesTheme: 'Verkehrswende' },
  { situation: 'Podium Integration durch Sprache', sceneHint: 'Kurse, Arbeit, Alltag', fiveDialoguesTheme: 'Deutsch lernen in Deutschland' },
  { situation: 'Diskussion zum Deutschland-Ticket', sceneHint: 'Preis, Finanzierung, Nutzung', fiveDialoguesTheme: 'Öffentlicher Nahverkehr' },
  { situation: 'Podium zur Rentenreform', sceneHint: 'Alter, Beiträge, Generationen', fiveDialoguesTheme: 'Rente mit 70?' },
  { situation: 'Diskussion Energiewende Gebäude', sceneHint: 'Heizung, Sanierung, Kosten', fiveDialoguesTheme: 'Wärmepumpe und Sanierung' },
  { situation: 'Podium Jugend und Social Media', sceneHint: 'Zeit, Sucht, Regulierung', fiveDialoguesTheme: 'TikTok-Generation' },
  { situation: 'Diskussion zu Homeoffice', sceneHint: 'Produktivität, Sozialleben, Recht', fiveDialoguesTheme: 'Homeoffice dauerhaft?' },
  { situation: 'Podium Künstliche Intelligenz', sceneHint: 'Arbeit, Ethik, Bildung', fiveDialoguesTheme: 'KI im Alltag' },
  { situation: 'Diskussion Ernährung und Gesundheit', sceneHint: 'Vegan, Regional, Schulen', fiveDialoguesTheme: 'Ernährung der Zukunft' },
  { situation: 'Podium zum Ehrenamt', sceneHint: 'Motivation, Zeit, Anerkennung', fiveDialoguesTheme: 'Ehrenamt in Deutschland' },
  { situation: 'Diskussion Work-Life-Balance', sceneHint: '4-Tage-Woche, Familie, Gehalt', fiveDialoguesTheme: 'Arbeit und Leben' },
  { situation: 'Podium Mobilität in Städten', sceneHint: 'Auto-frei, ÖPNV, Fahrrad', fiveDialoguesTheme: 'Autofreie Innenstadt' },
  { situation: 'Diskussion Bildung Chancengleichheit', sceneHint: 'Herkunft, Schulwahl, Förderung', fiveDialoguesTheme: 'Bildungsgerechtigkeit' },
  { situation: 'Podium Mietpreisbremse', sceneHint: 'Wirkung, Umgehungen, Reform', fiveDialoguesTheme: 'Mietregulierung' },
  { situation: 'Diskussion Gesundheitssystem', sceneHint: 'Privat, Gesetzlich, Wartezeiten', fiveDialoguesTheme: 'Zwei-Klassen-Medizin?' },
  { situation: 'Podium Wasserknappheit', sceneHint: 'Landwirtschaft, Trinken, Regionen', fiveDialoguesTheme: 'Wasser als Ressource' },
  { situation: 'Diskussion Arbeitgebermarke', sceneHint: 'Benefits, Standort, Gehalt', fiveDialoguesTheme: 'Talente gewinnen' },
  { situation: 'Podium zum Fernsehverhalten', sceneHint: 'Streaming, Qualität, Generationen', fiveDialoguesTheme: 'Fernsehen von morgen' },
  { situation: 'Diskussion Sozialstaat', sceneHint: 'Bürgergeld, Anreize, Gerechtigkeit', fiveDialoguesTheme: 'Bürgergeld-Reform' },
  { situation: 'Podium zu Medien und Demokratie', sceneHint: 'Fake-News, Regulierung, Journalismus', fiveDialoguesTheme: 'Medienkompetenz' },
  { situation: 'Diskussion zum Elterngeld', sceneHint: 'Höhe, Dauer, Väter', fiveDialoguesTheme: 'Elterngeld reformieren?' },
  { situation: 'Podium zu Klimawandel Alltag', sceneHint: 'Konsum, Reisen, Heizen', fiveDialoguesTheme: 'Klimafreundlich leben' },
  { situation: 'Diskussion Sportförderung', sceneHint: 'Vereine, Schulsport, Geld', fiveDialoguesTheme: 'Bewegung in Deutschland' },
  { situation: 'Podium Landwirtschaft Zukunft', sceneHint: 'Bio, Technik, Preise', fiveDialoguesTheme: 'Ernährung und Landwirtschaft' },
  { situation: 'Diskussion Einwanderung Fachkräfte', sceneHint: 'Gesetz, Sprache, Anerkennung', fiveDialoguesTheme: 'Fachkräfteeinwanderung' },
  { situation: 'Podium Wohnen im Alter', sceneHint: 'WG, Pflege, Barrierefrei', fiveDialoguesTheme: 'Älterwerden zu Hause' },
  { situation: 'Diskussion zum Verbraucherschutz', sceneHint: 'Online, Lebensmittel, Werbung', fiveDialoguesTheme: 'Transparenz für Käufer' },
  { situation: 'Podium Digitalverwaltung', sceneHint: 'Apps, Behörden, Datenschutz', fiveDialoguesTheme: 'Digitales Bürgeramt' },
  { situation: 'Diskussion Frauen in Führung', sceneHint: 'Quote, Familie, Karriere', fiveDialoguesTheme: 'Gleichstellung in Betrieben' },
  { situation: 'Podium Reiseverhalten', sceneHint: 'Fernreisen, Bahn, Umwelt', fiveDialoguesTheme: 'Urlaub im Wandel' },
  { situation: 'Diskussion Bildungsföderalismus', sceneHint: 'Länder, Lehrpläne, Vergleichbarkeit', fiveDialoguesTheme: 'Schule Bund vs. Länder' },
  { situation: 'Podium Start-up-Szene', sceneHint: 'Gründung, Kapital, Risiko', fiveDialoguesTheme: 'Unternehmensgründung heute' },
  { situation: 'Diskussion Sparen und Anlegen', sceneHint: 'Inflation, ETF, Immobilien', fiveDialoguesTheme: 'Geld richtig anlegen' },
  { situation: 'Podium Arbeitsmarkt Zuwanderung', sceneHint: 'Visa, Sprache, Integration', fiveDialoguesTheme: 'Internationale Fachkräfte' },
  { situation: 'Diskussion zum Stadtverkehr', sceneHint: 'Tempo 30, Radwege, Lärm', fiveDialoguesTheme: 'Lebensqualität in Städten' },
  { situation: 'Podium Digitale Bildung Uni', sceneHint: 'Online-Lehre, Präsenz, Qualität', fiveDialoguesTheme: 'Hochschule digital' },
  { situation: 'Diskussion Fachkräftemangel Handwerk', sceneHint: 'Nachwuchs, Image, Zuwanderung', fiveDialoguesTheme: 'Handwerk sucht Nachwuchs' },
  { situation: 'Podium Stadt und Land', sceneHint: 'Internet, ÖPNV, Ärzte', fiveDialoguesTheme: 'Leben auf dem Land' },
  { situation: 'Diskussion Lebenslanges Lernen', sceneHint: 'VHS, MOOC, Arbeitgeber', fiveDialoguesTheme: 'Weiterbildung im Beruf' },
  { situation: 'Podium Digitalsteuer', sceneHint: 'Konzerne, Staat, Wettbewerb', fiveDialoguesTheme: 'Internet-Konzerne besteuern' },
  { situation: 'Diskussion Tierschutz', sceneHint: 'Haltung, Transport, Label', fiveDialoguesTheme: 'Tierwohl in Deutschland' },
  { situation: 'Podium Jugend und Politik', sceneHint: 'Wahl, Engagement, Bildung', fiveDialoguesTheme: 'Demokratiebildung' },
  { situation: 'Diskussion Kulturpolitik', sceneHint: 'Theater, Förderung, Besucher', fiveDialoguesTheme: 'Kultur in der Krise' },
  { situation: 'Podium zu Medienkompetenz', sceneHint: 'Schule, Eltern, Plattformen', fiveDialoguesTheme: 'Kinder und Smartphones' },
  { situation: 'Diskussion zu Pflegeversicherung', sceneHint: 'Beiträge, Leistungen, Zukunft', fiveDialoguesTheme: 'Pflege finanzieren' },
  { situation: 'Podium zu Integration im Sport', sceneHint: 'Vereine, Sprache, Teilhabe', fiveDialoguesTheme: 'Sport verbindet' },
  { situation: 'Diskussion Digitalpakt Kita', sceneHint: 'Tablets, Erzieher, Eltern', fiveDialoguesTheme: 'Frühkindliche digitale Bildung' },
  { situation: 'Podium Wasserstoff-Wirtschaft', sceneHint: 'Industrie, Verkehr, Kosten', fiveDialoguesTheme: 'Energie der Zukunft' },
  { situation: 'Diskussion Handel und Innenstadt', sceneHint: 'Online, Leerstand, Erlebnis', fiveDialoguesTheme: 'Belebte Innenstädte' },
  { situation: 'Podium Ausbildung Zuwanderung', sceneHint: 'Anerkennung, Sprache, Betriebe', fiveDialoguesTheme: 'Ausbildung für Zugewanderte' },
  { situation: 'Diskussion zu Ausstiegshilfen', sceneHint: 'Rauchen, Alkohol, Sucht', fiveDialoguesTheme: 'Sucht und Gesellschaft' },
  { situation: 'Podium Bildung Menschen mit Behinderung', sceneHint: 'Inklusion, Schule, Arbeit', fiveDialoguesTheme: 'Inklusion im Alltag' },
  { situation: 'Diskussion zu Müllvermeidung', sceneHint: 'Verpackung, Mehrweg, Politik', fiveDialoguesTheme: 'Weniger Müll produzieren' },
  { situation: 'Podium zu Mobilität auf dem Land', sceneHint: 'Bus, Auto, Ruftaxi', fiveDialoguesTheme: 'Ländliche Verkehrswende' },
  { situation: 'Diskussion Arbeit und Gesundheit', sceneHint: 'Stress, Prävention, Betrieb', fiveDialoguesTheme: 'Gesund arbeiten' },
]
