// Темы для модуля Lesen B1 — все 5 Teile.

import type { TopicData } from '@/lib/topic-sampler'

// Teil 1 — Blog B1 (persönlicher Text mit Reflexion)
export const LESEN_B1_T1: TopicData[] = [
  { situation: 'Ehrenamtliche Tätigkeit im Tierheim', category: 'Soziales', sceneHint: 'Reflexion über Arbeit und Menschen', blogAuthor: 'Mona' },
  { situation: 'Auslandssemester in Spanien', category: 'Bildung', sceneHint: 'kulturelle Eindrücke', blogAuthor: 'Leon' },
  { situation: 'Vom Büro ins Homeoffice', category: 'Arbeit', sceneHint: 'Veränderung des Arbeitsalltags', blogAuthor: 'Sabine' },
  { situation: 'Mein Weg aus dem Burnout', category: 'Gesundheit', sceneHint: 'persönliche Reflexion', blogAuthor: 'Tom' },
  { situation: 'Die Elternzeit eines Vaters', category: 'Familie', sceneHint: 'neun Monate Erziehung', blogAuthor: 'Raphael' },
  { situation: 'Mein Jahr als Freiwillige in Tansania', category: 'Reise', sceneHint: 'Kultur und Lernen', blogAuthor: 'Johanna' },
  { situation: 'Karriereknick und Neustart', category: 'Arbeit', sceneHint: 'Branchenwechsel', blogAuthor: 'Katrin' },
  { situation: 'Mein erstes Jahr in der Selbstständigkeit', category: 'Arbeit', sceneHint: 'Startup in Hamburg', blogAuthor: 'Ben' },
  { situation: 'Zurück zu den Wurzeln: Dorfleben nach der Großstadt', category: 'Wohnen', sceneHint: 'Ruhe statt Hektik', blogAuthor: 'Hannah' },
  { situation: 'Nach zehn Jahren aus Deutschland wieder Heimat', category: 'Gesellschaft', sceneHint: 'Rückkehr-Experiment', blogAuthor: 'Ayşen' },
  { situation: 'Leben mit einer chronischen Erkrankung', category: 'Gesundheit', sceneHint: 'Alltagserfahrungen', blogAuthor: 'Nora' },
  { situation: 'Alleinerziehend in Deutschland', category: 'Familie', sceneHint: 'Wochen im Alltag', blogAuthor: 'Oliver' },
  { situation: 'Mein Auslandsjahr im Homeoffice', category: 'Arbeit', sceneHint: 'Workation Lissabon', blogAuthor: 'Alina' },
  { situation: 'Ein Jahr ohne Fliegen', category: 'Umwelt', sceneHint: 'Bahn statt Flugzeug', blogAuthor: 'Malte' },
  { situation: 'Vom Angestellten zum Handwerker', category: 'Arbeit', sceneHint: 'zweite Ausbildung', blogAuthor: 'Dieter' },
  { situation: 'Wie ich Deutsch gelernt habe', category: 'Sprache', sceneHint: 'Vom A1 zum B2 in 18 Monaten', blogAuthor: 'Maria' },
  { situation: 'Leben in einer Kleinstadt', category: 'Wohnen', sceneHint: 'Leben auf dem Land', blogAuthor: 'Jens' },
  { situation: 'Ein Sabbatical als Familie', category: 'Familie', sceneHint: 'Sechs Monate unterwegs', blogAuthor: 'Corinna' },
  { situation: 'Meine Erfahrungen mit der Pflege zu Hause', category: 'Gesundheit', sceneHint: 'Mutter pflegen', blogAuthor: 'Magda' },
  { situation: 'Integration trotz Bürokratie', category: 'Gesellschaft', sceneHint: 'Bürokratie-Hürden', blogAuthor: 'Saeed' },
  { situation: 'Mein Wechsel vom Studium ins Berufsleben', category: 'Arbeit', sceneHint: 'Berufseinstieg im Journalismus', blogAuthor: 'Lisa' },
  { situation: 'Wie ich Schulden losgeworden bin', category: 'Finanzen', sceneHint: 'Haushaltsbuch-System', blogAuthor: 'Ali' },
  { situation: 'Mein Jahr in der dualen Ausbildung', category: 'Arbeit', sceneHint: 'Handwerkskammer Köln', blogAuthor: 'Mike' },
  { situation: 'Ein Jahr im Schrebergarten', category: 'Umwelt', sceneHint: 'Selbstversorgung', blogAuthor: 'Ursula' },
  { situation: 'Warum ich mein Auto verkauft habe', category: 'Umwelt', sceneHint: 'Leben mit ÖPNV', blogAuthor: 'Nadim' },
  { situation: 'Mein Weg zur Beamtin', category: 'Arbeit', sceneHint: 'Öffentlicher Dienst', blogAuthor: 'Kristin' },
  { situation: 'Gründer*innen-Erfahrung im Bereich Mode', category: 'Arbeit', sceneHint: 'Faire Kleidung', blogAuthor: 'Pia' },
  { situation: 'Ein Jahr Veganismus — Fazit', category: 'Gesundheit', sceneHint: 'Ernährung umstellen', blogAuthor: 'Robert' },
  { situation: 'Pendeln auf 150 Kilometer', category: 'Verkehr', sceneHint: 'Fernpendler in NRW', blogAuthor: 'Markus' },
  { situation: 'Mein Weg in die Pflege', category: 'Arbeit', sceneHint: 'Quereinstieg', blogAuthor: 'Elena' },
  { situation: 'Familienurlaub mit drei Generationen', category: 'Familie', sceneHint: 'Oma, Eltern, Kinder', blogAuthor: 'Bernd' },
  { situation: 'Ein Jahr als Pflegefamilie', category: 'Familie', sceneHint: 'Pflegekind aufnehmen', blogAuthor: 'Johanna' },
  { situation: 'Mein Ehrenamt im Sprachcafé', category: 'Soziales', sceneHint: 'Sprachmittlung', blogAuthor: 'Ewa' },
  { situation: 'Meine Erfahrungen mit Mediation', category: 'Arbeit', sceneHint: 'Konfliktbewältigung', blogAuthor: 'Sabina' },
  { situation: 'Wohnen auf dem Bauernhof', category: 'Wohnen', sceneHint: 'Leben im Landgasthof', blogAuthor: 'Ruth' },
  { situation: 'Vom Praktikum zum Festvertrag', category: 'Arbeit', sceneHint: 'IT-Branche', blogAuthor: 'Arman' },
  { situation: 'Neue Stadt, neue Nachbarn', category: 'Wohnen', sceneHint: 'Einzug in Leipzig', blogAuthor: 'Frieda' },
  { situation: 'Mein Umzug nach Deutschland mit Kindern', category: 'Familie', sceneHint: 'Schulwahl', blogAuthor: 'Ngozi' },
  { situation: 'Ein Jahr als Sprachassistenz in einer Schule', category: 'Bildung', sceneHint: 'Grundschule', blogAuthor: 'Clara' },
  { situation: 'Meine Erfahrungen als Gründerin', category: 'Arbeit', sceneHint: 'Gastronomie-Start-up', blogAuthor: 'Natascha' },
  { situation: 'Meine Reise durch die Pfalz', category: 'Reise', sceneHint: 'Weinberge und Dörfer', blogAuthor: 'Stefan' },
  { situation: 'Vom Büro in die Bäckerei', category: 'Arbeit', sceneHint: 'zweite Karriere', blogAuthor: 'Annika' },
  { situation: 'Ein Jahr als Ehrenamtlicher bei der Tafel', category: 'Soziales', sceneHint: 'Reflexion', blogAuthor: 'Carlo' },
  { situation: 'Wie ich ein Haus gekauft habe', category: 'Wohnen', sceneHint: 'Finanzierung und Makler', blogAuthor: 'Kerstin' },
  { situation: 'Meine Erfahrungen mit Coaching-Ausbildung', category: 'Arbeit', sceneHint: 'Zertifizierter Coach', blogAuthor: 'Marek' },
  { situation: 'Alleinreisende durch Deutschland', category: 'Reise', sceneHint: 'Solo-Trip', blogAuthor: 'Yuki' },
  { situation: 'Mein Weg zum dualen Studium', category: 'Bildung', sceneHint: 'Bewerbung und Auswahl', blogAuthor: 'Rami' },
  { situation: 'Rollstuhlgerechtes Reisen in Deutschland', category: 'Reise', sceneHint: 'Barrierefreiheit', blogAuthor: 'Tim' },
  { situation: 'Meine Erfahrungen mit einer Adoption', category: 'Familie', sceneHint: 'Adoption in Deutschland', blogAuthor: 'Aya' },
  { situation: 'Freelance als Übersetzerin', category: 'Arbeit', sceneHint: 'Selbstständigkeit', blogAuthor: 'Viktoria' },
  { situation: 'Mein Sprachzertifikat: Goethe B1', category: 'Sprache', sceneHint: 'Prüfung bestehen', blogAuthor: 'Sofía' },
  { situation: 'Deutschland als Lebensabschnitt', category: 'Gesellschaft', sceneHint: 'Rückblick nach fünf Jahren', blogAuthor: 'Henry' },
  { situation: 'Ein Jahr als Werkstudentin', category: 'Arbeit', sceneHint: 'Studium und Job', blogAuthor: 'Lena' },
  { situation: 'Mein Weg zur Yoga-Lehrerin', category: 'Gesundheit', sceneHint: 'Ausbildung', blogAuthor: 'Maja' },
  { situation: 'Wie ich meinen Mietvertrag gekündigt habe', category: 'Wohnen', sceneHint: 'Kündigungsfristen', blogAuthor: 'Lars' },
  { situation: 'Ein Jahr ohne Fastfood', category: 'Gesundheit', sceneHint: 'Ernährungsreflexion', blogAuthor: 'Sven' },
  { situation: 'Mein Auslandspraktikum in Zürich', category: 'Arbeit', sceneHint: 'Schweizer Arbeitskultur', blogAuthor: 'Julia' },
  { situation: 'Erziehung zweisprachig', category: 'Familie', sceneHint: 'Kind wächst mit zwei Sprachen auf', blogAuthor: 'Dmitri' },
  { situation: 'Mein Jahr in der politischen Jugendarbeit', category: 'Gesellschaft', sceneHint: 'Jugendgruppe', blogAuthor: 'Ronja' },
  { situation: 'Mein Kampf gegen Pendlerstress', category: 'Arbeit', sceneHint: 'ÖPNV-Strategie', blogAuthor: 'Timo' },
]

// Teil 2 — Zeitungsartikel
export const LESEN_B1_T2: TopicData[] = [
  { situation: 'Digitalisierung an deutschen Schulen', category: 'Bildung', articleSource: 'Tageszeitung' },
  { situation: 'Klimawandel und Weinbau in Deutschland', category: 'Umwelt', articleSource: 'Wirtschaftsteil' },
  { situation: 'Fachkräftemangel in der Pflege', category: 'Wirtschaft', articleSource: 'Wirtschaftsteil' },
  { situation: 'Wohnungsnot in Ballungsräumen', category: 'Gesellschaft', articleSource: 'Tageszeitung' },
  { situation: 'Neue Regelungen beim Elterngeld', category: 'Familie', articleSource: 'Politikteil' },
  { situation: 'Streit um das Deutschlandticket', category: 'Verkehr', articleSource: 'Wirtschaftsteil' },
  { situation: 'Bundestagswahl und junge Wähler', category: 'Gesellschaft', articleSource: 'Politikteil' },
  { situation: 'Künstliche Intelligenz im Arbeitsalltag', category: 'Technik', articleSource: 'Wirtschaftsteil' },
  { situation: 'Kreislaufwirtschaft in Deutschland', category: 'Umwelt', articleSource: 'Wissensteil' },
  { situation: 'Integration von Geflüchteten auf dem Arbeitsmarkt', category: 'Gesellschaft', articleSource: 'Politikteil' },
  { situation: 'Deutschlands Energiewende', category: 'Umwelt', articleSource: 'Wirtschaftsteil' },
  { situation: 'Smarte Städte und Datenschutz', category: 'Technik', articleSource: 'Wissensteil' },
  { situation: 'Fachkräftezuwanderung aus Nicht-EU-Ländern', category: 'Wirtschaft', articleSource: 'Politikteil' },
  { situation: 'Weltraumforschung made in Germany', category: 'Wissenschaft', articleSource: 'Wissensteil' },
  { situation: 'Steigende Lebenshaltungskosten und Familien', category: 'Gesellschaft', articleSource: 'Tageszeitung' },
  { situation: 'Schulreform: Gymnasium in neun Jahren', category: 'Bildung', articleSource: 'Politikteil' },
  { situation: 'Ehrenamt als Stütze der Gesellschaft', category: 'Soziales', articleSource: 'Feuilleton' },
  { situation: 'Unternehmensnachfolge im Mittelstand', category: 'Wirtschaft', articleSource: 'Wirtschaftsteil' },
  { situation: 'Deutschland und die Rente der Zukunft', category: 'Politik', articleSource: 'Politikteil' },
  { situation: 'Hochwasserschutz an Flüssen', category: 'Umwelt', articleSource: 'Wissensteil' },
  { situation: 'Streaming verändert die Musikbranche', category: 'Kultur', articleSource: 'Kulturteil' },
  { situation: 'Neue Wege gegen Einsamkeit im Alter', category: 'Soziales', articleSource: 'Feuilleton' },
  { situation: 'Debatte um Cannabis-Legalisierung', category: 'Politik', articleSource: 'Politikteil' },
  { situation: 'Lehrkräftemangel und Quereinsteiger', category: 'Bildung', articleSource: 'Bildungsteil' },
  { situation: 'Wissenschaft gegen Long-Covid', category: 'Wissenschaft', articleSource: 'Wissensteil' },
  { situation: 'Deutschland importiert weniger Energie', category: 'Wirtschaft', articleSource: 'Wirtschaftsteil' },
  { situation: 'Wie junge Menschen Nachrichten konsumieren', category: 'Gesellschaft', articleSource: 'Feuilleton' },
  { situation: 'Städte pflanzen Klimabäume', category: 'Umwelt', articleSource: 'Regionalteil' },
  { situation: 'Kunsthandwerk erlebt eine Renaissance', category: 'Kultur', articleSource: 'Kulturteil' },
  { situation: 'Fußball und Integration in Vereinen', category: 'Sport', articleSource: 'Sportteil' },
  { situation: 'Gesundheit und Schichtarbeit', category: 'Gesundheit', articleSource: 'Wissensteil' },
  { situation: 'Wohnprojekte für Senioren-WGs', category: 'Soziales', articleSource: 'Regionalteil' },
  { situation: 'Spielkonsolen und Sozialverhalten', category: 'Gesellschaft', articleSource: 'Feuilleton' },
  { situation: 'Klimaschutzklagen vor Gericht', category: 'Politik', articleSource: 'Politikteil' },
  { situation: 'Solidarische Landwirtschaft wächst', category: 'Umwelt', articleSource: 'Wirtschaftsteil' },
  { situation: 'Der Trend zum E-Bike', category: 'Verkehr', articleSource: 'Wirtschaftsteil' },
  { situation: 'Künstliche Intelligenz im Journalismus', category: 'Technik', articleSource: 'Feuilleton' },
  { situation: 'Elterngeldreform und Väterbeteiligung', category: 'Familie', articleSource: 'Politikteil' },
  { situation: 'Regionale Währungen als Projekt', category: 'Wirtschaft', articleSource: 'Wirtschaftsteil' },
  { situation: 'Zuwachs bei Homeschooling in Europa', category: 'Bildung', articleSource: 'Bildungsteil' },
  { situation: 'Inklusion in deutschen Schulen', category: 'Bildung', articleSource: 'Bildungsteil' },
  { situation: 'Mietpreisbremse — Bilanz', category: 'Wohnen', articleSource: 'Wirtschaftsteil' },
  { situation: 'Streit um Windkraft in Wäldern', category: 'Umwelt', articleSource: 'Wissensteil' },
  { situation: 'Debatte um Tempolimit auf Autobahnen', category: 'Verkehr', articleSource: 'Politikteil' },
  { situation: 'Psychische Gesundheit bei Jugendlichen', category: 'Gesundheit', articleSource: 'Gesundheitsteil' },
  { situation: 'Nachhaltigkeit in der Textilindustrie', category: 'Wirtschaft', articleSource: 'Wirtschaftsteil' },
  { situation: 'Digitale Gesundheitsakte in Deutschland', category: 'Gesundheit', articleSource: 'Gesundheitsteil' },
  { situation: 'Stadt-Land-Gefälle beim Internet', category: 'Gesellschaft', articleSource: 'Wirtschaftsteil' },
  { situation: 'Volkshochschulen im Wandel', category: 'Bildung', articleSource: 'Feuilleton' },
  { situation: 'Wissenschaft zum Insektensterben', category: 'Wissenschaft', articleSource: 'Wissensteil' },
  { situation: 'Demografischer Wandel und Mittelstand', category: 'Wirtschaft', articleSource: 'Wirtschaftsteil' },
  { situation: 'Arbeit 4.0: Neue Arbeitsformen', category: 'Arbeit', articleSource: 'Wirtschaftsteil' },
  { situation: 'Deutsch als Fremdsprache weltweit', category: 'Kultur', articleSource: 'Feuilleton' },
  { situation: 'Sport in der Schule: Bewegungsmangel', category: 'Bildung', articleSource: 'Bildungsteil' },
  { situation: 'Kirchen und gesellschaftliche Debatten', category: 'Gesellschaft', articleSource: 'Feuilleton' },
  { situation: 'Traditionelle Handwerksbetriebe in Städten', category: 'Wirtschaft', articleSource: 'Regionalteil' },
  { situation: 'Regionale Lebensmittel und Zertifikate', category: 'Essen', articleSource: 'Wissensteil' },
  { situation: 'Streit um kürzere Wochenarbeitszeit', category: 'Arbeit', articleSource: 'Wirtschaftsteil' },
  { situation: 'Kultur in kleinen Gemeinden', category: 'Kultur', articleSource: 'Regionalteil' },
  { situation: 'Klimaangst — eine neue Form der Belastung', category: 'Gesundheit', articleSource: 'Feuilleton' },
]

// Teil 3 — Regelwerk / Teilnahmebedingungen B1
export const LESEN_B1_T3: TopicData[] = [
  { situation: 'Teilnahmebedingungen eines Online-Kurses', category: 'Bildung', regelDomain: 'Online-Kurs', regelContext: 'Lizenzen' },
  { situation: 'Rückgaberecht im Online-Shop', category: 'Verbraucher', regelDomain: 'Online-Shop', regelContext: 'Widerruf' },
  { situation: 'Hausordnung Studentenwohnheim', category: 'Wohnen', regelDomain: 'Studentenwohnheim', regelContext: 'Gemeinschaftsregeln' },
  { situation: 'AGB einer Carsharing-Plattform', category: 'Verkehr', regelDomain: 'Carsharing', regelContext: 'Buchung und Haftung' },
  { situation: 'Teilnahmebedingungen Sommerakademie', category: 'Bildung', regelDomain: 'Sommerakademie', regelContext: 'Anmeldefrist' },
  { situation: 'Benutzungsordnung Coworking-Space', category: 'Arbeit', regelDomain: 'Coworking', regelContext: 'Drucker und Meetingräume' },
  { situation: 'Verträge bei Streaming-Diensten', category: 'Verbraucher', regelDomain: 'Streaming', regelContext: 'Kündigungsfristen' },
  { situation: 'Regeln in einem DaF-Sprachcafé', category: 'Sprache', regelDomain: 'Sprachcafé', regelContext: 'Teilnahme' },
  { situation: 'Regeln bei einer Schrebergartenpacht', category: 'Umwelt', regelDomain: 'Kleingartenverein', regelContext: 'Gartenordnung' },
  { situation: 'AGB eines Lieferdienstes', category: 'Verbraucher', regelDomain: 'Lieferdienst', regelContext: 'Stornierung' },
  { situation: 'Regeln beim Betriebspraktikum', category: 'Arbeit', regelDomain: 'Praktikum', regelContext: 'Arbeitszeit' },
  { situation: 'Regeln einer Kindertagespflege', category: 'Familie', regelDomain: 'Tagespflege', regelContext: 'Bring- und Abholzeiten' },
  { situation: 'Regeln beim Volunteering in Südamerika', category: 'Reise', regelDomain: 'Volunteering', regelContext: 'Versicherung' },
  { situation: 'Regeln im Hackathon', category: 'Technik', regelDomain: 'Hackathon', regelContext: 'Code of Conduct' },
  { situation: 'Regeln in einer studentischen WG', category: 'Wohnen', regelDomain: 'WG', regelContext: 'Gemeinschaftskasse' },
  { situation: 'Teilnahmebedingungen Forschungsprojekt', category: 'Wissenschaft', regelDomain: 'Forschungsprojekt', regelContext: 'Einwilligung' },
  { situation: 'Regeln beim BAföG-Antrag', category: 'Bildung', regelDomain: 'BAföG', regelContext: 'Nachweise' },
  { situation: 'Ordnung eines Mehrgenerationenhauses', category: 'Wohnen', regelDomain: 'Mehrgenerationenhaus', regelContext: 'Gemeinschaftsräume' },
  { situation: 'Regeln bei einer Online-Lotterie', category: 'Verbraucher', regelDomain: 'Online-Lotterie', regelContext: 'Alter und Identität' },
  { situation: 'Teilnahmebedingungen Fotowettbewerb', category: 'Kultur', regelDomain: 'Fotowettbewerb', regelContext: 'Urheberrecht' },
  { situation: 'Regeln beim Bluspendedienst', category: 'Gesundheit', regelDomain: 'Blutspende', regelContext: 'Ausschlussgründe' },
  { situation: 'AGB einer Reiseversicherung', category: 'Verbraucher', regelDomain: 'Reiseversicherung', regelContext: 'Leistungen' },
  { situation: 'Regeln im Freiwilligen Sozialen Jahr', category: 'Soziales', regelDomain: 'FSJ', regelContext: 'Urlaub und Gehalt' },
  { situation: 'Regeln an der Hochschule zur Klausurteilnahme', category: 'Bildung', regelDomain: 'Hochschule', regelContext: 'Klausuranmeldung' },
  { situation: 'Teilnahmebedingungen Startup-Acceleratior', category: 'Wirtschaft', regelDomain: 'Accelerator', regelContext: 'Equity und Regeln' },
  { situation: 'AGB einer Mietwagen-Station', category: 'Verkehr', regelDomain: 'Mietwagen', regelContext: 'Selbstbeteiligung' },
  { situation: 'Regeln in einer Fahrgemeinschaft-App', category: 'Verkehr', regelDomain: 'Mitfahr-App', regelContext: 'Bezahlung und Bewertung' },
  { situation: 'Hausordnung eines Seniorenheims', category: 'Soziales', regelDomain: 'Seniorenheim', regelContext: 'Ruhezeiten' },
  { situation: 'Regeln bei der Online-Immatrikulation', category: 'Bildung', regelDomain: 'Universität', regelContext: 'Fristen' },
  { situation: 'Teilnahmebedingungen Marathonlauf', category: 'Sport', regelDomain: 'Marathon', regelContext: 'Startgebühren' },
  { situation: 'AGB einer Möbel-Leasing-Plattform', category: 'Verbraucher', regelDomain: 'Möbel-Leasing', regelContext: 'Rückgabe' },
  { situation: 'Regeln für Gastfamilien beim Schüleraustausch', category: 'Bildung', regelDomain: 'Schüleraustausch', regelContext: 'Aufnahme und Aufgaben' },
  { situation: 'Teilnahmebedingungen eines Programmierworkshops', category: 'Technik', regelDomain: 'Workshop', regelContext: 'Voraussetzungen' },
  { situation: 'Regeln bei einer Auslandskrankenversicherung', category: 'Gesundheit', regelDomain: 'Auslandskrankenversicherung', regelContext: 'Leistungen' },
  { situation: 'AGB einer Ferien-Apartment-Plattform', category: 'Reise', regelDomain: 'Ferien-Apartment', regelContext: 'Stornierung' },
  { situation: 'Regeln für Förderprogramme in Kommunen', category: 'Soziales', regelDomain: 'Förderprogramm', regelContext: 'Zielgruppe' },
  { situation: 'Hausordnung eines Wohnheims für Azubis', category: 'Wohnen', regelDomain: 'Azubiheim', regelContext: 'Besuchsregeln' },
  { situation: 'Regeln beim Crowdfunding-Projekt', category: 'Wirtschaft', regelDomain: 'Crowdfunding', regelContext: 'Zielbetrag' },
  { situation: 'Regeln beim Bergsport-Club', category: 'Sport', regelDomain: 'Bergsport-Club', regelContext: 'Mitgliedsanträge' },
  { situation: 'Teilnahmebedingungen einer Klimakonferenz', category: 'Umwelt', regelDomain: 'Klimakonferenz', regelContext: 'Anmeldung' },
  { situation: 'Regeln in einem Makerspace', category: 'Technik', regelDomain: 'Makerspace', regelContext: 'Maschinennutzung' },
  { situation: 'Regeln bei einem Weiterbildungszertifikat', category: 'Bildung', regelDomain: 'Weiterbildungszertifikat', regelContext: 'Prüfungsanforderungen' },
  { situation: 'Regeln bei einem Mentoringprogramm', category: 'Arbeit', regelDomain: 'Mentoring', regelContext: 'Laufzeit' },
  { situation: 'AGB einer App zum Deutschlernen', category: 'Sprache', regelDomain: 'Sprach-App', regelContext: 'Abo und Datenschutz' },
  { situation: 'Regeln in einer Teamsitzung (Hybrid)', category: 'Arbeit', regelDomain: 'Teamsitzung', regelContext: 'Hybrid-Teilnahme' },
  { situation: 'Teilnahmebedingungen eines Stipendiums', category: 'Bildung', regelDomain: 'Stipendium', regelContext: 'Auswahlkriterien' },
  { situation: 'Hausordnung eines Sportinternats', category: 'Sport', regelDomain: 'Sportinternat', regelContext: 'Trainingspflichten' },
  { situation: 'Regeln bei einem Ferienlager', category: 'Familie', regelDomain: 'Ferienlager', regelContext: 'Betreuung' },
  { situation: 'Regeln an einem historischen Denkmal', category: 'Kultur', regelDomain: 'Denkmalpark', regelContext: 'Schutzzone' },
  { situation: 'AGB eines Online-Marktplatzes für Handwerker', category: 'Wirtschaft', regelDomain: 'Handwerkermarkt', regelContext: 'Rechnungen' },
  { situation: 'Regeln bei einem Genossenschaftsantrag', category: 'Wohnen', regelDomain: 'Wohnungsbaugenossenschaft', regelContext: 'Einlage' },
  { situation: 'Regeln bei einem Zoobesuch mit Gruppen', category: 'Bildung', regelDomain: 'Zoo', regelContext: 'Gruppenführung' },
  { situation: 'Teilnahmebedingungen Filmfest', category: 'Kultur', regelDomain: 'Filmfest', regelContext: 'Einreichung' },
  { situation: 'Regeln bei einer Bürgerinitiative', category: 'Gesellschaft', regelDomain: 'Bürgerinitiative', regelContext: 'Unterschriften' },
  { situation: 'Hausordnung eines Gästehauses der Firma', category: 'Arbeit', regelDomain: 'Gästehaus', regelContext: 'Reservierung' },
  { situation: 'AGB einer Kinderbetreuungs-App', category: 'Familie', regelDomain: 'Betreuungs-App', regelContext: 'Qualifikationen' },
  { situation: 'Regeln bei einer Förderung für Selbstständige', category: 'Arbeit', regelDomain: 'Selbstständigen-Förderung', regelContext: 'Nachweise' },
  { situation: 'Teilnahmebedingungen Crowdsourcing-Plattform', category: 'Technik', regelDomain: 'Crowdsourcing', regelContext: 'Zahlung' },
  { situation: 'Regeln in einer Umweltbildungs-Initiative', category: 'Umwelt', regelDomain: 'Umweltbildung', regelContext: 'Teilnehmergruppe' },
  { situation: 'Regeln bei Förderprogrammen für energetische Sanierung', category: 'Umwelt', regelDomain: 'KfW-Förderung', regelContext: 'Antragstellung' },
]

// Teil 4 — Kleinanzeigen
export const LESEN_B1_T4: TopicData[] = [
  { situation: 'Ehrenamtliche Tätigkeiten in der Stadt', category: 'Soziales', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für WG-Zimmer in Berlin', category: 'Wohnen', kleinanzeigenCategory: 'Wohnen', itemCount: 8 },
  { situation: 'Anzeigen für Sprachtandem-Partner', category: 'Bildung', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Praktika in NGOs', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für duale Studienplätze', category: 'Bildung', kleinanzeigenCategory: 'Bildung', itemCount: 8 },
  { situation: 'Anzeigen für Mentoringprogramme', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Ferienjobs in der Gastronomie', category: 'Arbeit', kleinanzeigenCategory: 'Gastro', itemCount: 8 },
  { situation: 'Anzeigen für ehrenamtliche Flüchtlingshilfe', category: 'Soziales', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für Lehrkräfte in Nachhilfeinstituten', category: 'Bildung', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Coworking-Spaces im Süden', category: 'Arbeit', kleinanzeigenCategory: 'Büro', itemCount: 8 },
  { situation: 'Anzeigen für Ferienwohnungen an der Ostsee', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Öko-Reisen in Deutschland', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Jobs im Klimaschutz', category: 'Umwelt', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Sprachaufenthalte im Ausland', category: 'Sprache', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Werkstudent*innen-Stellen', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Küsten-Ferienhäuser', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Hebammen-Dienste', category: 'Familie', kleinanzeigenCategory: 'Gesundheit', itemCount: 8 },
  { situation: 'Anzeigen für Musikunterricht online', category: 'Kultur', kleinanzeigenCategory: 'Musik', itemCount: 8 },
  { situation: 'Anzeigen für Fahrradtourenleiter', category: 'Freizeit', kleinanzeigenCategory: 'Freizeit', itemCount: 8 },
  { situation: 'Anzeigen für Büros zum Teilen', category: 'Arbeit', kleinanzeigenCategory: 'Büro', itemCount: 8 },
  { situation: 'Anzeigen für Au-pair-Stellen', category: 'Arbeit', kleinanzeigenCategory: 'Familie', itemCount: 8 },
  { situation: 'Anzeigen für Umweltbildungs-Seminare', category: 'Umwelt', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Vertrauenslehrkräfte', category: 'Bildung', kleinanzeigenCategory: 'Bildung', itemCount: 8 },
  { situation: 'Anzeigen für Lesepaten in Schulen', category: 'Bildung', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für Wochenendseminare zu Achtsamkeit', category: 'Gesundheit', kleinanzeigenCategory: 'Gesundheit', itemCount: 8 },
  { situation: 'Anzeigen für Probewohnen auf dem Land', category: 'Wohnen', kleinanzeigenCategory: 'Wohnen', itemCount: 8 },
  { situation: 'Anzeigen für Führungen durch Industriekultur', category: 'Kultur', kleinanzeigenCategory: 'Kultur', itemCount: 8 },
  { situation: 'Anzeigen für Stellen in der Altenpflege', category: 'Arbeit', kleinanzeigenCategory: 'Gesundheit', itemCount: 8 },
  { situation: 'Anzeigen für Yogalehrer-Ausbildungen', category: 'Gesundheit', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Dachgärten zur Miete', category: 'Wohnen', kleinanzeigenCategory: 'Wohnen', itemCount: 8 },
  { situation: 'Anzeigen für Mitfahrten nach Osteuropa', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Startup-Jobs in der Digitalwirtschaft', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Kursleiter an der VHS', category: 'Bildung', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Weiterbildung in Projektmanagement', category: 'Arbeit', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Einsatzmöglichkeiten im Katastrophenschutz', category: 'Soziales', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für Nachtwachen in der Pflege', category: 'Arbeit', kleinanzeigenCategory: 'Gesundheit', itemCount: 8 },
  { situation: 'Anzeigen für Dolmetschereinsätze in Behörden', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Chöre und Orchester mit freien Plätzen', category: 'Kultur', kleinanzeigenCategory: 'Musik', itemCount: 8 },
  { situation: 'Anzeigen für Kletterpartner', category: 'Sport', kleinanzeigenCategory: 'Sport', itemCount: 8 },
  { situation: 'Anzeigen für vegane Kochkurse', category: 'Essen', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Bürgerjournalismus-Projekte', category: 'Gesellschaft', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für politische Bildung Workshops', category: 'Gesellschaft', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Ferienprogramme für Kinder', category: 'Familie', kleinanzeigenCategory: 'Familie', itemCount: 8 },
  { situation: 'Anzeigen für Workshops zu digitalem Fotografieren', category: 'Kultur', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Konferenzen im Bereich Energie', category: 'Umwelt', kleinanzeigenCategory: 'Veranstaltung', itemCount: 8 },
  { situation: 'Anzeigen für Fachkräfte in der Sozialarbeit', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Inklusions-Paten', category: 'Soziales', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für Wohnungstausch-Programme', category: 'Wohnen', kleinanzeigenCategory: 'Wohnen', itemCount: 8 },
  { situation: 'Anzeigen für Online-Meetings zu Demokratiebildung', category: 'Gesellschaft', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Kurse zum Thema Datenschutz', category: 'Technik', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für ehrenamtliche Koordinatoren', category: 'Soziales', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für Freelance-Designer', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Content-Kreative', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Sprachlehrer an der Universität', category: 'Bildung', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Doktorandenstellen', category: 'Wissenschaft', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Coaching-Partnerschaften', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Workshops zur Kreislaufwirtschaft', category: 'Umwelt', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Förderprogramme im Kulturbereich', category: 'Kultur', kleinanzeigenCategory: 'Förderung', itemCount: 8 },
  { situation: 'Anzeigen für interkulturelle Begegnungen', category: 'Gesellschaft', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für ökologische Bauprojekte', category: 'Umwelt', kleinanzeigenCategory: 'Wohnen', itemCount: 8 },
]

// Teil 5 — Lückentext (komplexe Briefe)
export const LESEN_B1_T5: TopicData[] = [
  { situation: 'Beschwerde an ein Hotel nach dem Urlaub', category: 'Reise', textTopic: 'Hotelbeschwerde', textGenre: 'Brief' },
  { situation: 'Bewerbungsanschreiben auf eine Stelle', category: 'Arbeit', textTopic: 'Bewerbung', textGenre: 'Brief' },
  { situation: 'Mail an die Krankenkasse wegen Rechnung', category: 'Gesundheit', textTopic: 'Rechnung prüfen', textGenre: 'E-Mail' },
  { situation: 'Brief an den Vermieter wegen Mietminderung', category: 'Wohnen', textTopic: 'Mietminderung', textGenre: 'Brief' },
  { situation: 'Beschwerde beim Fernsehsender', category: 'Gesellschaft', textTopic: 'Programm', textGenre: 'Brief' },
  { situation: 'Brief an einen Freund mit Ratschlägen', category: 'Privat', textTopic: 'Lebensratschlag', textGenre: 'Brief' },
  { situation: 'E-Mail an die Personalabteilung wegen Gehaltsverhandlung', category: 'Arbeit', textTopic: 'Gehaltsverhandlung', textGenre: 'E-Mail' },
  { situation: 'Anschreiben zu einer Stipendiumsbewerbung', category: 'Bildung', textTopic: 'Stipendium', textGenre: 'Anschreiben' },
  { situation: 'Beschwerde beim Online-Shop über defekte Ware', category: 'Verbraucher', textTopic: 'Defekte Ware', textGenre: 'E-Mail' },
  { situation: 'Brief an einen Politiker wegen Verkehrsberuhigung', category: 'Gesellschaft', textTopic: 'Tempo 30', textGenre: 'Brief' },
  { situation: 'E-Mail an die Versicherung wegen Schaden', category: 'Verbraucher', textTopic: 'Schadensmeldung', textGenre: 'E-Mail' },
  { situation: 'Brief an die Redaktion einer Zeitung', category: 'Gesellschaft', textTopic: 'Leserbrief', textGenre: 'Brief' },
  { situation: 'Brief an den Bürgermeister wegen Radwegausbau', category: 'Gesellschaft', textTopic: 'Radwege', textGenre: 'Brief' },
  { situation: 'E-Mail an eine Reisefirma wegen Rückerstattung', category: 'Reise', textTopic: 'Rückerstattung', textGenre: 'E-Mail' },
  { situation: 'Anschreiben für ein Auslandssemester', category: 'Bildung', textTopic: 'Auslandssemester', textGenre: 'Anschreiben' },
  { situation: 'Beschwerde bei der Hausverwaltung wegen Heizung', category: 'Wohnen', textTopic: 'Heizung defekt', textGenre: 'Brief' },
  { situation: 'Brief an eine Kollegin mit Feedback', category: 'Arbeit', textTopic: 'Feedback', textGenre: 'Brief' },
  { situation: 'E-Mail an den Energieversorger wegen Tarifs', category: 'Verbraucher', textTopic: 'Tarifwechsel', textGenre: 'E-Mail' },
  { situation: 'Beschwerde beim Fernbusbetreiber', category: 'Verkehr', textTopic: 'Verspätung', textGenre: 'Brief' },
  { situation: 'Anschreiben einer Praktikumsbewerbung', category: 'Arbeit', textTopic: 'Praktikum', textGenre: 'Anschreiben' },
  { situation: 'Brief an die Schule wegen Konflikten', category: 'Familie', textTopic: 'Schulsituation', textGenre: 'Brief' },
  { situation: 'E-Mail an einen Kollegen wegen Projektwechsel', category: 'Arbeit', textTopic: 'Projektwechsel', textGenre: 'E-Mail' },
  { situation: 'Beschwerde beim Flughafen wegen Gepäck', category: 'Reise', textTopic: 'Gepäckverlust', textGenre: 'Brief' },
  { situation: 'Brief an eine Stadtbücherei wegen Veranstaltung', category: 'Kultur', textTopic: 'Veranstaltung', textGenre: 'Brief' },
  { situation: 'E-Mail an die Eltern-Initiative', category: 'Familie', textTopic: 'Mitwirkung', textGenre: 'E-Mail' },
  { situation: 'Anschreiben zur Bewerbung um ein Stipendium für duales Studium', category: 'Bildung', textTopic: 'Duales Studium', textGenre: 'Anschreiben' },
  { situation: 'Brief an die Schulleitung wegen Elternabend', category: 'Familie', textTopic: 'Elternabend', textGenre: 'Brief' },
  { situation: 'Beschwerde beim Paketdienst wegen Lieferung', category: 'Verbraucher', textTopic: 'Falsche Lieferung', textGenre: 'Brief' },
  { situation: 'Leserbrief zur Wohnungsfrage', category: 'Gesellschaft', textTopic: 'Mietenpolitik', textGenre: 'Leserbrief' },
  { situation: 'Brief an das Finanzamt wegen Einspruch', category: 'Behörde', textTopic: 'Einspruch', textGenre: 'Brief' },
  { situation: 'E-Mail an eine Universitätsverwaltung wegen Immatrikulation', category: 'Bildung', textTopic: 'Immatrikulation', textGenre: 'E-Mail' },
  { situation: 'Beschwerde bei einem Streaming-Dienst', category: 'Verbraucher', textTopic: 'Service', textGenre: 'E-Mail' },
  { situation: 'Brief an eine Initiative wegen Spende', category: 'Soziales', textTopic: 'Spende', textGenre: 'Brief' },
  { situation: 'E-Mail an eine Konferenzorganisation', category: 'Arbeit', textTopic: 'Konferenzanmeldung', textGenre: 'E-Mail' },
  { situation: 'Brief an ein Reisebüro mit Sonderwünschen', category: 'Reise', textTopic: 'Sonderreise', textGenre: 'Brief' },
  { situation: 'E-Mail an das Kultusministerium wegen Anerkennung', category: 'Bildung', textTopic: 'Zeugnis anerkennen', textGenre: 'E-Mail' },
  { situation: 'Beschwerde beim Kundenservice einer Bank', category: 'Finanzen', textTopic: 'Kontoproblem', textGenre: 'Brief' },
  { situation: 'Brief an ein Restaurant wegen Buffet-Service', category: 'Essen', textTopic: 'Servicebeschwerde', textGenre: 'Brief' },
  { situation: 'E-Mail an einen Unternehmensverband', category: 'Arbeit', textTopic: 'Mitgliedschaft', textGenre: 'E-Mail' },
  { situation: 'Beschwerde an die Tafel wegen Organisation', category: 'Soziales', textTopic: 'Organisation', textGenre: 'Brief' },
  { situation: 'Brief an einen Mentor mit Bitte um Gespräch', category: 'Arbeit', textTopic: 'Mentoring', textGenre: 'Brief' },
  { situation: 'E-Mail an einen Galeristen wegen Ausstellung', category: 'Kultur', textTopic: 'Ausstellung', textGenre: 'E-Mail' },
  { situation: 'Beschwerde bei einem Konzertveranstalter', category: 'Kultur', textTopic: 'Konzertabsage', textGenre: 'Brief' },
  { situation: 'Brief an einen Verein wegen Austritt', category: 'Soziales', textTopic: 'Austritt', textGenre: 'Brief' },
  { situation: 'E-Mail an ein Umweltamt wegen Sauberkeit', category: 'Umwelt', textTopic: 'Müll am Ufer', textGenre: 'E-Mail' },
  { situation: 'Brief an einen Verlag wegen Manuskript', category: 'Kultur', textTopic: 'Manuskript', textGenre: 'Brief' },
  { situation: 'E-Mail an eine Sprachschule wegen Probestunde', category: 'Bildung', textTopic: 'Probestunde', textGenre: 'E-Mail' },
  { situation: 'Leserbrief zur Nachhaltigkeit', category: 'Umwelt', textTopic: 'Nachhaltigkeit', textGenre: 'Leserbrief' },
  { situation: 'E-Mail an eine Sportschule wegen Trainerlizenz', category: 'Sport', textTopic: 'Trainerlizenz', textGenre: 'E-Mail' },
  { situation: 'Brief an eine Kita-Leitung wegen Beschwerde', category: 'Familie', textTopic: 'Kita-Beschwerde', textGenre: 'Brief' },
  { situation: 'E-Mail an den Betriebsrat wegen Arbeitszeit', category: 'Arbeit', textTopic: 'Arbeitszeit', textGenre: 'E-Mail' },
  { situation: 'Brief an einen Sportverein mit Vorschlag', category: 'Sport', textTopic: 'Vereinsvorschlag', textGenre: 'Brief' },
  { situation: 'E-Mail an die Deutsche Bahn wegen Service', category: 'Verkehr', textTopic: 'Service-Beschwerde', textGenre: 'E-Mail' },
  { situation: 'Brief an einen Arzt mit Danksagung', category: 'Gesundheit', textTopic: 'Dank', textGenre: 'Brief' },
  { situation: 'E-Mail an einen Museumsdirektor wegen Sonderausstellung', category: 'Kultur', textTopic: 'Ausstellungsanfrage', textGenre: 'E-Mail' },
  { situation: 'Brief an eine Redaktion mit Themenvorschlag', category: 'Gesellschaft', textTopic: 'Themenvorschlag', textGenre: 'Brief' },
  { situation: 'E-Mail an ein Weiterbildungsinstitut', category: 'Bildung', textTopic: 'Weiterbildung', textGenre: 'E-Mail' },
  { situation: 'Brief an einen Nachbarschaftsverein', category: 'Gesellschaft', textTopic: 'Mitwirkung', textGenre: 'Brief' },
  { situation: 'E-Mail an ein Forschungsinstitut wegen Praktikum', category: 'Wissenschaft', textTopic: 'Forschungspraktikum', textGenre: 'E-Mail' },
  { situation: 'Leserbrief zur Debatte um Verkehrswende', category: 'Gesellschaft', textTopic: 'Verkehrswende', textGenre: 'Leserbrief' },
]
