// Темы для модуля Lesen A2 — все 5 Teile.

import type { TopicData } from '@/lib/topic-sampler'

// Teil 1 — Blog (richtig/falsch)
export const LESEN_A2_T1: TopicData[] = [
  { situation: 'Umzug in eine andere Stadt', category: 'Wohnen', sceneHint: 'Blog über Umzug nach Köln', blogAuthor: 'Marie' },
  { situation: 'Wochenendausflug mit Freunden', category: 'Reise', sceneHint: 'Kurztrip in die Sächsische Schweiz', blogAuthor: 'Tim' },
  { situation: 'Sportverein beitreten', category: 'Freizeit', sceneHint: 'erster Monat im Fußballverein', blogAuthor: 'Leila' },
  { situation: 'Meine ersten Nebenkosten', category: 'Wohnen', sceneHint: 'Nebenkostenabrechnung verstehen', blogAuthor: 'David' },
  { situation: 'Mein Praktikum im Kindergarten', category: 'Arbeit', sceneHint: 'sechs Wochen Kita', blogAuthor: 'Nadja' },
  { situation: 'Ein Jahr Homeoffice', category: 'Arbeit', sceneHint: 'Rückblick und Tipps', blogAuthor: 'Simon' },
  { situation: 'Mein neues Fahrrad-Abo', category: 'Verkehr', sceneHint: 'Leihfahrrad statt Kauf', blogAuthor: 'Elif' },
  { situation: 'Zum ersten Mal wählen gehen', category: 'Gesellschaft', sceneHint: 'Erstwähler', blogAuthor: 'Linus' },
  { situation: 'Meine erste Steuererklärung', category: 'Alltag', sceneHint: 'Elster-Formular', blogAuthor: 'Marta' },
  { situation: 'Ein Praktikum im Ausland', category: 'Arbeit', sceneHint: 'Erasmus in Wien', blogAuthor: 'Hanna' },
  { situation: 'Meine WG-Zeit in Berlin', category: 'Wohnen', sceneHint: 'drei Monate WG-Leben', blogAuthor: 'Ravi' },
  { situation: 'Mein Fitnessstart', category: 'Gesundheit', sceneHint: '30 Tage Programm', blogAuthor: 'Sonja' },
  { situation: 'Mein erster Deutschprüfungstag', category: 'Bildung', sceneHint: 'Goethe A2', blogAuthor: 'Bruno' },
  { situation: 'Meine neue Lieblings-App', category: 'Alltag', sceneHint: 'Haushaltsbuch-App', blogAuthor: 'Yasmin' },
  { situation: 'Ein Wochenende in Leipzig', category: 'Reise', sceneHint: 'Kurzurlaub', blogAuthor: 'Piotr' },
  { situation: 'Mein erster Ausbildungstag', category: 'Arbeit', sceneHint: 'Einzelhandelsausbildung', blogAuthor: 'Laila' },
  { situation: 'Ein Projekt im Schrebergarten', category: 'Freizeit', sceneHint: 'Tomaten pflanzen', blogAuthor: 'Uwe' },
  { situation: 'Ein Monat ohne Fleisch', category: 'Gesundheit', sceneHint: 'vegetarisches Experiment', blogAuthor: 'Chiara' },
  { situation: 'Mein Umgang mit dem Deutschland-Ticket', category: 'Verkehr', sceneHint: 'Pendeln mit 49€', blogAuthor: 'Kerem' },
  { situation: 'Mein Sprachkurs und meine Fortschritte', category: 'Sprache', sceneHint: 'B1 in Sicht', blogAuthor: 'Ana' },
  { situation: 'Ein Wochenende in Hamburg', category: 'Reise', sceneHint: 'Hafenstadt entdecken', blogAuthor: 'Johannes' },
  { situation: 'Mein erster Besuch bei der Krankenkasse', category: 'Gesundheit', sceneHint: 'Fragen zur Versicherung', blogAuthor: 'Camila' },
  { situation: 'Eine Woche ohne Internet', category: 'Alltag', sceneHint: 'Selbstversuch', blogAuthor: 'Mats' },
  { situation: 'Meine Ausbildung in der Pflege', category: 'Arbeit', sceneHint: 'Pflegeschule', blogAuthor: 'Eva' },
  { situation: 'Mein erstes Oktoberfest', category: 'Feste', sceneHint: 'Trachten und Brezen', blogAuthor: 'Sebastian' },
  { situation: 'Mein erster Elternabend', category: 'Familie', sceneHint: 'Grundschule', blogAuthor: 'Nora' },
  { situation: 'Ein Wochenende in den Alpen', category: 'Reise', sceneHint: 'Wandern im Allgäu', blogAuthor: 'Tobias' },
  { situation: 'Zwei Wochen Kurzarbeit', category: 'Arbeit', sceneHint: 'Was bedeutet Kurzarbeit', blogAuthor: 'Ilhan' },
  { situation: 'Mein Einzug in ein Studentenwohnheim', category: 'Wohnen', sceneHint: 'Zimmer einrichten', blogAuthor: 'Mila' },
  { situation: 'Mein erster Arzttermin ohne Übersetzer', category: 'Gesundheit', sceneHint: 'Allein beim Hausarzt', blogAuthor: 'Nabila' },
  { situation: 'Ein Monat Fahrrad statt Auto', category: 'Umwelt', sceneHint: 'Klimaversuch', blogAuthor: 'Jonas' },
  { situation: 'Mein erstes Deutsch-Interview', category: 'Arbeit', sceneHint: 'Bewerbungsgespräch', blogAuthor: 'Selin' },
  { situation: 'Mein Start im dualen Studium', category: 'Bildung', sceneHint: 'duales Studium Maschinenbau', blogAuthor: 'Paul' },
  { situation: 'Eine Woche bei einer Gastfamilie', category: 'Reise', sceneHint: 'Bayerische Gastfamilie', blogAuthor: 'Asmaa' },
  { situation: 'Mein neuer Nebenjob', category: 'Arbeit', sceneHint: 'Kellnern im Café', blogAuthor: 'Milo' },
  { situation: 'Meine erste Wohnungsübergabe', category: 'Wohnen', sceneHint: 'Vermieter und Protokoll', blogAuthor: 'Svea' },
  { situation: 'Ein Ausflug mit dem Fahrradclub', category: 'Freizeit', sceneHint: 'ADFC-Tour', blogAuthor: 'Florian' },
  { situation: 'Ein Semester im Ausland', category: 'Bildung', sceneHint: 'Erasmus Lissabon', blogAuthor: 'Mira' },
  { situation: 'Ein Tag im Integrationskurs', category: 'Bildung', sceneHint: 'BAMF-Kurs', blogAuthor: 'Kareem' },
  { situation: 'Mein Lieblings-Supermarkt', category: 'Alltag', sceneHint: 'Rossmann vs Edeka', blogAuthor: 'Irina' },
  { situation: 'Eine Woche nur regional einkaufen', category: 'Umwelt', sceneHint: 'Hofladen-Experiment', blogAuthor: 'Jette' },
  { situation: 'Mein neuer Lieblingspodcast', category: 'Freizeit', sceneHint: 'Podcast auf Deutsch', blogAuthor: 'Klara' },
  { situation: 'Eine Tour durch das Ruhrgebiet', category: 'Reise', sceneHint: 'Industriekultur', blogAuthor: 'Eren' },
  { situation: 'Mein neues Ehrenamt im Lesecafé', category: 'Soziales', sceneHint: 'Alltagshilfe', blogAuthor: 'Rebecca' },
  { situation: 'Mein Weg durch das Jobcenter', category: 'Arbeit', sceneHint: 'ALG II Antrag', blogAuthor: 'Maxim' },
  { situation: 'Ein Monat ohne Zucker', category: 'Gesundheit', sceneHint: 'Ernährungsumstellung', blogAuthor: 'Chloe' },
  { situation: 'Mein erster Skiurlaub in den Alpen', category: 'Reise', sceneHint: 'Skikurs', blogAuthor: 'Patryk' },
  { situation: 'Mein erstes Mal Kassenbon einreichen', category: 'Alltag', sceneHint: 'Cashback-App', blogAuthor: 'Lisbeth' },
  { situation: 'Mein neues Hobby: Töpfern', category: 'Freizeit', sceneHint: 'Kurs im Atelier', blogAuthor: 'Finja' },
  { situation: 'Meine Arbeit beim Bürgerbüro', category: 'Arbeit', sceneHint: 'Werkstudent im Amt', blogAuthor: 'Henning' },
  { situation: 'Meine erste Wohnungssuche', category: 'Wohnen', sceneHint: 'Portale und Besichtigungen', blogAuthor: 'Alina' },
  { situation: 'Meine erste Bewerbungsmappe', category: 'Arbeit', sceneHint: 'Lebenslauf auf Deutsch', blogAuthor: 'Rania' },
  { situation: 'Mein Sonntag auf dem Flohmarkt', category: 'Freizeit', sceneHint: 'Mauerpark Berlin', blogAuthor: 'Ayşegül' },
  { situation: 'Meine Radtour an der Donau', category: 'Reise', sceneHint: 'Donauradweg', blogAuthor: 'Samuel' },
  { situation: 'Ein Wochenende im Schwarzwald', category: 'Reise', sceneHint: 'Wandern und Kuchen', blogAuthor: 'Lina' },
  { situation: 'Mein Umzug in eine kleine Stadt', category: 'Wohnen', sceneHint: 'vom Land zurück aufs Land', blogAuthor: 'Antonia' },
  { situation: 'Meine Erfahrungen als Au-pair', category: 'Arbeit', sceneHint: 'Au-pair in Hamburg', blogAuthor: 'Lucia' },
  { situation: 'Mein Wechsel der Krankenkasse', category: 'Gesundheit', sceneHint: 'gesetzliche Kasse wechseln', blogAuthor: 'Nils' },
  { situation: 'Mein erster Online-Kurs an der VHS', category: 'Bildung', sceneHint: 'VHS Online Kurs', blogAuthor: 'Ivana' },
  { situation: 'Meine Erfahrung mit einem Sprachtandem', category: 'Sprache', sceneHint: 'Deutsch-Spanisch', blogAuthor: 'Diego' },
]

// Teil 2 — Zeitungsartikel
export const LESEN_A2_T2: TopicData[] = [
  { situation: 'Neue Buslinie verbindet Stadtteile', category: 'Verkehr', articleSource: 'Lokalzeitung' },
  { situation: 'Junge Menschen lesen weniger Zeitung', category: 'Gesellschaft', articleSource: 'Tageszeitung' },
  { situation: 'Schulgarten-Projekt an Grundschulen', category: 'Bildung', articleSource: 'Regionalblatt' },
  { situation: 'Fahrradverleih in der Innenstadt wird erweitert', category: 'Verkehr', articleSource: 'Stadtteilzeitung' },
  { situation: 'Neue Mensa an der Universität', category: 'Bildung', articleSource: 'Unizeitung' },
  { situation: 'Stadtbibliothek führt Online-Ausleihe ein', category: 'Kultur', articleSource: 'Lokalzeitung' },
  { situation: 'Solarzellen auf städtischen Gebäuden', category: 'Umwelt', articleSource: 'Stadtzeitung' },
  { situation: 'Mehr Radwege für die Innenstadt', category: 'Verkehr', articleSource: 'Lokalnachrichten' },
  { situation: 'Neue Sprachkurse für Zugezogene', category: 'Bildung', articleSource: 'Amtsblatt' },
  { situation: 'Wohnraum für Studierende wird knapper', category: 'Wohnen', articleSource: 'Tageszeitung' },
  { situation: 'Supermarkt eröffnet unverpackt-Abteilung', category: 'Umwelt', articleSource: 'Wochenblatt' },
  { situation: 'Pfand auf Milchflaschen soll kommen', category: 'Umwelt', articleSource: 'Tageszeitung' },
  { situation: 'Bürgeramt testet Online-Termine', category: 'Stadt', articleSource: 'Amtsblatt' },
  { situation: 'Senioren nutzen häufiger Smartphones', category: 'Gesellschaft', articleSource: 'Tageszeitung' },
  { situation: 'Freiwilligenagentur sucht Helfer', category: 'Soziales', articleSource: 'Lokalpresse' },
  { situation: 'Neues Konzerthaus öffnet seine Türen', category: 'Kultur', articleSource: 'Feuilleton' },
  { situation: 'Immer mehr Hobby-Imker in der Stadt', category: 'Umwelt', articleSource: 'Regionalseite' },
  { situation: 'Weihnachtsmärkte starten früher', category: 'Feste', articleSource: 'Lokalzeitung' },
  { situation: 'Mehr Familien ziehen aufs Land', category: 'Gesellschaft', articleSource: 'Tageszeitung' },
  { situation: 'Neue Haltestelle für die Straßenbahn', category: 'Verkehr', articleSource: 'Lokalpresse' },
  { situation: 'Kinderbetreuung am Wochenende wird erweitert', category: 'Familie', articleSource: 'Amtsblatt' },
  { situation: 'Deutsch lernen per App', category: 'Bildung', articleSource: 'Tageszeitung' },
  { situation: 'Neues Schwimmbad mit Therme', category: 'Freizeit', articleSource: 'Regionalseite' },
  { situation: 'Immer mehr Menschen arbeiten im Homeoffice', category: 'Arbeit', articleSource: 'Tageszeitung' },
  { situation: 'Regionale Lebensmittel im Trend', category: 'Gesellschaft', articleSource: 'Wirtschaftsteil' },
  { situation: 'Stadt bietet kostenfreien Deutschkurs', category: 'Bildung', articleSource: 'Lokalzeitung' },
  { situation: 'Radweg am See wird eröffnet', category: 'Freizeit', articleSource: 'Regionalseite' },
  { situation: 'Erste Carsharing-Stationen in Vororten', category: 'Verkehr', articleSource: 'Lokalzeitung' },
  { situation: 'Schüler gründen eigene Zeitung', category: 'Bildung', articleSource: 'Schulseite' },
  { situation: 'Hundekotstationen in Parks verdoppelt', category: 'Stadt', articleSource: 'Lokalnachrichten' },
  { situation: 'Weihnachtsbaum aus der Region', category: 'Feste', articleSource: 'Lokalzeitung' },
  { situation: 'Jugendzentrum bekommt neue Räume', category: 'Soziales', articleSource: 'Regionalseite' },
  { situation: 'Baustelle auf der A7 verursacht Stau', category: 'Verkehr', articleSource: 'Verkehrsseite' },
  { situation: 'Sommerferien starten später', category: 'Bildung', articleSource: 'Lokalzeitung' },
  { situation: 'Museum öffnet einmal im Monat abends', category: 'Kultur', articleSource: 'Kulturseite' },
  { situation: 'Neues Freiwilligenjahr für Geflüchtete', category: 'Soziales', articleSource: 'Tageszeitung' },
  { situation: 'E-Scooter sorgen für Diskussionen', category: 'Verkehr', articleSource: 'Lokalzeitung' },
  { situation: 'Stadt testet kostenfreies WLAN', category: 'Technik', articleSource: 'Wirtschaftsteil' },
  { situation: 'Radeln an der Donau wird beliebter', category: 'Reise', articleSource: 'Reiseseite' },
  { situation: 'Neue Ausbildungsplätze in der Pflege', category: 'Arbeit', articleSource: 'Stellenanzeigenteil' },
  { situation: 'Eltern protestieren für mehr Kita-Plätze', category: 'Familie', articleSource: 'Lokalzeitung' },
  { situation: 'Neues Kulturprogramm für Jugendliche', category: 'Kultur', articleSource: 'Regionalseite' },
  { situation: 'Obst und Gemüse direkt vom Bauern', category: 'Alltag', articleSource: 'Wochenblatt' },
  { situation: 'Klimastreik in der Innenstadt', category: 'Gesellschaft', articleSource: 'Tageszeitung' },
  { situation: 'Immer mehr Menschen pendeln weit', category: 'Gesellschaft', articleSource: 'Wirtschaftsteil' },
  { situation: 'Frauenhaus öffnet Beratungsstelle', category: 'Soziales', articleSource: 'Lokalzeitung' },
  { situation: 'Stadtteilgarten für alle', category: 'Umwelt', articleSource: 'Lokalpresse' },
  { situation: 'Deutschkurs speziell für Mütter', category: 'Bildung', articleSource: 'Regionalseite' },
  { situation: 'Neues Café für Geflüchtete und Einheimische', category: 'Soziales', articleSource: 'Lokalzeitung' },
  { situation: 'Bibliothek bietet Kurse für Eltern', category: 'Familie', articleSource: 'Regionalseite' },
  { situation: 'Stadt plant neuen Bolzplatz', category: 'Sport', articleSource: 'Lokalnachrichten' },
  { situation: 'Neue Öffnungszeiten im Schwimmbad', category: 'Freizeit', articleSource: 'Stadtzeitung' },
  { situation: 'Senioren lernen Tablet-Nutzung', category: 'Gesellschaft', articleSource: 'Lokalzeitung' },
  { situation: 'Schulweg soll sicherer werden', category: 'Bildung', articleSource: 'Regionalseite' },
  { situation: 'Weihnachtsaktion im Obdachlosenzentrum', category: 'Soziales', articleSource: 'Lokalnachrichten' },
  { situation: 'Sportverein sucht neue Trainer', category: 'Sport', articleSource: 'Stellenanzeigenteil' },
  { situation: 'Neuer Wochenmarkt für Bio-Produkte', category: 'Essen', articleSource: 'Lokalzeitung' },
  { situation: 'Ein Stadtteil testet autofreies Wochenende', category: 'Umwelt', articleSource: 'Lokalzeitung' },
  { situation: 'Jobangebote in der IT nehmen zu', category: 'Arbeit', articleSource: 'Wirtschaftsteil' },
  { situation: 'Neues Konzept gegen Einsamkeit', category: 'Soziales', articleSource: 'Tageszeitung' },
]

// Teil 3 — Regeltext
export const LESEN_A2_T3: TopicData[] = [
  { situation: 'Ausleihbedingungen in einer Mediathek', category: 'Bibliothek', regelDomain: 'Mediathek', regelContext: 'Leihfristen' },
  { situation: 'Benutzerordnung Sportzentrum', category: 'Sport', regelDomain: 'Sportzentrum', regelContext: 'Zutritt' },
  { situation: 'Mülltrennung in der Mietwohnung', category: 'Wohnen', regelDomain: 'Mietshaus', regelContext: 'Biotonne und Gelber Sack' },
  { situation: 'Regeln im Volkshochschul-Kurs', category: 'Bildung', regelDomain: 'Volkshochschule', regelContext: 'Teilnahme' },
  { situation: 'Parkhausordnung einer Stadthalle', category: 'Verkehr', regelDomain: 'Parkhaus', regelContext: 'Gebühren' },
  { situation: 'Regeln im Hallenbad mit Sauna', category: 'Freizeit', regelDomain: 'Hallenbad', regelContext: 'Saunaregeln' },
  { situation: 'Hygieneregeln in der Fitnesslounge', category: 'Sport', regelDomain: 'Fitnessstudio', regelContext: 'Sauberkeit' },
  { situation: 'Hausordnung im Studentenwohnheim', category: 'Wohnen', regelDomain: 'Studentenwohnheim', regelContext: 'Gemeinschaftsküche' },
  { situation: 'Benutzungsordnung E-Scooter', category: 'Verkehr', regelDomain: 'E-Scooter-Verleih', regelContext: 'Park- und Fahrregeln' },
  { situation: 'Regeln bei einem Volksfest', category: 'Feste', regelDomain: 'Volksfest', regelContext: 'Sicherheitsregeln' },
  { situation: 'Benutzungsregeln im Co-Working-Space', category: 'Arbeit', regelDomain: 'Co-Working-Space', regelContext: 'Kaffee und Ruhe' },
  { situation: 'Regeln im Senioren-Café', category: 'Soziales', regelDomain: 'Senioren-Café', regelContext: 'Besuch' },
  { situation: 'Regeln im Kino während Vorstellungen', category: 'Kultur', regelDomain: 'Kino', regelContext: 'Essen und Trinken' },
  { situation: 'Parkordnung einer Bergstation', category: 'Reise', regelDomain: 'Bergstation', regelContext: 'Parkgebühren' },
  { situation: 'Regeln im Sprachcafé der Stadt', category: 'Sprache', regelDomain: 'Sprachcafé', regelContext: 'Teilnahme' },
  { situation: 'Benutzungsregeln Gemeinschaftsgarten', category: 'Umwelt', regelDomain: 'Gemeinschaftsgarten', regelContext: 'Ernte' },
  { situation: 'Regeln im Kletterpark', category: 'Freizeit', regelDomain: 'Kletterpark', regelContext: 'Sicherheitsausrüstung' },
  { situation: 'Hausordnung einer Ferienwohnung am Meer', category: 'Reise', regelDomain: 'Ferienwohnung', regelContext: 'Checkout' },
  { situation: 'Regeln für das Parken im Hof', category: 'Wohnen', regelDomain: 'Hof', regelContext: 'Stellplätze' },
  { situation: 'Regeln bei der Teilnahme am Stadtlauf', category: 'Sport', regelDomain: 'Stadtlauf', regelContext: 'Startnummer' },
  { situation: 'Regeln für Eltern in der Kita', category: 'Familie', regelDomain: 'Kita', regelContext: 'Bring- und Abholzeiten' },
  { situation: 'Regeln beim Blutspendetermin', category: 'Gesundheit', regelDomain: 'Blutspendezentrum', regelContext: 'Voraussetzungen' },
  { situation: 'Regeln in der Schwimmschule für Erwachsene', category: 'Sport', regelDomain: 'Schwimmschule', regelContext: 'Kursbesuch' },
  { situation: 'Hausordnung eines Hostels', category: 'Reise', regelDomain: 'Hostel', regelContext: 'Nachtruhe' },
  { situation: 'Regeln für den Besuch im Tierheim', category: 'Soziales', regelDomain: 'Tierheim', regelContext: 'Spaziergänge' },
  { situation: 'Regeln im Fernzug der Deutschen Bahn', category: 'Verkehr', regelDomain: 'Deutsche Bahn', regelContext: 'Reservierung' },
  { situation: 'Regeln bei der Teilnahme an einem Chor', category: 'Kultur', regelDomain: 'Chor', regelContext: 'Proben' },
  { situation: 'Regeln eines Schrebergartenvereins', category: 'Umwelt', regelDomain: 'Kleingartenverein', regelContext: 'Arbeitsstunden' },
  { situation: 'Regeln bei einem offenen Sonntag im Museum', category: 'Kultur', regelDomain: 'Museum', regelContext: 'Eintritt' },
  { situation: 'Regeln beim Besuch des Flughafens', category: 'Reise', regelDomain: 'Flughafen', regelContext: 'Sicherheitskontrolle' },
  { situation: 'Regeln im Freibad für Kinder', category: 'Familie', regelDomain: 'Freibad', regelContext: 'Aufsichtspflicht' },
  { situation: 'Benutzungsregeln Stadtteilfitness', category: 'Sport', regelDomain: 'Stadtteilfitness', regelContext: 'Gerätenutzung' },
  { situation: 'Hausordnung eines Mehrgenerationenhauses', category: 'Wohnen', regelDomain: 'Mehrgenerationenhaus', regelContext: 'Gemeinschaftsräume' },
  { situation: 'Regeln im Jugendclub', category: 'Soziales', regelDomain: 'Jugendclub', regelContext: 'Altersgrenze' },
  { situation: 'Regeln im Restaurant mit Buffet', category: 'Essen', regelDomain: 'Buffet-Restaurant', regelContext: 'Portionen' },
  { situation: 'Benutzungsregeln VHS-Rechnerraum', category: 'Bildung', regelDomain: 'VHS-Rechnerraum', regelContext: 'Kennwort' },
  { situation: 'Regeln im Familien-Saunaclub', category: 'Freizeit', regelDomain: 'Saunaclub', regelContext: 'Familienzeiten' },
  { situation: 'Regeln beim Besuch des Therapiezentrums', category: 'Gesundheit', regelDomain: 'Therapiezentrum', regelContext: 'Termintreue' },
  { situation: 'Regeln bei einer Sommerakademie', category: 'Bildung', regelDomain: 'Sommerakademie', regelContext: 'Kurswahl' },
  { situation: 'Hausordnung im Ferienpark', category: 'Reise', regelDomain: 'Ferienpark', regelContext: 'Anreise' },
  { situation: 'Regeln im Großraumbüro', category: 'Arbeit', regelDomain: 'Großraumbüro', regelContext: 'Telefonzonen' },
  { situation: 'Regeln bei einem Tag der offenen Tür', category: 'Veranstaltung', regelDomain: 'Tag der offenen Tür', regelContext: 'Anmeldung' },
  { situation: 'Regeln im Club-Fitnessstudio', category: 'Sport', regelDomain: 'Club-Fitness', regelContext: 'Mitgliederkarte' },
  { situation: 'Regeln bei der Teilnahme an einer Stadtführung', category: 'Kultur', regelDomain: 'Stadtführung', regelContext: 'Pünktlichkeit' },
  { situation: 'Regeln bei einer Betriebsausflug-Organisation', category: 'Arbeit', regelDomain: 'Betriebsausflug', regelContext: 'Teilnahme' },
  { situation: 'Regeln im Besucherzentrum des Nationalparks', category: 'Umwelt', regelDomain: 'Nationalpark', regelContext: 'Wege' },
  { situation: 'Regeln für Haustiere im Hotel', category: 'Reise', regelDomain: 'Hotel', regelContext: 'Haustiere' },
  { situation: 'Regeln im Kochstudio', category: 'Freizeit', regelDomain: 'Kochstudio', regelContext: 'Hygiene' },
  { situation: 'Regeln beim Besuch des Frauenarztes', category: 'Gesundheit', regelDomain: 'Arztpraxis', regelContext: 'Anmeldung' },
  { situation: 'Regeln in der Krabbelstube', category: 'Familie', regelDomain: 'Krabbelstube', regelContext: 'Hygiene' },
  { situation: 'Regeln für Gruppenräume in der Bibliothek', category: 'Bildung', regelDomain: 'Stadtbibliothek', regelContext: 'Reservierung' },
  { situation: 'Regeln beim Kirchenkonzert', category: 'Kultur', regelDomain: 'Kirche', regelContext: 'Einlass' },
  { situation: 'Regeln am Hundestrand', category: 'Freizeit', regelDomain: 'Hundestrand', regelContext: 'Leinenpflicht' },
  { situation: 'Regeln bei der Schwimmprüfung', category: 'Sport', regelDomain: 'Schwimmprüfung', regelContext: 'Ausweis' },
  { situation: 'Regeln bei der Teilnahme am Carsharing', category: 'Verkehr', regelDomain: 'Carsharing', regelContext: 'Buchung' },
  { situation: 'Regeln bei einem Deutschkurs-Ausflug', category: 'Bildung', regelDomain: 'Sprachkurs-Ausflug', regelContext: 'Anmeldung' },
  { situation: 'Regeln im internen Café der Firma', category: 'Arbeit', regelDomain: 'Betriebscafé', regelContext: 'Zutritt' },
  { situation: 'Regeln bei einer Einwohnerversammlung', category: 'Gesellschaft', regelDomain: 'Einwohnerversammlung', regelContext: 'Redezeit' },
  { situation: 'Regeln beim Fahrradtechnik-Workshop', category: 'Freizeit', regelDomain: 'Fahrradwerkstatt', regelContext: 'Werkzeugnutzung' },
  { situation: 'Regeln bei der Buchrückgabe im Automaten', category: 'Bibliothek', regelDomain: 'Automat Bibliothek', regelContext: 'Barcode' },
]

// Teil 4 — Kleinanzeigen
export const LESEN_A2_T4: TopicData[] = [
  { situation: 'Anzeigen für Nebenjobs', category: 'Arbeit', kleinanzeigenCategory: 'Job', itemCount: 8 },
  { situation: 'Kurse an der Volkshochschule', category: 'Bildung', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für gemeinsame Reisen', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für WG-Zimmer', category: 'Wohnen', kleinanzeigenCategory: 'Wohnen', itemCount: 8 },
  { situation: 'Anzeigen für Sprachtandems', category: 'Sprache', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Musikkurse', category: 'Kultur', kleinanzeigenCategory: 'Musik', itemCount: 8 },
  { situation: 'Anzeigen für Babysitter-Dienste', category: 'Familie', kleinanzeigenCategory: 'Familie', itemCount: 8 },
  { situation: 'Anzeigen für Umzugshelfer', category: 'Wohnen', kleinanzeigenCategory: 'Dienstleistungen', itemCount: 8 },
  { situation: 'Anzeigen für Sportpartner', category: 'Sport', kleinanzeigenCategory: 'Sport', itemCount: 8 },
  { situation: 'Anzeigen für Praktika', category: 'Arbeit', kleinanzeigenCategory: 'Arbeit', itemCount: 8 },
  { situation: 'Anzeigen für Minijobs im Supermarkt', category: 'Arbeit', kleinanzeigenCategory: 'Minijob', itemCount: 8 },
  { situation: 'Anzeigen für Fahrradtouren', category: 'Freizeit', kleinanzeigenCategory: 'Freizeit', itemCount: 8 },
  { situation: 'Anzeigen für Sprachkurse am Wochenende', category: 'Bildung', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Ehrenamtliche', category: 'Soziales', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für Schülerjobs', category: 'Arbeit', kleinanzeigenCategory: 'Schülerjob', itemCount: 8 },
  { situation: 'Anzeigen für Reitbeteiligungen', category: 'Sport', kleinanzeigenCategory: 'Sport', itemCount: 8 },
  { situation: 'Anzeigen für Kinderbetreuung', category: 'Familie', kleinanzeigenCategory: 'Familie', itemCount: 8 },
  { situation: 'Anzeigen für Haushaltshilfen', category: 'Alltag', kleinanzeigenCategory: 'Dienstleistungen', itemCount: 8 },
  { situation: 'Anzeigen für Computerkurse', category: 'Bildung', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Sprachreisen', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Skireisen', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Nachhilfe Mathematik', category: 'Bildung', kleinanzeigenCategory: 'Bildung', itemCount: 8 },
  { situation: 'Anzeigen für Spaziergangspartner', category: 'Soziales', kleinanzeigenCategory: 'Freizeit', itemCount: 8 },
  { situation: 'Anzeigen für Fahrgemeinschaften', category: 'Verkehr', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Kochkurse', category: 'Freizeit', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Radtourenpartner', category: 'Freizeit', kleinanzeigenCategory: 'Freizeit', itemCount: 8 },
  { situation: 'Anzeigen für Fitness-Kurse', category: 'Sport', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Kleingarten-Pachten', category: 'Umwelt', kleinanzeigenCategory: 'Garten', itemCount: 8 },
  { situation: 'Anzeigen für Wohnungstausch im Urlaub', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Volksfeste und Helfer', category: 'Feste', kleinanzeigenCategory: 'Feste', itemCount: 8 },
  { situation: 'Anzeigen für ehrenamtliche Dolmetscher', category: 'Soziales', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für Musikinstrumente-Tausch', category: 'Kultur', kleinanzeigenCategory: 'Musik', itemCount: 8 },
  { situation: 'Anzeigen für Tandempartner Deutsch-Englisch', category: 'Sprache', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für E-Bikes zum Leihen', category: 'Verkehr', kleinanzeigenCategory: 'Verkehr', itemCount: 8 },
  { situation: 'Anzeigen für Jobs mit Wohnung', category: 'Arbeit', kleinanzeigenCategory: 'Job+Wohnen', itemCount: 8 },
  { situation: 'Anzeigen für Garagen zu vermieten', category: 'Wohnen', kleinanzeigenCategory: 'Wohnen', itemCount: 8 },
  { situation: 'Anzeigen für Seniorentreff-Dienste', category: 'Soziales', kleinanzeigenCategory: 'Soziales', itemCount: 8 },
  { situation: 'Anzeigen für Yoga-Retreats', category: 'Gesundheit', kleinanzeigenCategory: 'Gesundheit', itemCount: 8 },
  { situation: 'Anzeigen für Kulturführungen', category: 'Kultur', kleinanzeigenCategory: 'Kultur', itemCount: 8 },
  { situation: 'Anzeigen für Wochenendjobs in der Gastronomie', category: 'Arbeit', kleinanzeigenCategory: 'Gastro', itemCount: 8 },
  { situation: 'Anzeigen für Lesepatenschaften', category: 'Bildung', kleinanzeigenCategory: 'Ehrenamt', itemCount: 8 },
  { situation: 'Anzeigen für Hundeausführer', category: 'Alltag', kleinanzeigenCategory: 'Tiere', itemCount: 8 },
  { situation: 'Anzeigen für Schwimmbegleiter', category: 'Sport', kleinanzeigenCategory: 'Sport', itemCount: 8 },
  { situation: 'Anzeigen für Eselwanderungen', category: 'Freizeit', kleinanzeigenCategory: 'Freizeit', itemCount: 8 },
  { situation: 'Anzeigen für Wohnmobil-Vermietung', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Apartments an der Nordsee', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Deutsch-Nachhilfe online', category: 'Bildung', kleinanzeigenCategory: 'Bildung', itemCount: 8 },
  { situation: 'Anzeigen für Büromöbel-Tausch', category: 'Arbeit', kleinanzeigenCategory: 'Büro', itemCount: 8 },
  { situation: 'Anzeigen für Kunstkurse', category: 'Kultur', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Gartenarbeit als Dienstleistung', category: 'Umwelt', kleinanzeigenCategory: 'Garten', itemCount: 8 },
  { situation: 'Anzeigen für Hochzeitslocations', category: 'Feste', kleinanzeigenCategory: 'Feste', itemCount: 8 },
  { situation: 'Anzeigen für Geburtstagsparty-Dienste', category: 'Feste', kleinanzeigenCategory: 'Feste', itemCount: 8 },
  { situation: 'Anzeigen für Fotografie-Workshops', category: 'Kultur', kleinanzeigenCategory: 'Kultur', itemCount: 8 },
  { situation: 'Anzeigen für Joggen in der Gruppe', category: 'Sport', kleinanzeigenCategory: 'Sport', itemCount: 8 },
  { situation: 'Anzeigen für Online-Deutsch-Stammtisch', category: 'Sprache', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Mittagstisch im Viertel', category: 'Essen', kleinanzeigenCategory: 'Essen', itemCount: 8 },
  { situation: 'Anzeigen für Kinderflohmarkt', category: 'Familie', kleinanzeigenCategory: 'Familie', itemCount: 8 },
  { situation: 'Anzeigen für Studenten-Hilfsdienste', category: 'Arbeit', kleinanzeigenCategory: 'Job', itemCount: 8 },
  { situation: 'Anzeigen für Konzertmitfahrten', category: 'Kultur', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Wanderpartner im Harz', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
]

// Teil 5 — Lückentext
export const LESEN_A2_T5: TopicData[] = [
  { situation: 'Anmeldung zu einem Sportkurs', category: 'Freizeit', textTopic: 'Sportkurs-Anmeldung', textGenre: 'E-Mail' },
  { situation: 'Mail an die Reiseagentur', category: 'Reise', textTopic: 'Reiseangebot erfragen', textGenre: 'E-Mail' },
  { situation: 'Bestätigung eines Termins beim Arzt', category: 'Gesundheit', textTopic: 'Terminbestätigung', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Krankenkasse wegen Bescheinigung', category: 'Gesundheit', textTopic: 'Bescheinigung', textGenre: 'E-Mail' },
  { situation: 'Antwort auf eine Wohnungsanzeige', category: 'Wohnen', textTopic: 'Wohnungsanfrage', textGenre: 'E-Mail' },
  { situation: 'Bewerbung für einen Nebenjob', category: 'Arbeit', textTopic: 'Nebenjob-Bewerbung', textGenre: 'E-Mail' },
  { situation: 'E-Mail an das Bürgeramt wegen Ummeldung', category: 'Behörde', textTopic: 'Ummeldung', textGenre: 'E-Mail' },
  { situation: 'Bestätigung einer Hotelbuchung', category: 'Reise', textTopic: 'Buchungsbestätigung', textGenre: 'E-Mail' },
  { situation: 'Bitte um Urlaubsprospekt', category: 'Reise', textTopic: 'Prospekt', textGenre: 'E-Mail' },
  { situation: 'E-Mail an den Vermieter wegen Defekt', category: 'Wohnen', textTopic: 'Defekt melden', textGenre: 'E-Mail' },
  { situation: 'Rückfrage bei der Kfz-Werkstatt', category: 'Alltag', textTopic: 'Autoreparatur', textGenre: 'E-Mail' },
  { situation: 'Anfrage an die Sprachschule wegen Einstufungstest', category: 'Bildung', textTopic: 'Einstufungstest', textGenre: 'E-Mail' },
  { situation: 'Rückmeldung an die Kita wegen Ausflug', category: 'Familie', textTopic: 'Kita-Ausflug', textGenre: 'E-Mail' },
  { situation: 'E-Mail an den Sportverein wegen Mitgliedschaft', category: 'Sport', textTopic: 'Anmeldung', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Hausverwaltung wegen Waschküche', category: 'Wohnen', textTopic: 'Waschküche', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Apotheke wegen Rezept', category: 'Gesundheit', textTopic: 'Rezept abholen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Friseursalon wegen Termin', category: 'Alltag', textTopic: 'Terminverschiebung', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Volkshochschule wegen Zertifikat', category: 'Bildung', textTopic: 'Zertifikat erfragen', textGenre: 'E-Mail' },
  { situation: 'Anfrage bei einem Sprachtandem-Portal', category: 'Sprache', textTopic: 'Tandem-Partner', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Deutsche Bahn wegen Erstattung', category: 'Reise', textTopic: 'Fahrkarten-Erstattung', textGenre: 'E-Mail' },
  { situation: 'Anfrage bei einer Reinigungsfirma', category: 'Alltag', textTopic: 'Reinigung buchen', textGenre: 'E-Mail' },
  { situation: 'E-Mail an das Fitnessstudio wegen Probetraining', category: 'Sport', textTopic: 'Probetraining', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Hausmeister wegen Briefkasten', category: 'Wohnen', textTopic: 'Briefkasten defekt', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Schule wegen Fehltag', category: 'Bildung', textTopic: 'Fehltag melden', textGenre: 'E-Mail' },
  { situation: 'Bestätigung einer Reservierung im Restaurant', category: 'Essen', textTopic: 'Reservierung bestätigen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Musikschule', category: 'Kultur', textTopic: 'Musikkurs-Start', textGenre: 'E-Mail' },
  { situation: 'Rückmeldung an den Arbeitgeber wegen Gespräch', category: 'Arbeit', textTopic: 'Bewerbungsgespräch bestätigen', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Elternvertretung', category: 'Familie', textTopic: 'Elternvertretung', textGenre: 'E-Mail' },
  { situation: 'Anfrage an die Krankenhausrezeption', category: 'Gesundheit', textTopic: 'Besuchszeiten', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Tierarzt wegen Termin', category: 'Alltag', textTopic: 'Tierarzttermin', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Stadtbibliothek wegen Ausweis', category: 'Bildung', textTopic: 'Bibliotheksausweis', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Englischkurs wegen Fehltag', category: 'Bildung', textTopic: 'Fehltag', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Hochzeitslocation', category: 'Feste', textTopic: 'Hochzeitsanfrage', textGenre: 'E-Mail' },
  { situation: 'Anfrage bei einem Umzugsunternehmen', category: 'Wohnen', textTopic: 'Umzug planen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Kindergarten wegen Geburtstag', category: 'Familie', textTopic: 'Geburtstag feiern', textGenre: 'E-Mail' },
  { situation: 'Bestätigung einer Kursanmeldung', category: 'Bildung', textTopic: 'Kurs bestätigen', textGenre: 'E-Mail' },
  { situation: 'Rückfrage bei einer Versicherung', category: 'Alltag', textTopic: 'Versicherungsvertrag', textGenre: 'E-Mail' },
  { situation: 'E-Mail an eine Babysitterin', category: 'Familie', textTopic: 'Babysitten verabreden', textGenre: 'E-Mail' },
  { situation: 'Anfrage bei einem Reiseführer', category: 'Reise', textTopic: 'Stadtführung', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Sportlehrer', category: 'Bildung', textTopic: 'Sportunterricht', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Arbeitskollegin wegen Geburtstagsüberraschung', category: 'Arbeit', textTopic: 'Überraschung', textGenre: 'E-Mail' },
  { situation: 'Rückmeldung auf eine Einladung', category: 'Privat', textTopic: 'Einladung annehmen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Bibliothek wegen Lesung', category: 'Kultur', textTopic: 'Lesung besuchen', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Abendschule', category: 'Bildung', textTopic: 'Abitur-Kurs', textGenre: 'E-Mail' },
  { situation: 'Anfrage bei einem Kinderarzt', category: 'Gesundheit', textTopic: 'Untersuchung', textGenre: 'E-Mail' },
  { situation: 'Bestätigung einer Spende', category: 'Soziales', textTopic: 'Spende', textGenre: 'E-Mail' },
  { situation: 'E-Mail an einen Sprachcoach', category: 'Sprache', textTopic: 'Coaching', textGenre: 'E-Mail' },
  { situation: 'Anfrage bei einer Tanzschule', category: 'Freizeit', textTopic: 'Tanzkurs', textGenre: 'E-Mail' },
  { situation: 'Nachricht an das Fundbüro', category: 'Stadt', textTopic: 'Fundsache', textGenre: 'E-Mail' },
  { situation: 'Rückfrage bei einer Eisdiele', category: 'Alltag', textTopic: 'Torten-Bestellung', textGenre: 'E-Mail' },
  { situation: 'E-Mail an ein Autohaus', category: 'Verkehr', textTopic: 'Probefahrt', textGenre: 'E-Mail' },
  { situation: 'Anfrage bei einer Ferienakademie', category: 'Bildung', textTopic: 'Kursprogramm', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Elterninitiative', category: 'Familie', textTopic: 'Mitarbeit', textGenre: 'E-Mail' },
  { situation: 'E-Mail an einen Camping-Platz', category: 'Reise', textTopic: 'Stellplatz', textGenre: 'E-Mail' },
  { situation: 'Anfrage bei einem Möbelhaus', category: 'Wohnen', textTopic: 'Lieferung', textGenre: 'E-Mail' },
  { situation: 'Bestätigung einer Probestunde', category: 'Kultur', textTopic: 'Probestunde Musik', textGenre: 'E-Mail' },
  { situation: 'E-Mail an die Schwimmschule', category: 'Sport', textTopic: 'Schwimmkurs', textGenre: 'E-Mail' },
  { situation: 'Rückmeldung an den Fußballverein', category: 'Sport', textTopic: 'Training', textGenre: 'E-Mail' },
  { situation: 'Nachricht an das Reisebüro wegen Visum', category: 'Reise', textTopic: 'Visum-Unterlagen', textGenre: 'E-Mail' },
  { situation: 'E-Mail an eine Pension im Allgäu', category: 'Reise', textTopic: 'Zimmer buchen', textGenre: 'E-Mail' },
]
