// Темы для модуля Lesen A1 — все 5 Teile.
// Поля: {situation, category, sceneHint?} — основные для промптов.
// Дополнительные поля (blogTopic, articleSource, regelDomain и т.д.) обогащают {topic_extra}.

import type { TopicData } from '@/lib/topic-sampler'

// Teil 1 — Blogbeitrag (richtig/falsch)
export const LESEN_A1_T1: TopicData[] = [
  { situation: 'Mein neues Haustier', category: 'Alltag', sceneHint: 'Studentin bloggt über ihre Katze', blogAuthor: 'Studentin Anna' },
  { situation: 'Erster Tag im neuen Job', category: 'Arbeit', sceneHint: 'Berufsanfänger schreibt im Blog', blogAuthor: 'Lukas, 22' },
  { situation: 'Mein Hobby: Kochen lernen', category: 'Freizeit', sceneHint: 'Food-Blog einer Anfängerin', blogAuthor: 'Hobbyköchin Mira' },
  { situation: 'Wochenende in Berlin', category: 'Reise', sceneHint: 'Kurztrip-Blog', blogAuthor: 'Studentin Lea' },
  { situation: 'Meine erste Wohnung', category: 'Wohnen', sceneHint: 'Umzugstagebuch', blogAuthor: 'Jonas' },
  { situation: 'Mein Deutschkurs', category: 'Bildung', sceneHint: 'Sprachschülerin erzählt', blogAuthor: 'Elena aus Italien' },
  { situation: 'Mein erstes Fahrrad in Deutschland', category: 'Alltag', sceneHint: 'Reifenflickerei', blogAuthor: 'Pablo aus Spanien' },
  { situation: 'Ein Tag im Schwimmbad', category: 'Freizeit', sceneHint: 'Sommertag mit Familie', blogAuthor: 'Papa-Blog Thomas' },
  { situation: 'Einkaufen im Supermarkt', category: 'Alltag', sceneHint: 'erste Erfahrung', blogAuthor: 'Maria aus Brasilien' },
  { situation: 'Frühstück am Sonntag', category: 'Essen', sceneHint: 'Brunch-Routine', blogAuthor: 'Hanna' },
  { situation: 'Mein Nachbar hilft mir', category: 'Wohnen', sceneHint: 'Nachbarschaftsgeschichte', blogAuthor: 'Sofia' },
  { situation: 'Meine Lieblingsbäckerei', category: 'Essen', sceneHint: 'Brezeln und Brötchen', blogAuthor: 'Ayşe' },
  { situation: 'Ein Ausflug in den Park', category: 'Freizeit', sceneHint: 'Tiergarten Berlin', blogAuthor: 'Olga' },
  { situation: 'Mein erster Tag an der Uni', category: 'Bildung', sceneHint: 'TU München', blogAuthor: 'Mateo' },
  { situation: 'Ich lerne Deutsch mit Serien', category: 'Sprache', sceneHint: 'Netflix auf Deutsch', blogAuthor: 'Yuki' },
  { situation: 'Mein erster Arztbesuch', category: 'Gesundheit', sceneHint: 'Hausarztpraxis', blogAuthor: 'Hasan' },
  { situation: 'Samstag auf dem Markt', category: 'Alltag', sceneHint: 'Wochenmarkt', blogAuthor: 'Nadia' },
  { situation: 'Meine neue Mitbewohnerin', category: 'Wohnen', sceneHint: 'WG-Leben', blogAuthor: 'Rafael' },
  { situation: 'Mein Lieblingscafé', category: 'Freizeit', sceneHint: 'Kaffee und Kuchen', blogAuthor: 'Ines' },
  { situation: 'Ein Wochenende am See', category: 'Reise', sceneHint: 'Starnberger See', blogAuthor: 'Leon' },
  { situation: 'Mein erster Winter in Deutschland', category: 'Alltag', sceneHint: 'Schnee und Kälte', blogAuthor: 'Kofi aus Ghana' },
  { situation: 'Mein erster Besuch im Kino', category: 'Freizeit', sceneHint: 'Film auf Deutsch', blogAuthor: 'Noor' },
  { situation: 'Ein Tag im Zoo', category: 'Freizeit', sceneHint: 'Zoo Leipzig', blogAuthor: 'Linda' },
  { situation: 'Mein neuer Lieblingsplatz', category: 'Alltag', sceneHint: 'Bank am Fluss', blogAuthor: 'Taro' },
  { situation: 'Deutsch-Tandem mit einem Freund', category: 'Sprache', sceneHint: '1 Std pro Woche', blogAuthor: 'Amelie' },
  { situation: 'Mein Tag im Homeoffice', category: 'Arbeit', sceneHint: 'neuer Arbeitsrhythmus', blogAuthor: 'Timo' },
  { situation: 'Mein erstes Oktoberfest', category: 'Feste', sceneHint: 'Wiesn München', blogAuthor: 'Clara' },
  { situation: 'Einkaufen auf dem Flohmarkt', category: 'Freizeit', sceneHint: 'Schätze entdecken', blogAuthor: 'Mila' },
  { situation: 'Eine neue Sprachpartnerin', category: 'Sprache', sceneHint: 'Tandem-Café', blogAuthor: 'Ömer' },
  { situation: 'Mein neuer Lieblingsbäcker', category: 'Essen', sceneHint: 'Brot aus dem Holzofen', blogAuthor: 'Fabio' },
  { situation: 'Ein Nachmittag im Museum', category: 'Freizeit', sceneHint: 'Dresdner Kunsthalle', blogAuthor: 'Emma' },
  { situation: 'Mein erstes Mal Zug fahren', category: 'Reise', sceneHint: 'Regionalbahn', blogAuthor: 'Kamal' },
  { situation: 'Meine erste deutsche Freundin', category: 'Alltag', sceneHint: 'Freundschaft erzählen', blogAuthor: 'Luis' },
  { situation: 'Mein Lieblings-Park', category: 'Freizeit', sceneHint: 'Grünanlage in Hamburg', blogAuthor: 'Fatima' },
  { situation: 'Ein Tag am Meer', category: 'Reise', sceneHint: 'Ostsee-Urlaub', blogAuthor: 'Jan' },
  { situation: 'Mein neues Fahrrad', category: 'Alltag', sceneHint: 'Fahrradkauf', blogAuthor: 'Sara' },
  { situation: 'Ich koche zum ersten Mal', category: 'Essen', sceneHint: 'Nudelsalat-Rezept', blogAuthor: 'Mateus' },
  { situation: 'Ein Abend mit Freunden', category: 'Alltag', sceneHint: 'Spieleabend', blogAuthor: 'Tim' },
  { situation: 'Ich kaufe Bücher auf Deutsch', category: 'Bildung', sceneHint: 'Lesestoff', blogAuthor: 'Rania' },
  { situation: 'Mein erstes Mal Bäcker-Brötchen', category: 'Essen', sceneHint: 'neue Lieblingssorte', blogAuthor: 'Ivan' },
  { situation: 'Ein Tag im Bergpark', category: 'Reise', sceneHint: 'Wilhelmshöhe Kassel', blogAuthor: 'Oskar' },
  { situation: 'Ein Wochenende in Leipzig', category: 'Reise', sceneHint: 'Stadterkundung', blogAuthor: 'Greta' },
  { situation: 'Mein erster Kochkurs', category: 'Freizeit', sceneHint: 'VHS Kochkurs', blogAuthor: 'Nora' },
  { situation: 'Mein Lieblingsrestaurant', category: 'Essen', sceneHint: 'italienische Küche', blogAuthor: 'Mia' },
  { situation: 'Ein Tag im Wald', category: 'Freizeit', sceneHint: 'Spaziergang im Spessart', blogAuthor: 'Paul' },
  { situation: 'Mein neuer Hund', category: 'Alltag', sceneHint: 'Tierheim-Adoption', blogAuthor: 'Jasmin' },
  { situation: 'Meine erste Wohnungsbesichtigung', category: 'Wohnen', sceneHint: 'Altbau in Köln', blogAuthor: 'Hugo' },
  { situation: 'Mein Deutschtest', category: 'Bildung', sceneHint: 'Prüfungsvorbereitung', blogAuthor: 'Laura' },
  { situation: 'Ein Nachmittag mit Oma', category: 'Familie', sceneHint: 'Kuchen backen', blogAuthor: 'Jakob' },
  { situation: 'Mein neues Hobby: Fotografieren', category: 'Freizeit', sceneHint: 'Kamerakauf', blogAuthor: 'Rania' },
  { situation: 'Mein erster Schulweg', category: 'Bildung', sceneHint: 'Volksschule Nürnberg', blogAuthor: 'Felix' },
  { situation: 'Mein Umzug in eine neue Stadt', category: 'Wohnen', sceneHint: 'nach Stuttgart', blogAuthor: 'Stella' },
  { situation: 'Ein Tag ohne Handy', category: 'Alltag', sceneHint: 'Digital Detox', blogAuthor: 'Niklas' },
  { situation: 'Mein Weg zur Arbeit mit dem Bus', category: 'Alltag', sceneHint: 'Stadtbus 52', blogAuthor: 'Pınar' },
  { situation: 'Mein neuer Sprachkurs', category: 'Sprache', sceneHint: 'VHS-Abendkurs', blogAuthor: 'Dejan' },
  { situation: 'Ein Wochenende mit der Familie', category: 'Familie', sceneHint: 'Familientreffen', blogAuthor: 'Lara' },
  { situation: 'Ein Besuch beim Friseur', category: 'Alltag', sceneHint: 'neue Frisur', blogAuthor: 'Meryem' },
  { situation: 'Mein Fitnessstudio-Start', category: 'Gesundheit', sceneHint: 'erste Trainingswoche', blogAuthor: 'Ben' },
  { situation: 'Mein Abend im Theater', category: 'Freizeit', sceneHint: 'Stadttheater', blogAuthor: 'Isabel' },
  { situation: 'Ein Tag ohne Auto', category: 'Alltag', sceneHint: 'nur ÖPNV', blogAuthor: 'Tomás' },
]

// Teil 2 — Zeitungsartikel (Multiple Choice)
export const LESEN_A1_T2: TopicData[] = [
  { situation: 'Neues Schwimmbad in der Stadt', category: 'Lokalnachrichten', articleSource: 'Stadtzeitung' },
  { situation: 'Bücherei öffnet sonntags', category: 'Stadt', articleSource: 'Gemeindeblatt' },
  { situation: 'Weihnachtsmarkt eröffnet', category: 'Veranstaltung', articleSource: 'Lokalzeitung' },
  { situation: 'Neuer Radweg im Park', category: 'Verkehr', articleSource: 'Stadtteilzeitung' },
  { situation: 'Kinderfest am Wochenende', category: 'Familie', articleSource: 'Wochenblatt' },
  { situation: 'Neue Buslinie nach X', category: 'Verkehr', articleSource: 'Stadtzeitung' },
  { situation: 'Straßenfest in der Innenstadt', category: 'Veranstaltung', articleSource: 'Lokalzeitung' },
  { situation: 'Flohmarkt am Samstag', category: 'Freizeit', articleSource: 'Anzeigenblatt' },
  { situation: 'Spielplatz wird renoviert', category: 'Stadt', articleSource: 'Lokalpresse' },
  { situation: 'Stadtbibliothek bekommt neue Computer', category: 'Bildung', articleSource: 'Gemeindeblatt' },
  { situation: 'Konzert im Stadtpark', category: 'Kultur', articleSource: 'Kulturkalender' },
  { situation: 'Neuer Supermarkt öffnet', category: 'Wirtschaft', articleSource: 'Anzeigenblatt' },
  { situation: 'Sommerkino am Hauptplatz', category: 'Kultur', articleSource: 'Stadtmagazin' },
  { situation: 'Schulfest der Grundschule', category: 'Bildung', articleSource: 'Schulzeitung' },
  { situation: 'Café öffnet neu in der Altstadt', category: 'Wirtschaft', articleSource: 'Lokalzeitung' },
  { situation: 'Stadtlauf am Sonntag', category: 'Sport', articleSource: 'Sportteil' },
  { situation: 'Neues Museum für Kinder', category: 'Kultur', articleSource: 'Kulturredaktion' },
  { situation: 'Verkehr: Baustelle auf Hauptstraße', category: 'Verkehr', articleSource: 'Lokalnachrichten' },
  { situation: 'Stadtteilfest im Mai', category: 'Veranstaltung', articleSource: 'Stadtteilzeitung' },
  { situation: 'Neue Kita im Viertel', category: 'Familie', articleSource: 'Gemeindeblatt' },
  { situation: 'Tag der offenen Tür in der Schule', category: 'Bildung', articleSource: 'Schulzeitung' },
  { situation: 'Weihnachtskonzert im Dom', category: 'Kultur', articleSource: 'Kulturseite' },
  { situation: 'Wintermarkt in der Fußgängerzone', category: 'Veranstaltung', articleSource: 'Wochenblatt' },
  { situation: 'Einfache Öffnungszeiten der Post', category: 'Alltag', articleSource: 'Amtsblatt' },
  { situation: 'Neues Café im Bahnhof', category: 'Alltag', articleSource: 'Lokalzeitung' },
  { situation: 'Sportplatz wird erneuert', category: 'Sport', articleSource: 'Sportteil' },
  { situation: 'Neuer Fahrradverleih in der Stadt', category: 'Verkehr', articleSource: 'Lokalzeitung' },
  { situation: 'Frühlingsfest am See', category: 'Veranstaltung', articleSource: 'Stadtzeitung' },
  { situation: 'Große Spendenaktion für das Tierheim', category: 'Soziales', articleSource: 'Lokalpresse' },
  { situation: 'Neue Straßenbahnlinie in Betrieb', category: 'Verkehr', articleSource: 'Lokalnachrichten' },
  { situation: 'Bauernmarkt jeden Mittwoch', category: 'Alltag', articleSource: 'Stadtblatt' },
  { situation: 'Kinderbuchmesse in der Stadthalle', category: 'Kultur', articleSource: 'Kulturseite' },
  { situation: 'Wasserrutsche im Freibad erneuert', category: 'Freizeit', articleSource: 'Lokalzeitung' },
  { situation: 'Laternenfest im Kindergarten', category: 'Familie', articleSource: 'Gemeindeblatt' },
  { situation: 'Laufveranstaltung für Kinder', category: 'Sport', articleSource: 'Sportteil' },
  { situation: 'Neue Öffnungszeiten im Rathaus', category: 'Stadt', articleSource: 'Amtsblatt' },
  { situation: 'Eröffnung einer neuen Eisdiele', category: 'Alltag', articleSource: 'Wochenblatt' },
  { situation: 'Nikolausfeier in der Kirche', category: 'Feste', articleSource: 'Gemeindeblatt' },
  { situation: 'Parkfest mit Musik und Essen', category: 'Veranstaltung', articleSource: 'Lokalzeitung' },
  { situation: 'Stadtbücherei feiert Geburtstag', category: 'Bildung', articleSource: 'Kulturseite' },
  { situation: 'Neues Lokal mit regionaler Küche', category: 'Essen', articleSource: 'Lokalpresse' },
  { situation: 'Kindertheater im Schloss', category: 'Kultur', articleSource: 'Kulturkalender' },
  { situation: 'Stadt plant mehr Blumen', category: 'Umwelt', articleSource: 'Lokalzeitung' },
  { situation: 'Workshop fürs Fahrrad-Reparieren', category: 'Freizeit', articleSource: 'Wochenblatt' },
  { situation: 'Neuer Yogakurs im Stadtpark', category: 'Gesundheit', articleSource: 'Lokalnachrichten' },
  { situation: 'Bücherflohmarkt am Samstag', category: 'Kultur', articleSource: 'Kulturseite' },
  { situation: 'Neue Ampel an der Schule', category: 'Verkehr', articleSource: 'Stadtblatt' },
  { situation: 'Konzert am Weihnachtsbaum', category: 'Kultur', articleSource: 'Kulturteil' },
  { situation: 'Blutspendeaktion in der Gemeinde', category: 'Soziales', articleSource: 'Amtsblatt' },
  { situation: 'Kinder-Malwettbewerb', category: 'Familie', articleSource: 'Schulzeitung' },
  { situation: 'Kino zeigt Kinderfilme', category: 'Kultur', articleSource: 'Kulturkalender' },
  { situation: 'Schwimmkurs für Anfänger', category: 'Sport', articleSource: 'Sportteil' },
  { situation: 'Neues Tierheim eröffnet', category: 'Soziales', articleSource: 'Lokalzeitung' },
  { situation: 'Erste-Hilfe-Kurs für alle', category: 'Gesundheit', articleSource: 'Lokalpresse' },
  { situation: 'Lesung im Rathaus', category: 'Kultur', articleSource: 'Kulturseite' },
  { situation: 'Spielplatz-Eröffnung im Neubaugebiet', category: 'Familie', articleSource: 'Stadtzeitung' },
  { situation: 'Stadt sucht Helfer für Stadtputz', category: 'Umwelt', articleSource: 'Gemeindeblatt' },
  { situation: 'Seniorenausflug in die Berge', category: 'Soziales', articleSource: 'Wochenblatt' },
  { situation: 'Müllentsorgung: neue Regeln', category: 'Stadt', articleSource: 'Amtsblatt' },
  { situation: 'Neue Notruf-App der Stadt', category: 'Sicherheit', articleSource: 'Lokalpresse' },
]

// Teil 3 — Regelwerk (ja/nein)
export const LESEN_A1_T3: TopicData[] = [
  { situation: 'Hausordnung eines Wohnhauses', category: 'Wohnen', regelDomain: 'Mietshaus', regelContext: 'Ruhezeiten' },
  { situation: 'Nutzungsregeln einer Bibliothek', category: 'Öffentlicher Ort', regelDomain: 'Stadtbibliothek', regelContext: 'Ausleihe' },
  { situation: 'Regeln im Schwimmbad', category: 'Freizeit', regelDomain: 'Schwimmbad', regelContext: 'Beckenordnung' },
  { situation: 'Benutzungsregeln Kinderspielplatz', category: 'Familie', regelDomain: 'Spielplatz', regelContext: 'Altersregel' },
  { situation: 'Regeln in der Kita', category: 'Familie', regelDomain: 'Kindergarten', regelContext: 'Bringzeiten' },
  { situation: 'Hausordnung im Studentenwohnheim (einfach)', category: 'Wohnen', regelDomain: 'Studentenwohnheim', regelContext: 'Gemeinschaftsräume' },
  { situation: 'Benutzung Waschküche', category: 'Wohnen', regelDomain: 'Waschküche', regelContext: 'Belegplan' },
  { situation: 'Regeln im Fitnessstudio (einfach)', category: 'Sport', regelDomain: 'Fitnessstudio', regelContext: 'Handtuchpflicht' },
  { situation: 'Regeln im Bus', category: 'Verkehr', regelDomain: 'Stadtbus', regelContext: 'Fahrkarte' },
  { situation: 'Regeln im Café (Tische reservieren)', category: 'Freizeit', regelDomain: 'Café', regelContext: 'Selbstbedienung' },
  { situation: 'Hausordnung Ferienwohnung', category: 'Reise', regelDomain: 'Ferienwohnung', regelContext: 'Anreisezeit' },
  { situation: 'Regeln im Museum', category: 'Kultur', regelDomain: 'Museum', regelContext: 'Foto-Verbot' },
  { situation: 'Regeln im Zoo', category: 'Freizeit', regelDomain: 'Zoo', regelContext: 'Fütterungsverbot' },
  { situation: 'Nutzungsordnung Internetcafé', category: 'Alltag', regelDomain: 'Internetcafé', regelContext: 'Zeitlimit' },
  { situation: 'Regeln im Sprachkurs', category: 'Bildung', regelDomain: 'Sprachschule', regelContext: 'Anwesenheit' },
  { situation: 'Regeln für Gäste in der WG', category: 'Wohnen', regelDomain: 'WG', regelContext: 'Besuch anmelden' },
  { situation: 'Parkordnung des Stadtparks', category: 'Öffentlicher Ort', regelDomain: 'Stadtpark', regelContext: 'Hunde an Leine' },
  { situation: 'Benutzungsregeln Sauna', category: 'Freizeit', regelDomain: 'Sauna', regelContext: 'Textilfrei' },
  { situation: 'Regeln im Kino', category: 'Kultur', regelDomain: 'Kino', regelContext: 'Handy aus' },
  { situation: 'Regeln beim Tanzkurs', category: 'Freizeit', regelDomain: 'Tanzschule', regelContext: 'Schuhe wechseln' },
  { situation: 'Regeln am Strand (einfach)', category: 'Freizeit', regelDomain: 'Strandbad', regelContext: 'Flaggensystem' },
  { situation: 'Regeln im Klassenzimmer', category: 'Bildung', regelDomain: 'Schule', regelContext: 'Handy aus' },
  { situation: 'Regeln im Sportverein', category: 'Sport', regelDomain: 'Sportverein', regelContext: 'Mitgliedsbeitrag' },
  { situation: 'Regeln an der Haltestelle', category: 'Verkehr', regelDomain: 'Haltestelle', regelContext: 'Nichtraucher' },
  { situation: 'Regeln in der Bäckerei (Selbstbedienung)', category: 'Alltag', regelDomain: 'Bäckerei', regelContext: 'Zange benutzen' },
  { situation: 'Regeln beim Wandern', category: 'Reise', regelDomain: 'Wanderweg', regelContext: 'Wege nicht verlassen' },
  { situation: 'Regeln beim Mittagessen in der Mensa', category: 'Bildung', regelDomain: 'Mensa', regelContext: 'Tablett abräumen' },
  { situation: 'Benutzungsordnung Hallenbad', category: 'Freizeit', regelDomain: 'Hallenbad', regelContext: 'Duschen vorher' },
  { situation: 'Regeln im Schulbus', category: 'Verkehr', regelDomain: 'Schulbus', regelContext: 'Sitzen bleiben' },
  { situation: 'Regeln in der Sprachschule', category: 'Bildung', regelDomain: 'Sprachschule', regelContext: 'Pünktlichkeit' },
  { situation: 'Regeln im Bürgeramt (Wartebereich)', category: 'Behörde', regelDomain: 'Bürgeramt', regelContext: 'Nummer ziehen' },
  { situation: 'Regeln im Familienzentrum', category: 'Familie', regelDomain: 'Familienzentrum', regelContext: 'Anmeldung nötig' },
  { situation: 'Regeln im Bastelraum der Kita', category: 'Familie', regelDomain: 'Kita', regelContext: 'Aufsicht' },
  { situation: 'Regeln für Gastgeber einer Feier im Mehrfamilienhaus', category: 'Wohnen', regelDomain: 'Wohnhaus', regelContext: 'Nachbarn informieren' },
  { situation: 'Regeln auf dem Campingplatz', category: 'Reise', regelDomain: 'Campingplatz', regelContext: 'Lagerfeuer' },
  { situation: 'Regeln bei einem Feriencamp für Kinder', category: 'Familie', regelDomain: 'Feriencamp', regelContext: 'Nachtruhe' },
  { situation: 'Regeln im Schwimmkurs', category: 'Sport', regelDomain: 'Schwimmkurs', regelContext: 'Aufwärmen' },
  { situation: 'Regeln für die Bibliotheksbenutzung durch Kinder', category: 'Bildung', regelDomain: 'Kinderbibliothek', regelContext: 'Begleitung' },
  { situation: 'Benutzungsregeln Sporthalle', category: 'Sport', regelDomain: 'Sporthalle', regelContext: 'Hallenschuhe' },
  { situation: 'Regeln im Copyshop', category: 'Alltag', regelDomain: 'Copyshop', regelContext: 'Vorkasse' },
  { situation: 'Regeln im Kinderrestaurant', category: 'Essen', regelDomain: 'Kinderrestaurant', regelContext: 'Begleitperson' },
  { situation: 'Regeln bei der Benutzung des Trockners', category: 'Wohnen', regelDomain: 'Gemeinschaftstrockner', regelContext: 'Flusensieb' },
  { situation: 'Regeln bei Fundbüro der Stadt', category: 'Stadt', regelDomain: 'Fundbüro', regelContext: 'Öffnungszeiten' },
  { situation: 'Regeln in einer Tanzschule für Kinder', category: 'Freizeit', regelDomain: 'Tanzschule Kids', regelContext: 'Elternwartebereich' },
  { situation: 'Regeln auf dem Wertstoffhof', category: 'Stadt', regelDomain: 'Wertstoffhof', regelContext: 'sortieren' },
  { situation: 'Regeln in der Eisbahn', category: 'Freizeit', regelDomain: 'Eisbahn', regelContext: 'Helm empfohlen' },
  { situation: 'Regeln im Bastelkurs', category: 'Freizeit', regelDomain: 'Bastelkurs', regelContext: 'Werkzeug zurückgeben' },
  { situation: 'Regeln für die Parkbenutzung nach Einbruch der Dunkelheit', category: 'Stadt', regelDomain: 'Stadtpark', regelContext: 'Schließzeit' },
  { situation: 'Regeln im Familienhotel', category: 'Reise', regelDomain: 'Familienhotel', regelContext: 'Frühstückszeiten' },
  { situation: 'Regeln in der Jugendherberge', category: 'Reise', regelDomain: 'Jugendherberge', regelContext: 'Gemeinschaftsküche' },
  { situation: 'Regeln beim Kindergeburtstag in der Spielhalle', category: 'Familie', regelDomain: 'Spielhalle', regelContext: 'Aufsichtspflicht' },
  { situation: 'Regeln auf dem Fahrradweg', category: 'Verkehr', regelDomain: 'Radweg', regelContext: 'Vorfahrt' },
  { situation: 'Benutzungsregeln im Copyshop der Uni', category: 'Bildung', regelDomain: 'Copyshop Uni', regelContext: 'Studentenausweis' },
  { situation: 'Regeln im Wellenbad', category: 'Freizeit', regelDomain: 'Wellenbad', regelContext: 'keine Rettungswesten leihen' },
  { situation: 'Regeln im Minigolf-Park', category: 'Freizeit', regelDomain: 'Minigolf', regelContext: 'Schläger zurückbringen' },
  { situation: 'Regeln im Stadtmuseum für Kinder', category: 'Kultur', regelDomain: 'Kindermuseum', regelContext: 'Anfassen erlaubt' },
  { situation: 'Regeln im Bus zur Schule', category: 'Verkehr', regelDomain: 'Schulbus', regelContext: 'Anschnallen' },
  { situation: 'Regeln in der Autowerkstatt (Wartebereich)', category: 'Alltag', regelDomain: 'Autowerkstatt', regelContext: 'Bereich betreten' },
  { situation: 'Regeln im Secondhand-Laden', category: 'Alltag', regelDomain: 'Secondhand-Laden', regelContext: 'Anprobe' },
  { situation: 'Regeln in einer Kletterhalle (Kinder)', category: 'Sport', regelDomain: 'Kletterhalle', regelContext: 'Aufsicht' },
]

// Teil 4 — Kleinanzeigen (Zuordnung)
export const LESEN_A1_T4: TopicData[] = [
  { situation: 'Kurzanzeigen für Freizeit und Hobby', category: 'Sport/Verein/Kurs', kleinanzeigenCategory: 'Freizeit', itemCount: 8 },
  { situation: 'Kleinanzeigen für Mietgesuche', category: 'Wohnen', kleinanzeigenCategory: 'Wohnung', itemCount: 8 },
  { situation: 'Verkaufsanzeigen gebrauchter Möbel', category: 'Möbel', kleinanzeigenCategory: 'Möbel', itemCount: 8 },
  { situation: 'Kleinanzeigen für Fahrräder', category: 'Verkehr', kleinanzeigenCategory: 'Fahrrad', itemCount: 8 },
  { situation: 'Anzeigen für Kinderkleidung', category: 'Familie', kleinanzeigenCategory: 'Kleidung', itemCount: 8 },
  { situation: 'Anzeigen für Bücher', category: 'Bildung', kleinanzeigenCategory: 'Bücher', itemCount: 8 },
  { situation: 'Anzeigen für Haustiere', category: 'Alltag', kleinanzeigenCategory: 'Tiere', itemCount: 8 },
  { situation: 'Anzeigen für Gartenartikel', category: 'Wohnen', kleinanzeigenCategory: 'Garten', itemCount: 8 },
  { situation: 'Anzeigen für Sportausrüstung', category: 'Sport', kleinanzeigenCategory: 'Sportgeräte', itemCount: 8 },
  { situation: 'Anzeigen für Küchenartikel', category: 'Alltag', kleinanzeigenCategory: 'Küche', itemCount: 8 },
  { situation: 'Anzeigen für Babyausstattung', category: 'Familie', kleinanzeigenCategory: 'Baby', itemCount: 8 },
  { situation: 'Anzeigen für Spiele und Spielzeug', category: 'Familie', kleinanzeigenCategory: 'Spielzeug', itemCount: 8 },
  { situation: 'Anzeigen für Musikinstrumente', category: 'Freizeit', kleinanzeigenCategory: 'Musik', itemCount: 8 },
  { situation: 'Anzeigen für Kameras', category: 'Freizeit', kleinanzeigenCategory: 'Foto', itemCount: 8 },
  { situation: 'Anzeigen für Schreibtische', category: 'Möbel', kleinanzeigenCategory: 'Möbel', itemCount: 8 },
  { situation: 'Anzeigen für Sofas', category: 'Möbel', kleinanzeigenCategory: 'Möbel', itemCount: 8 },
  { situation: 'Anzeigen für Bettwäsche', category: 'Wohnen', kleinanzeigenCategory: 'Wohnen', itemCount: 8 },
  { situation: 'Anzeigen für Esstische', category: 'Möbel', kleinanzeigenCategory: 'Möbel', itemCount: 8 },
  { situation: 'Anzeigen für Küchengeräte', category: 'Alltag', kleinanzeigenCategory: 'Haushalt', itemCount: 8 },
  { situation: 'Anzeigen für Waschmaschinen', category: 'Alltag', kleinanzeigenCategory: 'Haushalt', itemCount: 8 },
  { situation: 'Anzeigen für Fernseher', category: 'Alltag', kleinanzeigenCategory: 'Elektronik', itemCount: 8 },
  { situation: 'Anzeigen für Rucksäcke', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Kinderwagen', category: 'Familie', kleinanzeigenCategory: 'Baby', itemCount: 8 },
  { situation: 'Anzeigen für Winterkleidung', category: 'Kleidung', kleinanzeigenCategory: 'Kleidung', itemCount: 8 },
  { situation: 'Anzeigen für Handys', category: 'Alltag', kleinanzeigenCategory: 'Elektronik', itemCount: 8 },
  { situation: 'Anzeigen für Fahrradhelme', category: 'Verkehr', kleinanzeigenCategory: 'Fahrrad', itemCount: 8 },
  { situation: 'Anzeigen für Reitzubehör', category: 'Sport', kleinanzeigenCategory: 'Sport', itemCount: 8 },
  { situation: 'Anzeigen für Sprachkurse', category: 'Bildung', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Babysitter', category: 'Familie', kleinanzeigenCategory: 'Familie', itemCount: 8 },
  { situation: 'Anzeigen für Nachhilfe', category: 'Bildung', kleinanzeigenCategory: 'Bildung', itemCount: 8 },
  { situation: 'Anzeigen für WG-Zimmer', category: 'Wohnen', kleinanzeigenCategory: 'Wohnung', itemCount: 8 },
  { situation: 'Anzeigen für Mitfahrgelegenheiten', category: 'Verkehr', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für kleine Jobs im Viertel', category: 'Arbeit', kleinanzeigenCategory: 'Job', itemCount: 8 },
  { situation: 'Anzeigen für Reinigungshilfen', category: 'Alltag', kleinanzeigenCategory: 'Haushalt', itemCount: 8 },
  { situation: 'Anzeigen für Weihnachtsdeko', category: 'Feste', kleinanzeigenCategory: 'Feste', itemCount: 8 },
  { situation: 'Anzeigen für Fahrradanhänger', category: 'Verkehr', kleinanzeigenCategory: 'Fahrrad', itemCount: 8 },
  { situation: 'Anzeigen für Gartenmöbel', category: 'Wohnen', kleinanzeigenCategory: 'Garten', itemCount: 8 },
  { situation: 'Anzeigen für Umzugskisten', category: 'Wohnen', kleinanzeigenCategory: 'Umzug', itemCount: 8 },
  { situation: 'Anzeigen für Kletterausrüstung', category: 'Sport', kleinanzeigenCategory: 'Sport', itemCount: 8 },
  { situation: 'Anzeigen für Skischuhe', category: 'Sport', kleinanzeigenCategory: 'Sport', itemCount: 8 },
  { situation: 'Anzeigen für Hundezubehör', category: 'Alltag', kleinanzeigenCategory: 'Tiere', itemCount: 8 },
  { situation: 'Anzeigen für Katzenzubehör', category: 'Alltag', kleinanzeigenCategory: 'Tiere', itemCount: 8 },
  { situation: 'Anzeigen für Hochbetten', category: 'Möbel', kleinanzeigenCategory: 'Möbel', itemCount: 8 },
  { situation: 'Anzeigen für Rollstühle', category: 'Gesundheit', kleinanzeigenCategory: 'Gesundheit', itemCount: 8 },
  { situation: 'Anzeigen für Stricksachen', category: 'Freizeit', kleinanzeigenCategory: 'Handarbeit', itemCount: 8 },
  { situation: 'Anzeigen für alte Münzen', category: 'Sammeln', kleinanzeigenCategory: 'Sammeln', itemCount: 8 },
  { situation: 'Anzeigen für Heimtrainer', category: 'Sport', kleinanzeigenCategory: 'Sport', itemCount: 8 },
  { situation: 'Anzeigen für Sprachtandems', category: 'Sprache', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Chorbeitritt', category: 'Kultur', kleinanzeigenCategory: 'Musik', itemCount: 8 },
  { situation: 'Anzeigen für Kinderchor', category: 'Familie', kleinanzeigenCategory: 'Musik', itemCount: 8 },
  { situation: 'Anzeigen für Filmclub', category: 'Kultur', kleinanzeigenCategory: 'Kultur', itemCount: 8 },
  { situation: 'Anzeigen für Yogakurse', category: 'Gesundheit', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Buchclub', category: 'Kultur', kleinanzeigenCategory: 'Bücher', itemCount: 8 },
  { situation: 'Anzeigen für Brettspielabende', category: 'Freizeit', kleinanzeigenCategory: 'Freizeit', itemCount: 8 },
  { situation: 'Anzeigen für Wanderpartner', category: 'Reise', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Koch-Events', category: 'Essen', kleinanzeigenCategory: 'Freizeit', itemCount: 8 },
  { situation: 'Anzeigen für Babyschwimmen', category: 'Familie', kleinanzeigenCategory: 'Kurse', itemCount: 8 },
  { situation: 'Anzeigen für Vorlesekreis', category: 'Kultur', kleinanzeigenCategory: 'Kultur', itemCount: 8 },
  { situation: 'Anzeigen für Fahrgemeinschaften zur Arbeit', category: 'Verkehr', kleinanzeigenCategory: 'Reise', itemCount: 8 },
  { situation: 'Anzeigen für Skimitfahrten', category: 'Sport', kleinanzeigenCategory: 'Reise', itemCount: 8 },
]

// Teil 5 — Lückentext
export const LESEN_A1_T5: TopicData[] = [
  { situation: 'E-Mail an die Vermieterin wegen Reparatur', category: 'Wohnen', textTopic: 'Heizung defekt', textGenre: 'E-Mail' },
  { situation: 'Einladung zum Geburtstag', category: 'Privat', textTopic: 'Geburtstag', textGenre: 'Einladung' },
  { situation: 'Kurze Nachricht an den Sprachkurs', category: 'Bildung', textTopic: 'Krankmeldung', textGenre: 'E-Mail' },
  { situation: 'E-Mail an einen Freund über Besuch', category: 'Privat', textTopic: 'Besuchsplanung', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Lehrerin wegen Hausaufgaben', category: 'Bildung', textTopic: 'Hausaufgaben', textGenre: 'Nachricht' },
  { situation: 'E-Mail an das Reisebüro', category: 'Reise', textTopic: 'Urlaub buchen', textGenre: 'E-Mail' },
  { situation: 'Glückwunschkarte zum Schulanfang', category: 'Familie', textTopic: 'Einschulung', textGenre: 'Karte' },
  { situation: 'E-Mail an die Bäckerei wegen Bestellung', category: 'Essen', textTopic: 'Tortenbestellung', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Nachbarn wegen Paket', category: 'Alltag', textTopic: 'Paket abholen', textGenre: 'Nachricht' },
  { situation: 'Gruß aus dem Urlaub an Oma', category: 'Familie', textTopic: 'Urlaubsgruß', textGenre: 'Postkarte' },
  { situation: 'Einladung zum Abendessen', category: 'Privat', textTopic: 'Abendessen', textGenre: 'Einladung' },
  { situation: 'Kurze Dankesnachricht', category: 'Privat', textTopic: 'Danke nach Party', textGenre: 'Nachricht' },
  { situation: 'E-Mail an den Fußballtrainer', category: 'Sport', textTopic: 'Training absagen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Freundin wegen Treffpunkt', category: 'Privat', textTopic: 'Treffpunkt klären', textGenre: 'Nachricht' },
  { situation: 'E-Mail an die Sprachschule wegen Stundenplan', category: 'Bildung', textTopic: 'Stundenplan', textGenre: 'E-Mail' },
  { situation: 'Kurze Nachricht an den Kollegen', category: 'Arbeit', textTopic: 'Mittagspause', textGenre: 'Nachricht' },
  { situation: 'Einladung zum Kinoabend', category: 'Freizeit', textTopic: 'Kino', textGenre: 'Einladung' },
  { situation: 'E-Mail an den Bibliothekar', category: 'Bildung', textTopic: 'Bücher verlängern', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Kollegin wegen Kuchen', category: 'Arbeit', textTopic: 'Geburtstagskuchen', textGenre: 'Nachricht' },
  { situation: 'E-Mail an die Schule wegen Elternabend', category: 'Familie', textTopic: 'Elternabend', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Mutter wegen Einkauf', category: 'Familie', textTopic: 'Einkaufszettel', textGenre: 'Nachricht' },
  { situation: 'E-Mail an den Chef wegen Urlaub', category: 'Arbeit', textTopic: 'Urlaubsantrag', textGenre: 'E-Mail' },
  { situation: 'Einladung zur Weihnachtsfeier', category: 'Feste', textTopic: 'Weihnachten', textGenre: 'Einladung' },
  { situation: 'Glückwunschkarte zur Hochzeit', category: 'Feste', textTopic: 'Hochzeit', textGenre: 'Karte' },
  { situation: 'E-Mail an den Hausarzt wegen Termin', category: 'Gesundheit', textTopic: 'Arzttermin', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Freund wegen Fahrrad', category: 'Privat', textTopic: 'Fahrrad ausleihen', textGenre: 'Nachricht' },
  { situation: 'E-Mail an die Fahrschule', category: 'Bildung', textTopic: 'Fahrstunde buchen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Freundin wegen Ausflug', category: 'Freizeit', textTopic: 'Ausflug planen', textGenre: 'Nachricht' },
  { situation: 'E-Mail an das Hotel wegen Zimmer', category: 'Reise', textTopic: 'Zimmer buchen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Nachbarn wegen Schlüssel', category: 'Wohnen', textTopic: 'Schlüssel', textGenre: 'Nachricht' },
  { situation: 'E-Mail an die Putzfrau', category: 'Alltag', textTopic: 'Termin ändern', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Schwester wegen Geschenk', category: 'Familie', textTopic: 'Geschenkidee', textGenre: 'Nachricht' },
  { situation: 'E-Mail an den Vermieter wegen Besichtigung', category: 'Wohnen', textTopic: 'Wohnungsbesichtigung', textGenre: 'E-Mail' },
  { situation: 'Kurze Nachricht an den Verkäufer', category: 'Alltag', textTopic: 'Ware reservieren', textGenre: 'Nachricht' },
  { situation: 'Einladung zum Kaffeetrinken', category: 'Privat', textTopic: 'Kaffee zu Hause', textGenre: 'Einladung' },
  { situation: 'E-Mail an den Sprachtandempartner', category: 'Sprache', textTopic: 'Treffen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Kita wegen Abholzeit', category: 'Familie', textTopic: 'Abholzeit', textGenre: 'Nachricht' },
  { situation: 'E-Mail an die Kursleiterin', category: 'Bildung', textTopic: 'Fehlen entschuldigen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Trainer wegen Ergebnis', category: 'Sport', textTopic: 'Spielergebnis', textGenre: 'Nachricht' },
  { situation: 'Glückwunschkarte zur Taufe', category: 'Feste', textTopic: 'Taufe', textGenre: 'Karte' },
  { situation: 'E-Mail an die Sportschule', category: 'Sport', textTopic: 'Kurs anmelden', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Freund wegen Autofahrt', category: 'Privat', textTopic: 'Mitfahrt', textGenre: 'Nachricht' },
  { situation: 'Gruß aus dem Krankenhaus', category: 'Gesundheit', textTopic: 'Genesungswünsche', textGenre: 'Karte' },
  { situation: 'E-Mail an die Tante wegen Familientreffen', category: 'Familie', textTopic: 'Familientreffen', textGenre: 'E-Mail' },
  { situation: 'Nachricht an die Nachbarin wegen Blumen', category: 'Wohnen', textTopic: 'Blumen gießen', textGenre: 'Nachricht' },
  { situation: 'E-Mail an den Chef wegen Krankheit', category: 'Arbeit', textTopic: 'Krankmeldung', textGenre: 'E-Mail' },
  { situation: 'Kurze Nachricht an die Lehrerin', category: 'Bildung', textTopic: 'Buch vergessen', textGenre: 'Nachricht' },
  { situation: 'E-Mail an die Eltern wegen Besuch', category: 'Familie', textTopic: 'Besuchsankündigung', textGenre: 'E-Mail' },
  { situation: 'Einladung zum Picknick', category: 'Freizeit', textTopic: 'Picknick', textGenre: 'Einladung' },
  { situation: 'E-Mail an den Arzt wegen Rezept', category: 'Gesundheit', textTopic: 'Rezept', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Kollegen wegen Meeting', category: 'Arbeit', textTopic: 'Meeting verschieben', textGenre: 'Nachricht' },
  { situation: 'E-Mail an die Freundin wegen Fotos', category: 'Privat', textTopic: 'Fotos schicken', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Freund wegen Buch', category: 'Privat', textTopic: 'Buch zurückgeben', textGenre: 'Nachricht' },
  { situation: 'E-Mail an die Schwimmlehrerin', category: 'Sport', textTopic: 'Fehlen beim Kurs', textGenre: 'E-Mail' },
  { situation: 'Glückwunschkarte zum Namenstag', category: 'Feste', textTopic: 'Namenstag', textGenre: 'Karte' },
  { situation: 'Nachricht an die Freundin wegen Feier', category: 'Privat', textTopic: 'Absage einer Feier', textGenre: 'Nachricht' },
  { situation: 'E-Mail an die Großeltern', category: 'Familie', textTopic: 'Besuch verabreden', textGenre: 'E-Mail' },
  { situation: 'Nachricht an den Briefträger', category: 'Alltag', textTopic: 'Paketnachsendung', textGenre: 'Nachricht' },
  { situation: 'E-Mail an den Veranstalter', category: 'Freizeit', textTopic: 'Ticket ändern', textGenre: 'E-Mail' },
  { situation: 'Kurze Einladung zum Frühstück', category: 'Privat', textTopic: 'Frühstück zu zweit', textGenre: 'Einladung' },
]
