// Расширенный набор тем для модуля Schreiben (A1/A2/B1).
// Каждая тема — {situation, recipient, taskHints[]}.
// Источник правды для генерации: таблица generation_topics.
// Этот файл импортируется сидером scripts/seed-generation-topics.ts.

import type { TopicData } from '@/lib/topic-sampler'

// ─── A1 — простые бытовые письма (30 слов) ─────────────────────
export const SCHREIBEN_A1: TopicData[] = [
  { situation: 'Geburtstagseinladung an eine Freundin', recipient: 'Freundin', taskHints: ['Datum nennen', 'Ort beschreiben', 'Essen erwähnen'] },
  { situation: 'Krankmeldung beim Deutschlehrer', recipient: 'Deutschlehrer', taskHints: ['Krankheit nennen', 'Dauer angeben', 'Hausaufgaben erfragen'] },
  { situation: 'Mittagspause mit dem Kollegen vereinbaren', recipient: 'Kollege', taskHints: ['Zeit vorschlagen', 'Ort nennen', 'Grund erklären'] },
  { situation: 'Kino-Einladung an einen Freund', recipient: 'Freund', taskHints: ['Film nennen', 'Uhrzeit', 'Treffpunkt'] },
  { situation: 'Nachricht an die Nachbarin wegen Paket', recipient: 'Nachbarin', taskHints: ['Paket erwähnen', 'bitten abzuholen', 'danken'] },
  { situation: 'Absage einer Party', recipient: 'Freundin', taskHints: ['entschuldigen', 'Grund kurz nennen', 'nächstes Treffen vorschlagen'] },
  { situation: 'Freunde zum Grillen einladen', recipient: 'Freunde', taskHints: ['Datum und Uhrzeit', 'was mitbringen', 'Adresse'] },
  { situation: 'Nachricht an die Sportlehrerin', recipient: 'Sportlehrerin', taskHints: ['nicht kommen können', 'Grund nennen', 'fragen was nachholen'] },
  { situation: 'E-Mail an die Freundin wegen Wochenende', recipient: 'Freundin', taskHints: ['Treffen vorschlagen', 'Aktivität nennen', 'Antwort erbitten'] },
  { situation: 'Einladung zum Kaffee nach Hause', recipient: 'Nachbarin', taskHints: ['Tag nennen', 'Uhrzeit', 'Kuchen ankündigen'] },
  { situation: 'Danke für ein Geschenk', recipient: 'Oma', taskHints: ['danken', 'Geschenk nennen', 'Besuch ankündigen'] },
  { situation: 'Nachricht an einen Freund über neue Telefonnummer', recipient: 'Freund', taskHints: ['neue Nummer nennen', 'Grund', 'bitten zu speichern'] },
  { situation: 'Verabredung im Café', recipient: 'Bekannte', taskHints: ['Café nennen', 'Uhrzeit', 'was besprechen wollen'] },
  { situation: 'Entschuldigung wegen Verspätung', recipient: 'Kollege', taskHints: ['entschuldigen', 'Grund', 'neuen Zeitpunkt'] },
  { situation: 'Freund zum Spaziergang einladen', recipient: 'Freund', taskHints: ['Park nennen', 'Uhrzeit', 'was mitnehmen'] },
  { situation: 'E-Mail an die Sprachschule wegen Kursbeginn', recipient: 'Sprachschule', taskHints: ['Name nennen', 'nach Termin fragen', 'Material erfragen'] },
  { situation: 'Kurze Nachricht an die Mutter aus der Arbeit', recipient: 'Mutter', taskHints: ['später kommen', 'Grund', 'nicht warten'] },
  { situation: 'Freund zum Fußballspiel einladen', recipient: 'Freund', taskHints: ['Datum', 'Stadion', 'Treffpunkt'] },
  { situation: 'E-Mail an die Lehrerin wegen Unterlagen', recipient: 'Lehrerin', taskHints: ['Unterlagen vermissen', 'bitten zu senden', 'danken'] },
  { situation: 'Einladung zu Essen bei Freunden zu Hause', recipient: 'Freund', taskHints: ['Tag und Uhrzeit', 'was kochen', 'Adresse'] },
  { situation: 'Gruß aus dem Urlaub', recipient: 'Freundin', taskHints: ['Ort nennen', 'Wetter', 'Aktivität'] },
  { situation: 'Nachricht an den Hausmeister wegen Heizung', recipient: 'Hausmeister', taskHints: ['Problem nennen', 'um Hilfe bitten', 'Zeit vorschlagen'] },
  { situation: 'Frage an den Kollegen wegen Feier', recipient: 'Kollege', taskHints: ['Feier erwähnen', 'Kleidung fragen', 'Fahrgemeinschaft'] },
  { situation: 'E-Mail an die Bibliothek wegen Ausweis', recipient: 'Bibliothek', taskHints: ['Ausweis verloren', 'um Hilfe bitten', 'Öffnungszeiten fragen'] },
  { situation: 'Nachricht an die Schwester wegen Besuch', recipient: 'Schwester', taskHints: ['Ankunft nennen', 'Abholung vom Bahnhof', 'Aufenthalt'] },
  { situation: 'Kollegin zum Geburtstag gratulieren', recipient: 'Kollegin', taskHints: ['gratulieren', 'Wunsch aussprechen', 'Treffen vorschlagen'] },
  { situation: 'E-Mail an Freunde wegen Umzug', recipient: 'Freunde', taskHints: ['neue Adresse', 'Einzugsparty', 'Hilfe erbitten'] },
  { situation: 'Einladung zum Spieleabend', recipient: 'Freunde', taskHints: ['Datum', 'Spiele mitbringen', 'Snacks'] },
  { situation: 'Nachricht an den Trainer wegen Training', recipient: 'Trainer', taskHints: ['abwesend sein', 'Grund', 'nächstes Training'] },
  { situation: 'E-Mail an die Tante wegen Besuch', recipient: 'Tante', taskHints: ['Datum', 'wie lange bleiben', 'was mitbringen'] },
  { situation: 'Freundin zum Schwimmbad einladen', recipient: 'Freundin', taskHints: ['Schwimmbad nennen', 'Uhrzeit', 'Eintrittspreis'] },
  { situation: 'Kurze Nachricht an den Vater', recipient: 'Vater', taskHints: ['Ankunft nennen', 'Abholung', 'Zuggleis'] },
  { situation: 'Einladung zum Kaffeetrinken ins Büro', recipient: 'Kollegen', taskHints: ['Anlass', 'Uhrzeit', 'Raum'] },
  { situation: 'Danke an den Nachbarn für Hilfe', recipient: 'Nachbar', taskHints: ['konkret danken', 'Hilfe erwähnen', 'Gegenleistung anbieten'] },
  { situation: 'Nachricht an die Bekannte wegen Kino-Karte', recipient: 'Bekannte', taskHints: ['Karte anbieten', 'Preis nennen', 'Abholung'] },
  { situation: 'Einladung zum Eis essen', recipient: 'Freundin', taskHints: ['Eisdiele', 'Uhrzeit', 'Sorten'] },
  { situation: 'Frage an den Kollegen wegen Dienstplan', recipient: 'Kollege', taskHints: ['Dienstplan unklar', 'nach Schicht fragen', 'danken'] },
  { situation: 'Einladung zum Picknick im Park', recipient: 'Freunde', taskHints: ['Datum', 'Essen aufteilen', 'Treffpunkt'] },
  { situation: 'E-Mail an die Freundin aus dem Heimatland', recipient: 'Freundin', taskHints: ['vom Alltag in Deutschland', 'Wetter', 'Frage stellen'] },
  { situation: 'Nachricht wegen vergessenem Schirm', recipient: 'Kollege', taskHints: ['Schirm vergessen', 'um Aufbewahrung bitten', 'Abholung'] },
  { situation: 'Einladung zum Brunch am Sonntag', recipient: 'Freunde', taskHints: ['Uhrzeit', 'Essen koordinieren', 'Adresse'] },
  { situation: 'E-Mail an den Arzt wegen Termin', recipient: 'Arztpraxis', taskHints: ['Termin erbitten', 'bevorzugter Tag', 'Telefonnummer'] },
  { situation: 'Kurze Nachricht an die Chefin wegen Urlaub', recipient: 'Chefin', taskHints: ['Urlaubswunsch', 'Zeitraum', 'Rückmeldung'] },
  { situation: 'Einladung zum Weihnachtsmarkt', recipient: 'Freundin', taskHints: ['Stadt nennen', 'Uhrzeit', 'Glühwein'] },
  { situation: 'Nachricht an den Freund wegen Zug', recipient: 'Freund', taskHints: ['Zug genommen', 'Ankunftszeit', 'Abholung'] },
  { situation: 'Dank an die Lehrerin zum Kursende', recipient: 'Lehrerin', taskHints: ['danken', 'Lob aussprechen', 'verabschieden'] },
  { situation: 'Einladung zum Kochen zu Hause', recipient: 'Freundin', taskHints: ['Gericht', 'Uhrzeit', 'Getränke mitbringen'] },
  { situation: 'E-Mail an die Schule wegen Sommerferien', recipient: 'Lehrerin', taskHints: ['Kind abmelden', 'Zeitraum', 'Unterlagen erfragen'] },
  { situation: 'Nachricht an den Freund wegen Konzert', recipient: 'Freund', taskHints: ['Konzert vorschlagen', 'Band nennen', 'Ticketpreis'] },
  { situation: 'Einladung zum Sport am Samstag', recipient: 'Freund', taskHints: ['Sportart', 'Uhrzeit', 'Ausrüstung'] },
  { situation: 'Nachricht an die Freundin wegen Film-Abend', recipient: 'Freundin', taskHints: ['Film auswählen', 'Popcorn', 'Uhrzeit'] },
  { situation: 'Kurze Mail an den Kursleiter wegen Pause', recipient: 'Kursleiter', taskHints: ['Pause machen', 'Rückkehr nennen', 'Material erfragen'] },
  { situation: 'Einladung zum Spaziergang durch die Altstadt', recipient: 'Freundin', taskHints: ['Stadt erkunden', 'Treffpunkt', 'Café danach'] },
  { situation: 'Nachricht an den Hausarzt wegen Rezept', recipient: 'Arztpraxis', taskHints: ['Rezept brauchen', 'Medikament', 'Abholung'] },
  { situation: 'Einladung zu Kaffee und Kuchen', recipient: 'Oma und Opa', taskHints: ['Sonntagnachmittag', 'Adresse', 'Kuchen ankündigen'] },
  { situation: 'Kurze Mail an Freundin wegen Hochzeit', recipient: 'Freundin', taskHints: ['Hochzeit gratulieren', 'Geschenk besprechen', 'Fahrgemeinschaft'] },
  { situation: 'Einladung zum Joggen im Park', recipient: 'Freund', taskHints: ['Park', 'Uhrzeit', 'Dauer'] },
  { situation: 'Nachricht an den Freund wegen Fahrrad leihen', recipient: 'Freund', taskHints: ['Fahrrad ausleihen', 'Grund', 'Abholung'] },
  { situation: 'E-Mail an Kollegen wegen Geschenk für Chef', recipient: 'Kollegen', taskHints: ['Geschenkidee', 'Geld sammeln', 'Abgabetermin'] },
  { situation: 'Einladung zu Tee und Keksen', recipient: 'Nachbarin', taskHints: ['Tag nennen', 'Uhrzeit', 'Anlass'] },
]

// ─── A2 — etwas komplexer: Arzttermine, VHS, Empfehlungen (50 слов) ─
export const SCHREIBEN_A2: TopicData[] = [
  { situation: 'Neue Wohnung in Deutschland beschreiben', recipient: 'Eltern im Heimatland', taskHints: ['Wohnung beschreiben', 'Nachbarschaft', 'Besuch einladen'] },
  { situation: 'Deutschkurs an der Volkshochschule empfehlen', recipient: 'Freund aus dem Heimatland', taskHints: ['Kurs beschreiben', 'empfehlen warum', 'Preis nennen'] },
  { situation: 'Glückwunsch zur Hochzeit eines Kollegen', recipient: 'Kollege', taskHints: ['gratulieren', 'Geschenkidee fragen', 'Feier'] },
  { situation: 'Gefundenes Fahrrad zurückgeben', recipient: 'Nachbar', taskHints: ['Fundort nennen', 'Abholzeit vereinbaren', 'Zustand beschreiben'] },
  { situation: 'Termin beim Zahnarzt absagen', recipient: 'Zahnarztpraxis', taskHints: ['absagen', 'Grund nennen', 'neuen Termin erbitten'] },
  { situation: 'Nach einem Kochkurs fragen', recipient: 'Volkshochschule', taskHints: ['Kurs finden', 'Preis erfragen', 'Anmeldung'] },
  { situation: 'Freundin um Rat beim Arztbesuch bitten', recipient: 'Freundin', taskHints: ['Problem beschreiben', 'um Empfehlung bitten', 'Erfahrung erfragen'] },
  { situation: 'Beschwerde im Fitnessstudio wegen Duschen', recipient: 'Fitnessstudio-Leitung', taskHints: ['Problem beschreiben', 'Lösung wünschen', 'Antwort erwarten'] },
  { situation: 'Einladung zur Einweihungsparty der neuen Wohnung', recipient: 'Freunde', taskHints: ['Adresse', 'Datum', 'was mitbringen'] },
  { situation: 'Termin mit dem Hausmeister vereinbaren', recipient: 'Hausmeister', taskHints: ['Defekt nennen', 'Zeitvorschlag', 'Kontaktinformation'] },
  { situation: 'Empfehlung eines Restaurants geben', recipient: 'Freundin', taskHints: ['Restaurant nennen', 'Küche beschreiben', 'Reservierung empfehlen'] },
  { situation: 'Teilnahme am Sprachcafé absagen', recipient: 'Sprachcafé-Leiterin', taskHints: ['entschuldigen', 'Grund angeben', 'nächstes Mal zusagen'] },
  { situation: 'Freund zum gemeinsamen Kochen einladen', recipient: 'Freund', taskHints: ['Rezept vorschlagen', 'Zutaten teilen', 'Zeit vereinbaren'] },
  { situation: 'Erfahrung mit einem Online-Shop teilen', recipient: 'Freundin', taskHints: ['Shop nennen', 'Produkt beschreiben', 'Lieferzeit'] },
  { situation: 'Um Tipps für einen Städtetrip nach Berlin bitten', recipient: 'Freundin aus Berlin', taskHints: ['Sehenswürdigkeiten', 'Restaurants', 'Fortbewegung'] },
  { situation: 'Nachbarin um einen Gefallen bitten', recipient: 'Nachbarin', taskHints: ['Blumen gießen', 'Dauer nennen', 'Schlüssel übergeben'] },
  { situation: 'Erinnerung an Arzttermin für Freundin', recipient: 'Freundin', taskHints: ['Termin erinnern', 'Uhrzeit', 'Fahrgemeinschaft'] },
  { situation: 'Gratulation zur bestandenen Prüfung', recipient: 'Kommilitonin', taskHints: ['gratulieren', 'Feier vorschlagen', 'Ergebnis erfragen'] },
  { situation: 'Beschwerde beim Vermieter wegen Lärm im Haus', recipient: 'Vermieter', taskHints: ['Problem schildern', 'Uhrzeiten nennen', 'Lösung erbitten'] },
  { situation: 'Neuen Kollegen zum Mittagessen einladen', recipient: 'neuer Kollege', taskHints: ['willkommen heißen', 'Kantine vorschlagen', 'Uhrzeit'] },
  { situation: 'Hilfe bei Umzug erbitten', recipient: 'Freund', taskHints: ['Datum nennen', 'was zu tragen ist', 'Essen danach'] },
  { situation: 'Einladung zum Kulturabend der Volkshochschule', recipient: 'Freundin', taskHints: ['Programm', 'Eintrittskarten', 'Treffpunkt'] },
  { situation: 'Anmeldung zum Yoga-Kurs erfragen', recipient: 'Volkshochschule', taskHints: ['Kursbeginn', 'Voraussetzungen', 'Gebühr'] },
  { situation: 'Kollegin um Vertretung bitten', recipient: 'Kollegin', taskHints: ['Grund nennen', 'Zeitraum', 'Aufgaben übergeben'] },
  { situation: 'Freund um Buchempfehlung bitten', recipient: 'Freund', taskHints: ['Genre angeben', 'Sprachlevel', 'Autor offen'] },
  { situation: 'Nachbarn um Tipp für Kinderarzt fragen', recipient: 'Nachbarn', taskHints: ['Kinderarzt suchen', 'Empfehlung', 'Sprechzeiten'] },
  { situation: 'Verabredung zum Museumsbesuch', recipient: 'Freundin', taskHints: ['Museum nennen', 'Eintrittspreis', 'Treffpunkt'] },
  { situation: 'Dank an die Nachbarin für Babysitten', recipient: 'Nachbarin', taskHints: ['danken', 'Gegenleistung anbieten', 'Kaffee einladen'] },
  { situation: 'Beschwerde beim Paketdienst über Zustellung', recipient: 'Paketdienst Kundenservice', taskHints: ['Paket nicht erhalten', 'Nachverfolgungsnummer', 'Lösung'] },
  { situation: 'Empfehlung eines Friseurs geben', recipient: 'Freundin', taskHints: ['Friseur nennen', 'Preis', 'Terminvereinbarung'] },
  { situation: 'Einladung zum Stadtfest', recipient: 'Freunde', taskHints: ['Programm', 'Treffpunkt', 'Essen und Getränke'] },
  { situation: 'Absage der Einladung zur Party', recipient: 'Freundin', taskHints: ['entschuldigen', 'Krankheit', 'Geschenk später'] },
  { situation: 'Freund um Hilfe bei Steuererklärung bitten', recipient: 'Freund', taskHints: ['Unterstützung erbitten', 'Termin', 'Gegenleistung'] },
  { situation: 'E-Mail an die Bibliothek wegen verlängerter Leihfrist', recipient: 'Stadtbibliothek', taskHints: ['Buch nennen', 'Verlängerung erbitten', 'Rückgabedatum'] },
  { situation: 'Anmeldung für einen Schwimmkurs', recipient: 'Schwimmbad', taskHints: ['Anfänger', 'Kurszeit', 'Kosten'] },
  { situation: 'Freundin zur Ausstellung einladen', recipient: 'Freundin', taskHints: ['Ausstellung beschreiben', 'Ort', 'Treffpunkt'] },
  { situation: 'Tausch des Abos im Fitnessstudio', recipient: 'Fitnessstudio', taskHints: ['Abowechsel', 'Begründung', 'Termin'] },
  { situation: 'Empfehlung für einen Kindergarten', recipient: 'Freundin', taskHints: ['Kindergarten nennen', 'Plätze', 'Anmeldung'] },
  { situation: 'Bestätigung einer Reservierung im Restaurant', recipient: 'Restaurant', taskHints: ['Datum bestätigen', 'Personenzahl', 'Sonderwünsche'] },
  { situation: 'Einladung zum Flohmarkt', recipient: 'Freundin', taskHints: ['Markt nennen', 'Treffpunkt', 'was suchen'] },
  { situation: 'Bitte um Praktikumsinformationen', recipient: 'Personalabteilung', taskHints: ['Interesse zeigen', 'Zeitraum', 'Dokumente erfragen'] },
  { situation: 'Freundin um Mitnahme zum Flughafen bitten', recipient: 'Freundin', taskHints: ['Flug nennen', 'Uhrzeit', 'Tank-Anteil anbieten'] },
  { situation: 'Empfehlung eines Babysitters weitergeben', recipient: 'Kollegin', taskHints: ['Babysitter nennen', 'Erfahrung', 'Kontakt'] },
  { situation: 'Nachricht an die Hausverwaltung wegen Waschküche', recipient: 'Hausverwaltung', taskHints: ['Maschine defekt', 'Problem beschreiben', 'Reparatur erbitten'] },
  { situation: 'Einladung zum Wandertag', recipient: 'Freunde', taskHints: ['Route', 'Ausrüstung', 'Treffpunkt'] },
  { situation: 'Bitte um Buchkauf an einen Freund', recipient: 'Freund', taskHints: ['Buch nennen', 'Geld zurückgeben', 'Abholung'] },
  { situation: 'Termin mit der Hausverwaltung wegen Abnahme', recipient: 'Hausverwaltung', taskHints: ['Wohnungsabnahme', 'Zeitvorschlag', 'Schlüsselübergabe'] },
  { situation: 'Absage eines Vorstellungsgesprächs', recipient: 'Personalabteilung', taskHints: ['entschuldigen', 'Grund', 'neuen Termin erfragen'] },
  { situation: 'Bitte um Sprachtandempartner', recipient: 'Sprachschule', taskHints: ['Sprache angeben', 'Niveau', 'Zeitrahmen'] },
  { situation: 'Empfehlung eines Tierarztes', recipient: 'Nachbar', taskHints: ['Tierarzt nennen', 'Adresse', 'Erfahrung'] },
  { situation: 'Frage an die Schule wegen Elternabend', recipient: 'Klassenlehrerin', taskHints: ['Datum bestätigen', 'Themen', 'Entschuldigung wenn nicht'] },
  { situation: 'Einladung zum Freibadbesuch', recipient: 'Freundin', taskHints: ['Freibad nennen', 'Eintrittspreis', 'Picknick'] },
  { situation: 'Nachricht an den Sprachlehrer wegen Hausaufgabe', recipient: 'Sprachlehrer', taskHints: ['Aufgabe unklar', 'Beispiel erbitten', 'Abgabe'] },
  { situation: 'Bitte um Mitfahrgelegenheit nach München', recipient: 'Kollege', taskHints: ['Datum', 'Tank-Anteil', 'Gepäck'] },
  { situation: 'Absage des Arzttermins wegen Krankheit', recipient: 'Hausarztpraxis', taskHints: ['absagen', 'Grund', 'neuen Termin'] },
  { situation: 'Kollegen zu einem Seminar einladen', recipient: 'Kollegen', taskHints: ['Thema', 'Datum', 'Anmeldung'] },
  { situation: 'Bitte um Auskunft zur VHS-Prüfung', recipient: 'Volkshochschule', taskHints: ['Prüfungstermin', 'Gebühr', 'Unterlagen'] },
  { situation: 'Empfehlung eines Reiseziels', recipient: 'Freund', taskHints: ['Ziel nennen', 'Reisezeit', 'Budget'] },
  { situation: 'Termin mit dem Optiker verschieben', recipient: 'Optiker', taskHints: ['verschieben', 'Grund', 'neuen Termin'] },
  { situation: 'Einladung zum Sprachcafé im Viertel', recipient: 'Freundin', taskHints: ['Ort', 'Uhrzeit', 'Atmosphäre beschreiben'] },
]

// ─── B1 — полноценные письма: Krankenkasse, аргументы (80 слов) ─
export const SCHREIBEN_B1: TopicData[] = [
  { situation: 'Reklamation — Online-Bestellung kam kaputt an', recipient: 'Kundenservice eines Online-Shops', taskHints: ['Problem schildern', 'Lösung fordern', 'Frist setzen'] },
  { situation: 'Nachbarschaftskonflikt wegen regelmäßigem Lärm', recipient: 'Nachbar', taskHints: ['Problem höflich ansprechen', 'Kompromiss vorschlagen', 'Konsequenzen andeuten'] },
  { situation: 'Absage der Bewerbung für ein Praktikum', recipient: 'Personalabteilung', taskHints: ['danken', 'Grund der Absage', 'offen für Zukunft bleiben'] },
  { situation: 'Kündigung des Vertrags beim Fitnessstudio', recipient: 'Fitnessstudio-Verwaltung', taskHints: ['zum Monatsende kündigen', 'schriftliche Bestätigung erbitten', 'Kündigungsfrist beachten'] },
  { situation: 'Beschwerde bei der Krankenkasse wegen falscher Rechnung', recipient: 'Krankenkasse', taskHints: ['Fehler in der Rechnung', 'Nachweise beilegen', 'Korrektur fordern'] },
  { situation: 'Widerspruch gegen den Mietvertrag-Nachtrag zu Nebenkosten', recipient: 'Vermieter', taskHints: ['Widerspruch begründen', 'Unterlagen erwähnen', 'Frist für Antwort'] },
  { situation: 'Argumentative Antwort auf Forumsbeitrag über Elterngeld', recipient: 'Online-Forum', taskHints: ['eigene Meinung', 'Erfahrung einbringen', 'Gegenargumente'] },
  { situation: 'Bewerbung um eine Ausbildungsstelle in der Krankenpflege', recipient: 'Pflegeschule', taskHints: ['Motivation', 'Vorerfahrung', 'Verfügbarkeit'] },
  { situation: 'Beschwerdebrief an eine Fluggesellschaft wegen Flugverspätung', recipient: 'Fluggesellschaft', taskHints: ['Zeitverlust', 'Entschädigung fordern', 'Buchungsnummer angeben'] },
  { situation: 'Antrag auf Sonderurlaub beim Arbeitgeber', recipient: 'Personalabteilung', taskHints: ['Grund', 'Zeitraum', 'Vertretung regeln'] },
  { situation: 'E-Mail an den Rundfunkbeitragsservice wegen Befreiung', recipient: 'Rundfunkbeitragsservice', taskHints: ['Befreiung beantragen', 'Nachweise', 'Frist'] },
  { situation: 'Beschwerde beim Bürgeramt wegen langer Wartezeit', recipient: 'Bürgeramt-Leitung', taskHints: ['Problem schildern', 'Verbesserung vorschlagen', 'Reaktion erbitten'] },
  { situation: 'Bewerbung um ein Stipendium', recipient: 'Stipendiumsstiftung', taskHints: ['Motivation', 'Ziel des Studiums', 'finanzielle Lage'] },
  { situation: 'Kündigung des Handyvertrags', recipient: 'Mobilfunkanbieter', taskHints: ['Vertragsnummer', 'Wirksamwerden', 'Rufnummernportierung'] },
  { situation: 'Reklamation beim Möbelhaus wegen falscher Lieferung', recipient: 'Möbelhaus Kundenservice', taskHints: ['Bestellnummer', 'Falschlieferung beschreiben', 'Abholung fordern'] },
  { situation: 'Antrag auf Ratenzahlung bei einer Rechnung', recipient: 'Rechnungsstelle', taskHints: ['finanzielle Situation', 'Vorschlag der Raten', 'Dank ankündigen'] },
  { situation: 'Einspruch gegen einen Bußgeldbescheid', recipient: 'Bußgeldstelle', taskHints: ['Aktenzeichen', 'Argumente darlegen', 'Nachweise beilegen'] },
  { situation: 'Beschwerde bei der Stadtverwaltung über ein Schlagloch', recipient: 'Stadtverwaltung', taskHints: ['Ort beschreiben', 'Gefahr darstellen', 'Reparatur fordern'] },
  { situation: 'Argumentative Antwort auf Forumsfrage: digitale Schulen', recipient: 'Online-Forum', taskHints: ['Standpunkt', 'Vor- und Nachteile', 'Fazit'] },
  { situation: 'Bitte um Urlaubsverlängerung in einer E-Mail an Chefin', recipient: 'Chefin', taskHints: ['Grund', 'neuen Zeitraum', 'Vertretung zusagen'] },
  { situation: 'Beschwerde bei der Hausverwaltung über kaputten Aufzug', recipient: 'Hausverwaltung', taskHints: ['Ausfall dokumentieren', 'Gefahr für ältere Mieter', 'Reparatur-Frist'] },
  { situation: 'Kündigung des Zeitungsabonnements', recipient: 'Zeitungsverlag', taskHints: ['Abonummer', 'Kündigungsdatum', 'Bestätigung erbitten'] },
  { situation: 'Bewerbung als Ehrenamtliche im Tierheim', recipient: 'Tierheim-Leitung', taskHints: ['Motivation', 'Verfügbarkeit', 'Erfahrung mit Tieren'] },
  { situation: 'Widerspruch gegen die Ablehnung eines Visums', recipient: 'Ausländerbehörde', taskHints: ['Ablehnungsgrund adressieren', 'Nachweise', 'Rücksprache erbitten'] },
  { situation: 'Formelles Anschreiben zur Wohnungsbesichtigung', recipient: 'Vermieter', taskHints: ['Interesse bekunden', 'Selbstvorstellung', 'Termin erbitten'] },
  { situation: 'Forumsbeitrag zu Rundfunkbeitrag — Meinung begründen', recipient: 'Online-Forum', taskHints: ['pro- oder contra-Argument', 'eigene Erfahrung', 'Fazit ziehen'] },
  { situation: 'Beschwerde bei einem Reiseveranstalter wegen Mängel im Hotel', recipient: 'Reiseveranstalter', taskHints: ['Reisenummer', 'Mängel auflisten', 'Rückerstattung fordern'] },
  { situation: 'Bewerbung für ein duales Studium', recipient: 'Personalabteilung eines Unternehmens', taskHints: ['Studienrichtung', 'Motivation', 'Unternehmensbezug'] },
  { situation: 'Argumentatives Schreiben zur Einführung einer Tempo-30-Zone', recipient: 'Stadtrat', taskHints: ['Sicherheitsargumente', 'Beispiele', 'Vorschlag konkretisieren'] },
  { situation: 'E-Mail an die Krankenkasse wegen Erstattung einer Brille', recipient: 'Krankenkasse', taskHints: ['Antrag begründen', 'Belege beifügen', 'Bearbeitungsfrist'] },
  { situation: 'Widerruf eines Online-Kaufs innerhalb der 14-Tage-Frist', recipient: 'Online-Shop', taskHints: ['Bestellnummer', 'Widerrufsrecht geltend machen', 'Rückzahlung erwarten'] },
  { situation: 'Bewerbung als Sprachassistenz an einer Grundschule', recipient: 'Schulleitung', taskHints: ['Sprachkenntnisse', 'Motivation', 'Referenzen'] },
  { situation: 'Beschwerde über laute Bauarbeiten nachts', recipient: 'Ordnungsamt', taskHints: ['Dauer angeben', 'Gesetzesverweis', 'Handlungsaufforderung'] },
  { situation: 'Antrag auf Kindergeld nach dem Umzug', recipient: 'Familienkasse', taskHints: ['neue Adresse', 'Nachweise', 'Auszahlungstermin'] },
  { situation: 'Kündigung eines Zeitschriftenabos wegen Umzug ins Ausland', recipient: 'Verlag', taskHints: ['Grund', 'Kündigungstermin', 'Rückerstattung offener Zahlungen'] },
  { situation: 'Argumentative Antwort zum Thema Homeoffice in einem Blog', recipient: 'Blog-Community', taskHints: ['Vorteile', 'Nachteile', 'eigene Erfahrung'] },
  { situation: 'Bewerbung um einen Platz im Deutsch-Integrationskurs', recipient: 'Volkshochschule', taskHints: ['aktuelles Niveau', 'Ziel', 'Kursform bevorzugen'] },
  { situation: 'Reklamation wegen verspäteter Paketlieferung zu Weihnachten', recipient: 'Online-Shop', taskHints: ['Bestellnummer', 'Schaden schildern', 'Entschädigung fordern'] },
  { situation: 'Widerspruch gegen Nebenkostenabrechnung', recipient: 'Vermieter', taskHints: ['konkrete Positionen anzweifeln', 'Belege einsehen wollen', 'Frist setzen'] },
  { situation: 'Bewerbung für einen Freiwilligendienst im sozialen Bereich', recipient: 'Trägerorganisation', taskHints: ['Motivation', 'Einsatzbereich', 'Dauer'] },
  { situation: 'Antrag auf Elternzeit', recipient: 'Personalabteilung', taskHints: ['Zeitraum', 'Antrittszeitpunkt', 'Vertretung'] },
  { situation: 'E-Mail an einen Freund mit Argumenten gegen Social Media Detox', recipient: 'Freund', taskHints: ['eigene Position', 'Gegenargumente adressieren', 'Vorschlag'] },
  { situation: 'Beschwerde bei der Apotheke wegen falsch ausgegebenem Medikament', recipient: 'Apothekenleitung', taskHints: ['Vorfall beschreiben', 'Folgen darstellen', 'Nachbesserung fordern'] },
  { situation: 'Bewerbung als Kursbegleitung an der Volkshochschule', recipient: 'VHS-Verwaltung', taskHints: ['Qualifikation', 'Zeitverfügbarkeit', 'Honorarvorstellung'] },
  { situation: 'Antrag auf Wohngeld nach Jobverlust', recipient: 'Wohngeldbehörde', taskHints: ['Situation schildern', 'Einkommensnachweis', 'benötigter Betrag'] },
  { situation: 'Widerspruch gegen die Kündigung eines Kontos', recipient: 'Bank', taskHints: ['Kontonummer', 'Begründung widerlegen', 'Gespräch erbitten'] },
  { situation: 'Reklamation beim Fernbusanbieter wegen Gepäckverlust', recipient: 'Fernbus-Kundenservice', taskHints: ['Buchungsnummer', 'Inhalt beschreiben', 'Entschädigung'] },
  { situation: 'Bewerbung für ein Austauschsemester im Ausland', recipient: 'International Office der Universität', taskHints: ['Motivation', 'Zielstadt', 'Sprachkenntnisse'] },
  { situation: 'Beschwerdebrief an den Zugbegleiter wegen Zugausfall', recipient: 'DB-Kundenservice', taskHints: ['Zugnummer', 'Folgen des Ausfalls', 'Entschädigung'] },
  { situation: 'Argumentative E-Mail an Freundin über vegane Ernährung', recipient: 'Freundin', taskHints: ['eigene Position', 'gesundheitliche Argumente', 'offenes Ende'] },
  { situation: 'E-Mail an den Stromversorger wegen Tarifwechsel', recipient: 'Stromversorger', taskHints: ['neuer Tarif', 'Starttermin', 'Bestätigung erbitten'] },
  { situation: 'Beschwerde beim Schwimmbad über unzureichende Hygiene', recipient: 'Schwimmbadleitung', taskHints: ['Vorfall beschreiben', 'Besorgnis äußern', 'Maßnahmen fordern'] },
  { situation: 'Kündigung der Mitgliedschaft im Sportverein', recipient: 'Vereinsvorstand', taskHints: ['Mitgliedsnummer', 'Austrittsdatum', 'Beitragsrückzahlung'] },
  { situation: 'Bewerbung um eine Stelle als Werkstudent*in', recipient: 'Unternehmen', taskHints: ['Studienfach', 'verfügbare Stunden', 'Motivation'] },
  { situation: 'Reklamation beim Friseur wegen misslungener Haarfarbe', recipient: 'Friseursalon', taskHints: ['Termin nennen', 'Problem beschreiben', 'Nachbesserung oder Erstattung'] },
  { situation: 'E-Mail an die Hausverwaltung wegen Schimmel in der Wohnung', recipient: 'Hausverwaltung', taskHints: ['Problem dokumentieren', 'Gesundheitsgefahr', 'Fristsetzung'] },
  { situation: 'Argumentative Antwort auf Leserbrief zu Deutschland-Ticket', recipient: 'Zeitungs-Leserbriefredaktion', taskHints: ['Zustimmung oder Kritik', 'Beispiele', 'Forderung formulieren'] },
  { situation: 'Bewerbung als Au-pair in Deutschland', recipient: 'Au-pair-Agentur', taskHints: ['Motivation', 'Sprachniveau', 'Erfahrung mit Kindern'] },
  { situation: 'Beschwerde über einen Zustellservice wegen mehrfacher Falschlieferung', recipient: 'Zustelldienst', taskHints: ['Vorfälle dokumentieren', 'Kundennummer', 'Lösung fordern'] },
  { situation: 'Antrag auf Beurlaubung vom Studium', recipient: 'Studierendensekretariat', taskHints: ['Grund', 'Zeitraum', 'Rückkehrplan'] },
]
