// Расширенный набор тем для модуля Sprechen (A1/A2/B1).
// Формат: Goethe-Sprechen — 3 части, общий контекст для всех трёх задаётся одной темой.
// Поля: {situation, taskType: 'planning'|'presentation'|'reaction', taskHints[], topicDetail?}.
// Для модуля Sprechen sampler подставляет ОДНУ тему для всех трёх задач, промпт генерирует
// 3 подзадачи (planning/presentation/reaction). Поэтому каждая тема фиксирует главный домен.

import type { TopicData } from '@/lib/topic-sampler'

export const SPRECHEN_A1: TopicData[] = [
  { situation: 'Zusammen einkaufen gehen', taskType: 'planning', taskHints: ['Wo?', 'Wann?', 'Was kaufen?', 'Wie hinkommen?'] },
  { situation: 'Meine Familie vorstellen', taskType: 'presentation', taskHints: ['Personen nennen', 'Wohnort', 'Hobbys', 'warum wichtig'] },
  { situation: 'Reaktion auf Familien-Präsentation', taskType: 'reaction', taskHints: ['Frage stellen', 'eigene Erfahrung', 'Kommentar'] },
  { situation: 'Einen Tag im Zoo planen', taskType: 'planning', taskHints: ['Treffpunkt', 'Uhrzeit', 'Verpflegung', 'Transport'] },
  { situation: 'Mein Tagesablauf', taskType: 'presentation', taskHints: ['Morgen', 'Arbeit/Studium', 'Abend', 'Wochenende'] },
  { situation: 'Reaktion auf Tagesablauf-Präsentation', taskType: 'reaction', taskHints: ['Unterschied zum eigenen Alltag', 'Frage'] },
  { situation: 'Geburtstagsgeschenk für einen Freund aussuchen', taskType: 'planning', taskHints: ['Budget', 'Geschäft', 'Geschenkidee', 'Übergabe'] },
  { situation: 'Mein Hobby', taskType: 'presentation', taskHints: ['Hobby nennen', 'wie oft', 'warum', 'mit wem'] },
  { situation: 'Reaktion auf Hobby-Präsentation', taskType: 'reaction', taskHints: ['neugierige Frage', 'eigenes Hobby'] },
  { situation: 'Ein Wochenende in der Stadt planen', taskType: 'planning', taskHints: ['Aktivität', 'Treffpunkt', 'Uhrzeit', 'Essen'] },
  { situation: 'Meine Wohnung', taskType: 'presentation', taskHints: ['Zimmer', 'Lage', 'Nachbarschaft', 'mein Lieblingsraum'] },
  { situation: 'Reaktion auf Wohnungs-Präsentation', taskType: 'reaction', taskHints: ['Frage zur Größe', 'Frage zur Miete'] },
  { situation: 'Ein Frühstück für Freunde planen', taskType: 'planning', taskHints: ['Datum', 'Menü', 'wer bringt was', 'Zeit'] },
  { situation: 'Mein Lieblingsessen', taskType: 'presentation', taskHints: ['Gericht', 'Zutaten', 'wann essen', 'wer kocht'] },
  { situation: 'Reaktion auf Essen-Präsentation', taskType: 'reaction', taskHints: ['Rezept erfragen', 'eigenes Lieblingsessen'] },
  { situation: 'Einen Sprachkurs zusammen besuchen', taskType: 'planning', taskHints: ['Kurs finden', 'Termin', 'Material', 'Anmeldung'] },
  { situation: 'Mein Heimatort', taskType: 'presentation', taskHints: ['Land', 'Stadt', 'Sehenswürdigkeiten', 'Besonderheiten'] },
  { situation: 'Reaktion auf Heimatort-Präsentation', taskType: 'reaction', taskHints: ['kulturelle Frage', 'Vergleich mit Deutschland'] },
  { situation: 'Ein Fest organisieren (Abendessen zu Hause)', taskType: 'planning', taskHints: ['Gäste', 'Zeit', 'Essen', 'Getränke'] },
  { situation: 'Mein Beruf oder Studium', taskType: 'presentation', taskHints: ['Beruf nennen', 'Aufgaben', 'Freude daran', 'Zukunft'] },
  { situation: 'Reaktion auf Beruf-Präsentation', taskType: 'reaction', taskHints: ['Alltagsfrage', 'Lohnfrage höflich'] },
  { situation: 'Ein Sport-Treffen organisieren', taskType: 'planning', taskHints: ['Sportart', 'Ort', 'Uhrzeit', 'Ausrüstung'] },
  { situation: 'Meine Freunde', taskType: 'presentation', taskHints: ['wer sind sie', 'wie kennengelernt', 'Aktivitäten', 'Bedeutung'] },
  { situation: 'Reaktion auf Freunde-Präsentation', taskType: 'reaction', taskHints: ['eigene Freundesgruppe', 'Frage'] },
  { situation: 'Eine Reise an die Nordsee planen', taskType: 'planning', taskHints: ['Datum', 'Verkehrsmittel', 'Unterkunft', 'Budget'] },
  { situation: 'Meine Lieblingsjahreszeit', taskType: 'presentation', taskHints: ['Jahreszeit', 'Wetter', 'Aktivitäten', 'Essen typisch'] },
  { situation: 'Reaktion auf Jahreszeit-Präsentation', taskType: 'reaction', taskHints: ['andere Präferenz erklären', 'Frage stellen'] },
  { situation: 'Eine Geburtstagsparty planen', taskType: 'planning', taskHints: ['Ort', 'Gäste', 'Musik', 'Dekoration'] },
  { situation: 'Meine Lieblingsmusik', taskType: 'presentation', taskHints: ['Stil', 'Künstler', 'wann hören', 'warum mögen'] },
  { situation: 'Reaktion auf Musik-Präsentation', taskType: 'reaction', taskHints: ['eigenen Geschmack', 'Empfehlung erfragen'] },
  { situation: 'Einen Filmabend organisieren', taskType: 'planning', taskHints: ['Film auswählen', 'Essen', 'Uhrzeit', 'Gäste'] },
  { situation: 'Mein Lieblingstier', taskType: 'presentation', taskHints: ['Tier nennen', 'Eigenschaften', 'persönliche Erfahrung', 'warum mögen'] },
  { situation: 'Reaktion auf Lieblingstier-Präsentation', taskType: 'reaction', taskHints: ['eigene Erfahrung', 'Frage zur Haltung'] },
  { situation: 'Einen gemeinsamen Café-Besuch planen', taskType: 'planning', taskHints: ['Café', 'Uhrzeit', 'Anlass', 'Bezahlung'] },
  { situation: 'Meine Lieblingskleidung', taskType: 'presentation', taskHints: ['Stil', 'Farben', 'Anlässe', 'Geschäfte'] },
  { situation: 'Reaktion auf Kleidung-Präsentation', taskType: 'reaction', taskHints: ['Geschmack vergleichen', 'Shopping-Tipp'] },
  { situation: 'Einen Ausflug ins Grüne planen', taskType: 'planning', taskHints: ['Ort', 'Zeit', 'Anreise', 'Verpflegung'] },
  { situation: 'Mein Zimmer', taskType: 'presentation', taskHints: ['Größe', 'Möbel', 'Farben', 'Lieblingsplatz'] },
  { situation: 'Reaktion auf Zimmer-Präsentation', taskType: 'reaction', taskHints: ['Einrichtungsfrage', 'eigenes Zimmer'] },
  { situation: 'Einen Museumsbesuch planen', taskType: 'planning', taskHints: ['Museum', 'Uhrzeit', 'Eintritt', 'Treffpunkt'] },
  { situation: 'Mein Lieblingsbuch oder Lieblingsfilm', taskType: 'presentation', taskHints: ['Titel', 'Handlung', 'Eindruck', 'Empfehlung'] },
  { situation: 'Reaktion auf Buch/Film-Präsentation', taskType: 'reaction', taskHints: ['Ähnliches nennen', 'Nachfrage zur Handlung'] },
  { situation: 'Gemeinsam Deutsch lernen', taskType: 'planning', taskHints: ['Lernort', 'Zeit', 'Material', 'Ziele'] },
  { situation: 'Mein Arbeitsweg', taskType: 'presentation', taskHints: ['Verkehrsmittel', 'Dauer', 'Route', 'Erlebnisse'] },
  { situation: 'Reaktion auf Arbeitsweg-Präsentation', taskType: 'reaction', taskHints: ['Verkehrsfrage', 'eigene Route'] },
  { situation: 'Einen Flohmarkt-Besuch organisieren', taskType: 'planning', taskHints: ['Markt finden', 'Anreise', 'Uhrzeit', 'Budget'] },
  { situation: 'Mein Lieblingsfeiertag', taskType: 'presentation', taskHints: ['Feiertag', 'Traditionen', 'Essen', 'Familie'] },
  { situation: 'Reaktion auf Feiertag-Präsentation', taskType: 'reaction', taskHints: ['andere Tradition', 'Frage'] },
  { situation: 'Den Geburtstag einer Freundin planen', taskType: 'planning', taskHints: ['Überraschung', 'Ort', 'Gäste', 'Geschenk'] },
  { situation: 'Meine Heimatküche', taskType: 'presentation', taskHints: ['typisches Gericht', 'Zutaten', 'Anlass', 'Zubereitung'] },
  { situation: 'Reaktion auf Heimatküche-Präsentation', taskType: 'reaction', taskHints: ['probiert?', 'eigene Küche'] },
  { situation: 'Einen Stadtspaziergang zusammen planen', taskType: 'planning', taskHints: ['Route', 'Dauer', 'Pausen', 'Ende'] },
  { situation: 'Mein Traumurlaub', taskType: 'presentation', taskHints: ['Ziel', 'Dauer', 'Aktivitäten', 'Begleitung'] },
  { situation: 'Reaktion auf Traumurlaub-Präsentation', taskType: 'reaction', taskHints: ['Budget fragen', 'eigene Reiseziele'] },
  { situation: 'Zusammen ein Geschenk für den Lehrer kaufen', taskType: 'planning', taskHints: ['Budget', 'Idee', 'Ort', 'Abgabe'] },
  { situation: 'Mein Handy — wie ich es nutze', taskType: 'presentation', taskHints: ['Apps', 'Dauer', 'Zweck', 'Vorteile'] },
  { situation: 'Reaktion auf Handy-Präsentation', taskType: 'reaction', taskHints: ['Nutzungsvergleich', 'App-Tipp'] },
  { situation: 'Ein Fahrradausflug planen', taskType: 'planning', taskHints: ['Route', 'Wetter', 'Proviant', 'Treffpunkt'] },
  { situation: 'Meine Woche', taskType: 'presentation', taskHints: ['Alltagstermine', 'Arbeit', 'Freizeit', 'Wochenende'] },
  { situation: 'Reaktion auf Wochen-Präsentation', taskType: 'reaction', taskHints: ['Zeitmanagement-Frage', 'eigener Ablauf'] },
]

export const SPRECHEN_A2: TopicData[] = [
  { situation: 'Geburtstagsfeier eines Kollegen organisieren', taskType: 'planning', taskHints: ['Ort', 'Zeit', 'Geschenk', 'Einladungen'] },
  { situation: 'Mein Arbeitsweg — Vor- und Nachteile', taskType: 'presentation', taskHints: ['Verkehrsmittel', 'Dauer', 'Vor-/Nachteile', 'Meinung'] },
  { situation: 'Reaktion auf Arbeitsweg-Präsentation', taskType: 'reaction', taskHints: ['Empfehlung', 'Verkehrsfrage'] },
  { situation: 'Ein Sommerfest für die Nachbarschaft planen', taskType: 'planning', taskHints: ['Datum', 'Ort', 'Essen', 'Einladung'] },
  { situation: 'Sprachen lernen in Deutschland', taskType: 'presentation', taskHints: ['Angebote', 'eigene Erfahrung', 'Vor-/Nachteile', 'Meinung'] },
  { situation: 'Reaktion auf Sprachen-Präsentation', taskType: 'reaction', taskHints: ['Kursempfehlung', 'eigener Weg'] },
  { situation: 'Einen Tagesausflug nach Hamburg planen', taskType: 'planning', taskHints: ['Anreise', 'Programm', 'Budget', 'Rückfahrt'] },
  { situation: 'Das Leben in der Großstadt', taskType: 'presentation', taskHints: ['Vorteile', 'Nachteile', 'Kosten', 'Meinung'] },
  { situation: 'Reaktion auf Großstadt-Präsentation', taskType: 'reaction', taskHints: ['Land vs Stadt', 'eigene Präferenz'] },
  { situation: 'Einen Kinoabend mit der WG planen', taskType: 'planning', taskHints: ['Film', 'Snacks', 'Start', 'Aufräumen'] },
  { situation: 'Deutsche Feiertage und Traditionen', taskType: 'presentation', taskHints: ['Bekannte Feiertage', 'Bräuche', 'Heimatvergleich', 'Meinung'] },
  { situation: 'Reaktion auf Feiertage-Präsentation', taskType: 'reaction', taskHints: ['eigene Tradition', 'Vergleich'] },
  { situation: 'Ein Fitnessstudio gemeinsam besuchen', taskType: 'planning', taskHints: ['Studio wählen', 'Abo', 'Zeitplan', 'Ziele'] },
  { situation: 'Mein Hobby und wie es mir hilft', taskType: 'presentation', taskHints: ['Hobby', 'Zeitaufwand', 'Nutzen', 'Empfehlung'] },
  { situation: 'Reaktion auf Hobby-Präsentation', taskType: 'reaction', taskHints: ['Einstiegstipps', 'Kostenfrage'] },
  { situation: 'Eine Fahrt mit dem Deutschland-Ticket planen', taskType: 'planning', taskHints: ['Ziel', 'Verbindung', 'Zeitplan', 'Proviant'] },
  { situation: 'Öffentliche Verkehrsmittel in Deutschland', taskType: 'presentation', taskHints: ['System', 'Preise', 'Pünktlichkeit', 'Meinung'] },
  { situation: 'Reaktion auf ÖPNV-Präsentation', taskType: 'reaction', taskHints: ['eigene Erfahrung', 'Alternativfrage'] },
  { situation: 'Ein gemeinsames Essen im Biergarten planen', taskType: 'planning', taskHints: ['Biergarten wählen', 'Uhrzeit', 'Reservierung', 'Bezahlung'] },
  { situation: 'Gesunde Ernährung im Alltag', taskType: 'presentation', taskHints: ['Definition', 'eigene Gewohnheiten', 'Herausforderungen', 'Meinung'] },
  { situation: 'Reaktion auf Ernährungs-Präsentation', taskType: 'reaction', taskHints: ['Alltagstipp', 'Unterschiede'] },
  { situation: 'Einen Umzug in eine neue Wohnung planen', taskType: 'planning', taskHints: ['Datum', 'Helfer', 'Transporter', 'Verpflegung'] },
  { situation: 'Das Wohnen zur Miete in Deutschland', taskType: 'presentation', taskHints: ['Mietvertrag', 'Nebenkosten', 'Rechte', 'Meinung'] },
  { situation: 'Reaktion auf Mieter-Präsentation', taskType: 'reaction', taskHints: ['eigene Erfahrung', 'Vermieter-Frage'] },
  { situation: 'Einen Besuch im Weihnachtsmarkt planen', taskType: 'planning', taskHints: ['Markt', 'Anreise', 'Essen', 'Geschenk-Einkauf'] },
  { situation: 'Weihnachten in Deutschland', taskType: 'presentation', taskHints: ['Bräuche', 'Essen', 'Heimatvergleich', 'eigene Eindrücke'] },
  { situation: 'Reaktion auf Weihnachts-Präsentation', taskType: 'reaction', taskHints: ['eigenes Fest', 'Lieblingsessen'] },
  { situation: 'Einen Arbeitsplatz gemeinsam einrichten', taskType: 'planning', taskHints: ['Möbel', 'Ort', 'Aufteilung', 'Budget'] },
  { situation: 'Arbeiten im Homeoffice — meine Sicht', taskType: 'presentation', taskHints: ['Ablauf', 'Vorteile', 'Nachteile', 'Meinung'] },
  { situation: 'Reaktion auf Homeoffice-Präsentation', taskType: 'reaction', taskHints: ['eigener Alltag', 'Trennung privat/beruflich'] },
  { situation: 'Eine Geburtstagsüberraschung für die Mutter planen', taskType: 'planning', taskHints: ['Idee', 'Helfer', 'Ort', 'Geschenk'] },
  { situation: 'Familienleben in meinem Heimatland', taskType: 'presentation', taskHints: ['Struktur', 'Traditionen', 'Rollen', 'Meinung'] },
  { situation: 'Reaktion auf Familien-Präsentation', taskType: 'reaction', taskHints: ['Vergleich Deutschland', 'Frage'] },
  { situation: 'Einen Sprachtandem organisieren', taskType: 'planning', taskHints: ['Partner', 'Ort', 'Zeit', 'Themen'] },
  { situation: 'Integration in Deutschland — meine Erfahrung', taskType: 'presentation', taskHints: ['Ankunft', 'Herausforderungen', 'Erfolge', 'Tipps'] },
  { situation: 'Reaktion auf Integrations-Präsentation', taskType: 'reaction', taskHints: ['persönliche Frage', 'Erfahrungsaustausch'] },
  { situation: 'Den ersten Besuch auf dem Bürgeramt vorbereiten', taskType: 'planning', taskHints: ['Unterlagen', 'Termin', 'Wegbeschreibung', 'Begleitung'] },
  { situation: 'Behördengänge in Deutschland', taskType: 'presentation', taskHints: ['wichtige Ämter', 'eigene Erfahrung', 'Tipps', 'Meinung'] },
  { situation: 'Reaktion auf Behörden-Präsentation', taskType: 'reaction', taskHints: ['Anekdote', 'Nachfrage zu Terminen'] },
  { situation: 'Einen Lauftreff im Park organisieren', taskType: 'planning', taskHints: ['Strecke', 'Uhrzeit', 'Häufigkeit', 'Kleidung'] },
  { situation: 'Sportvereine in Deutschland', taskType: 'presentation', taskHints: ['Struktur', 'Mitgliedschaft', 'Kosten', 'Meinung'] },
  { situation: 'Reaktion auf Sportvereins-Präsentation', taskType: 'reaction', taskHints: ['Einstiegstipp', 'eigener Verein'] },
  { situation: 'Einen gemeinsamen Urlaub planen', taskType: 'planning', taskHints: ['Ziel', 'Budget', 'Transport', 'Unterkunft'] },
  { situation: 'Reisen innerhalb Deutschlands', taskType: 'presentation', taskHints: ['beliebte Ziele', 'Kosten', 'Jahreszeit', 'Meinung'] },
  { situation: 'Reaktion auf Reisen-Präsentation', taskType: 'reaction', taskHints: ['Geheimtipp', 'Reisestil-Vergleich'] },
  { situation: 'Ein Deutsch-Sprachcafé organisieren', taskType: 'planning', taskHints: ['Ort', 'Themen', 'Werbung', 'Häufigkeit'] },
  { situation: 'Deutsches Fernsehen — was ich schaue', taskType: 'presentation', taskHints: ['Sender', 'Sendungen', 'Sprachnutzen', 'Meinung'] },
  { situation: 'Reaktion auf Fernseh-Präsentation', taskType: 'reaction', taskHints: ['Serienempfehlung', 'Streaming-Vergleich'] },
  { situation: 'Ein Gartenfest organisieren', taskType: 'planning', taskHints: ['Gäste', 'Essen', 'Spiele', 'Musik'] },
  { situation: 'Deutsche Gartenkultur und Schrebergärten', taskType: 'presentation', taskHints: ['Tradition', 'Regeln', 'Nutzen', 'Meinung'] },
  { situation: 'Reaktion auf Gartenkultur-Präsentation', taskType: 'reaction', taskHints: ['Heimatvergleich', 'Frage zu Kosten'] },
  { situation: 'Einen Sonntagsspaziergang an der Isar planen', taskType: 'planning', taskHints: ['Treffpunkt', 'Route', 'Picknick', 'Rückweg'] },
  { situation: 'Meine Lieblingsstadt in Deutschland', taskType: 'presentation', taskHints: ['Stadt', 'Sehenswürdigkeiten', 'Atmosphäre', 'Meinung'] },
  { situation: 'Reaktion auf Stadt-Präsentation', taskType: 'reaction', taskHints: ['eigene Lieblingsstadt', 'Vergleich'] },
  { situation: 'Eine Radtour an einem See planen', taskType: 'planning', taskHints: ['Strecke', 'Uhrzeit', 'Ausrüstung', 'Badestop'] },
  { situation: 'Mülltrennung in Deutschland', taskType: 'presentation', taskHints: ['Tonnen', 'Regeln', 'eigene Erfahrung', 'Meinung'] },
  { situation: 'Reaktion auf Mülltrennungs-Präsentation', taskType: 'reaction', taskHints: ['Heimatvergleich', 'Nachfrage'] },
  { situation: 'Einen Besuch im Zoo planen', taskType: 'planning', taskHints: ['Zoo', 'Anreise', 'Mittagessen', 'Tiere'] },
  { situation: 'Leben als Student*in in Deutschland', taskType: 'presentation', taskHints: ['Finanzen', 'Alltag', 'Herausforderungen', 'Meinung'] },
  { situation: 'Reaktion auf Studenten-Präsentation', taskType: 'reaction', taskHints: ['Nebenjob', 'Tipp'] },
]

export const SPRECHEN_B1: TopicData[] = [
  { situation: 'Eine Abschiedsparty für einen Kollegen organisieren', taskType: 'planning', taskHints: ['Ort', 'Datum', 'Gäste', 'Programm'] },
  { situation: 'Soziale Medien im Alltag', taskType: 'presentation', taskHints: ['Situation im Heimatland', 'Vorteile', 'Nachteile', 'Meinung'] },
  { situation: 'Reaktion auf Social-Media-Präsentation', taskType: 'reaction', taskHints: ['kritische Frage', 'eigene Nutzung'] },
  { situation: 'Ein Sommerfest im Betrieb organisieren', taskType: 'planning', taskHints: ['Ort', 'Budget', 'Programm', 'Einladungen'] },
  { situation: 'Digitalisierung in der Arbeitswelt', taskType: 'presentation', taskHints: ['Beispiele', 'Chancen', 'Risiken', 'Meinung'] },
  { situation: 'Reaktion auf Digitalisierungs-Präsentation', taskType: 'reaction', taskHints: ['Branchenfrage', 'eigene Position'] },
  { situation: 'Einen Workshop gegen Stress im Büro organisieren', taskType: 'planning', taskHints: ['Inhalte', 'Termin', 'Teilnehmer', 'Referent'] },
  { situation: 'Work-Life-Balance in Deutschland', taskType: 'presentation', taskHints: ['Stand heute', 'Beispiele', 'Heimatvergleich', 'Meinung'] },
  { situation: 'Reaktion auf Work-Life-Balance-Präsentation', taskType: 'reaction', taskHints: ['Rollenbild-Frage', 'eigene Strategie'] },
  { situation: 'Ein Klassentreffen in Berlin organisieren', taskType: 'planning', taskHints: ['Datum', 'Hotel', 'Programm', 'Reisekosten'] },
  { situation: 'Das deutsche Ausbildungssystem — duale Ausbildung', taskType: 'presentation', taskHints: ['Struktur', 'Vor-/Nachteile', 'Heimatvergleich', 'Meinung'] },
  { situation: 'Reaktion auf Ausbildungs-Präsentation', taskType: 'reaction', taskHints: ['Studium vs Ausbildung', 'eigene Wahl'] },
  { situation: 'Eine Spendenaktion für ein Tierheim organisieren', taskType: 'planning', taskHints: ['Ziel', 'Format', 'Werbung', 'Ehrenamtliche'] },
  { situation: 'Ehrenamt in Deutschland', taskType: 'presentation', taskHints: ['Beispiele', 'Motivation', 'Nutzen', 'Meinung'] },
  { situation: 'Reaktion auf Ehrenamt-Präsentation', taskType: 'reaction', taskHints: ['Zeitfrage', 'eigene Erfahrung'] },
  { situation: 'Einen Kurs in Stressmanagement gemeinsam besuchen', taskType: 'planning', taskHints: ['Kurs', 'Termine', 'Kosten', 'Ziele'] },
  { situation: 'Gesundheitssystem in Deutschland', taskType: 'presentation', taskHints: ['Krankenkassen', 'Arztbesuche', 'Heimatvergleich', 'Meinung'] },
  { situation: 'Reaktion auf Gesundheitssystem-Präsentation', taskType: 'reaction', taskHints: ['Wartezeit-Frage', 'private vs gesetzlich'] },
  { situation: 'Eine Radtour an der Ostsee planen', taskType: 'planning', taskHints: ['Route', 'Unterkunft', 'Ausrüstung', 'Tagesplan'] },
  { situation: 'Umweltbewusstsein und Nachhaltigkeit', taskType: 'presentation', taskHints: ['Definition', 'Alltagsbeispiele', 'Politik', 'Meinung'] },
  { situation: 'Reaktion auf Nachhaltigkeits-Präsentation', taskType: 'reaction', taskHints: ['Klimaanlagen-Debatte', 'eigene Maßnahmen'] },
  { situation: 'Einen Sprachaustausch mit einer Partnerstadt organisieren', taskType: 'planning', taskHints: ['Teilnehmer', 'Programm', 'Budget', 'Dolmetscher'] },
  { situation: 'Integration und interkulturelle Kommunikation', taskType: 'presentation', taskHints: ['Herausforderungen', 'Beispiele', 'Lösungen', 'Meinung'] },
  { situation: 'Reaktion auf Integrations-Präsentation', taskType: 'reaction', taskHints: ['Sprachhürden', 'eigene Erfahrung'] },
  { situation: 'Einen Kochabend mit Gerichten aus mehreren Ländern organisieren', taskType: 'planning', taskHints: ['Länder', 'Zutaten', 'Ablauf', 'Musik'] },
  { situation: 'Ernährungstrends in Deutschland (vegan, Bio, regional)', taskType: 'presentation', taskHints: ['Überblick', 'Beispiele', 'Heimatvergleich', 'Meinung'] },
  { situation: 'Reaktion auf Ernährungstrends-Präsentation', taskType: 'reaction', taskHints: ['Preisfrage', 'eigene Ernährung'] },
  { situation: 'Einen Stadtmarathon gemeinsam laufen', taskType: 'planning', taskHints: ['Marathon wählen', 'Training', 'Anmeldung', 'Anreise'] },
  { situation: 'Sport und Gesundheit im Alltag', taskType: 'presentation', taskHints: ['Empfehlungen', 'Hindernisse', 'eigene Routine', 'Meinung'] },
  { situation: 'Reaktion auf Sport-Präsentation', taskType: 'reaction', taskHints: ['Zeitmanagement', 'eigene Sportart'] },
  { situation: 'Einen Workshop zur Berufsorientierung für Schüler organisieren', taskType: 'planning', taskHints: ['Inhalte', 'Referenten', 'Schulen', 'Materialien'] },
  { situation: 'Der deutsche Arbeitsmarkt heute', taskType: 'presentation', taskHints: ['Fachkräftemangel', 'Branchen', 'Chancen', 'Meinung'] },
  { situation: 'Reaktion auf Arbeitsmarkt-Präsentation', taskType: 'reaction', taskHints: ['Quereinstieg', 'Lohnunterschiede'] },
  { situation: 'Eine Demonstration für mehr Radwege planen', taskType: 'planning', taskHints: ['Route', 'Genehmigung', 'Werbung', 'Redner'] },
  { situation: 'Politische Beteiligung junger Menschen', taskType: 'presentation', taskHints: ['Formen', 'Hindernisse', 'Beispiele', 'Meinung'] },
  { situation: 'Reaktion auf Politik-Präsentation', taskType: 'reaction', taskHints: ['Wahlbeteiligung', 'eigene Meinung'] },
  { situation: 'Ein Filmabend mit deutschen Filmen organisieren', taskType: 'planning', taskHints: ['Filmauswahl', 'Untertitel', 'Essen', 'Diskussion'] },
  { situation: 'Deutscher Film und deutsche Serien', taskType: 'presentation', taskHints: ['Beispiele', 'Themen', 'Sprachnutzen', 'Meinung'] },
  { situation: 'Reaktion auf Film-Präsentation', taskType: 'reaction', taskHints: ['Empfehlung', 'Heimatvergleich'] },
  { situation: 'Einen Ausflug in einen Nationalpark planen', taskType: 'planning', taskHints: ['Park', 'Wanderroute', 'Unterkunft', 'Verkehrsmittel'] },
  { situation: 'Natur- und Umweltschutz in Deutschland', taskType: 'presentation', taskHints: ['Gesetze', 'NGO', 'eigene Maßnahmen', 'Meinung'] },
  { situation: 'Reaktion auf Naturschutz-Präsentation', taskType: 'reaction', taskHints: ['Klimaschutz-Maßnahmen', 'Alltagsfrage'] },
  { situation: 'Ein Fundraising-Dinner für die Flüchtlingshilfe organisieren', taskType: 'planning', taskHints: ['Ort', 'Menü', 'Gäste', 'Spendenziel'] },
  { situation: 'Flucht und Migration in Europa', taskType: 'presentation', taskHints: ['Ursachen', 'Zahlen', 'Integration', 'Meinung'] },
  { situation: 'Reaktion auf Migrations-Präsentation', taskType: 'reaction', taskHints: ['Bildungsfrage', 'eigene Sicht'] },
  { situation: 'Einen Workshop zu Cybersicherheit organisieren', taskType: 'planning', taskHints: ['Inhalte', 'Zielgruppe', 'Referent', 'Ort'] },
  { situation: 'Datenschutz und Privatsphäre online', taskType: 'presentation', taskHints: ['Risiken', 'Gesetze', 'Tipps', 'Meinung'] },
  { situation: 'Reaktion auf Datenschutz-Präsentation', taskType: 'reaction', taskHints: ['eigene Gewohnheiten', 'Konkrete Apps'] },
  { situation: 'Ein gemeinsames Elterngeld-Beratungsseminar organisieren', taskType: 'planning', taskHints: ['Thema', 'Referent', 'Einladung', 'Raum'] },
  { situation: 'Vereinbarkeit von Beruf und Familie', taskType: 'presentation', taskHints: ['Möglichkeiten', 'Herausforderungen', 'Heimatvergleich', 'Meinung'] },
  { situation: 'Reaktion auf Vereinbarkeits-Präsentation', taskType: 'reaction', taskHints: ['Rollenverteilung', 'Kita-Plätze'] },
  { situation: 'Einen Lesekreis gründen', taskType: 'planning', taskHints: ['Bücher', 'Treffen', 'Teilnehmer', 'Raum'] },
  { situation: 'Lesegewohnheiten heute — Papier oder digital', taskType: 'presentation', taskHints: ['Entwicklung', 'Vorteile beider', 'eigene Nutzung', 'Meinung'] },
  { situation: 'Reaktion auf Lese-Präsentation', taskType: 'reaction', taskHints: ['Bibliothek-Frage', 'Leseempfehlung'] },
  { situation: 'Ein Startup-Pitch-Event organisieren', taskType: 'planning', taskHints: ['Location', 'Teilnehmer', 'Jury', 'Preise'] },
  { situation: 'Unternehmertum und Start-ups in Deutschland', taskType: 'presentation', taskHints: ['Beispiele', 'Rahmenbedingungen', 'Hindernisse', 'Meinung'] },
  { situation: 'Reaktion auf Start-up-Präsentation', taskType: 'reaction', taskHints: ['Finanzierung', 'eigene Idee'] },
  { situation: 'Eine Klimaaktionswoche in der Firma organisieren', taskType: 'planning', taskHints: ['Themen', 'Events', 'Teilnehmer', 'Budget'] },
  { situation: 'Der Klimawandel und seine Folgen für Deutschland', taskType: 'presentation', taskHints: ['Fakten', 'Regionen', 'Maßnahmen', 'Meinung'] },
  { situation: 'Reaktion auf Klimawandel-Präsentation', taskType: 'reaction', taskHints: ['individuelle Verantwortung', 'politische Maßnahmen'] },
]
