// lib/motivational-quotes.ts
//
// 100 мотивационных фраз на немецком с переводами на RU/EN/TR.
// Показываются под приветствием на /dashboard, рандомно на каждой загрузке страницы.
//
// Структура:
//   - de: оригинал на немецком (ВСЕГДА первым, основная единица)
//   - ru/en/tr: литературный перевод (не дословный)
//   - author: автор цитаты (null для пословиц/идиом)
//   - category: для потенциальной категоризации в будущем ('proverb' | 'idiom' | 'quote' | 'motivation' | 'path')
//
// При рендере: de показывается крупнее/акцентом, перевод — мелким вторичным текстом под ним.

export type MotivationalQuote = {
  de: string;
  ru: string;
  en: string;
  tr: string;
  author: string | null;
  category: 'proverb' | 'idiom' | 'quote' | 'motivation' | 'path';
};

export const motivationalQuotes: MotivationalQuote[] = [
  // ─── Пословицы (Sprichwörter) — 30 ───
  {
    de: 'Übung macht den Meister.',
    ru: 'Повторение — мать учения.',
    en: 'Practice makes perfect.',
    tr: 'Pratik ustalaştırır.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Wer rastet, der rostet.',
    ru: 'Кто отдыхает, тот ржавеет.',
    en: 'He who rests grows rusty.',
    tr: 'Dinlenen paslanır.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Morgenstund hat Gold im Mund.',
    ru: 'У раннего утра золото в устах.',
    en: 'The early bird catches the worm.',
    tr: 'Sabahın altın saati vardır.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Ohne Fleiß kein Preis.',
    ru: 'Без труда не вытащишь и рыбку из пруда.',
    en: 'No pain, no gain.',
    tr: 'Emek olmadan yemek olmaz.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Gut Ding will Weile haben.',
    ru: 'Хорошему делу нужно время.',
    en: 'Good things take time.',
    tr: 'İyi işler zaman ister.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Wer wagt, gewinnt.',
    ru: 'Кто рискует, тот выигрывает.',
    en: 'Fortune favours the bold.',
    tr: 'Cesaret kazandırır.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Aller Anfang ist schwer.',
    ru: 'Любое начало трудно.',
    en: 'Every beginning is hard.',
    tr: 'Her başlangıç zordur.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Es ist noch kein Meister vom Himmel gefallen.',
    ru: 'Мастером не рождаются — становятся.',
    en: 'No master has ever fallen from the sky.',
    tr: 'Usta gökten zembille inmez.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Geduld bringt Rosen.',
    ru: 'Терпение приносит розы.',
    en: 'Patience brings roses.',
    tr: 'Sabır güller getirir.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Wer A sagt, muss auch B sagen.',
    ru: 'Сказавший «А» должен сказать и «Б».',
    en: 'In for a penny, in for a pound.',
    tr: 'A diyen B demek zorunda kalır.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Der Weg ist das Ziel.',
    ru: 'Путь и есть цель.',
    en: 'The journey is the destination.',
    tr: 'Yol, varılacak yerin kendisidir.',
    author: null,
    category: 'path',
  },
  {
    de: 'Viele Wege führen nach Rom.',
    ru: 'Все дороги ведут в Рим.',
    en: 'All roads lead to Rome.',
    tr: 'Bütün yollar Roma\'ya çıkar.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Steter Tropfen höhlt den Stein.',
    ru: 'Капля камень точит.',
    en: 'Constant dripping wears the stone.',
    tr: 'Damlaya damlaya göl olur.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Was du heute kannst besorgen, das verschiebe nicht auf morgen.',
    ru: 'Не откладывай на завтра то, что можешь сделать сегодня.',
    en: 'Never put off till tomorrow what you can do today.',
    tr: 'Bugünün işini yarına bırakma.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Wer nicht wagt, der nicht gewinnt.',
    ru: 'Кто не рискует — тот не выигрывает.',
    en: 'Nothing ventured, nothing gained.',
    tr: 'Risk almayan kazanamaz.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'In der Ruhe liegt die Kraft.',
    ru: 'Сила — в спокойствии.',
    en: 'Strength lies in calmness.',
    tr: 'Güç, sükûnette yatar.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Probieren geht über Studieren.',
    ru: 'Попробовать — лучше, чем долго изучать.',
    en: 'The proof is in the pudding.',
    tr: 'Denemek, çalışmaktan üstündür.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Fleiß bricht Eis.',
    ru: 'Усердие ломает лёд.',
    en: 'Diligence breaks the ice.',
    tr: 'Azim buzu bile kırar.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Kleinvieh macht auch Mist.',
    ru: 'Копейка рубль бережёт.',
    en: 'Every little helps.',
    tr: 'Damla damla göl olur.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Eile mit Weile.',
    ru: 'Торопись не спеша.',
    en: 'Make haste slowly.',
    tr: 'Yavaş yavaş acele et.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Wie man in den Wald hineinruft, so schallt es heraus.',
    ru: 'Как аукнется, так и откликнется.',
    en: 'What you put in, you get out.',
    tr: 'Ne ekersen onu biçersin.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Früh übt sich, wer ein Meister werden will.',
    ru: 'Мастером становится тот, кто рано начинает.',
    en: 'Practice early if you want to be a master.',
    tr: 'Usta olmak isteyen erkenden başlar.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Lieber spät als nie.',
    ru: 'Лучше поздно, чем никогда.',
    en: 'Better late than never.',
    tr: 'Geç olsun, güç olmasın.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Der Appetit kommt beim Essen.',
    ru: 'Аппетит приходит во время еды.',
    en: 'Appetite comes with eating.',
    tr: 'İştah yemekle açılır.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Gelegenheit macht Diebe.',
    ru: 'Случай создаёт вора.',
    en: 'Opportunity makes the thief.',
    tr: 'Fırsat hırsız yaratır.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Wer zuletzt lacht, lacht am besten.',
    ru: 'Хорошо смеётся тот, кто смеётся последним.',
    en: 'He who laughs last laughs longest.',
    tr: 'Son gülen iyi güler.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Der Klügere gibt nach.',
    ru: 'Умный уступает.',
    en: 'The wiser one gives in.',
    tr: 'Akıllı olan geri adım atar.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Kommt Zeit, kommt Rat.',
    ru: 'Утро вечера мудренее.',
    en: 'Time will tell.',
    tr: 'Zaman her şeyi çözer.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Wer sucht, der findet.',
    ru: 'Кто ищет, тот найдёт.',
    en: 'Seek and you shall find.',
    tr: 'Arayan bulur.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Alles hat ein Ende, nur die Wurst hat zwei.',
    ru: 'Всё имеет конец — только колбаса имеет два.',
    en: 'Everything has an end — only the sausage has two.',
    tr: 'Her şeyin bir sonu vardır, yalnız sosisin iki.',
    author: null,
    category: 'proverb',
  },

  // ─── Redewendungen и идиомы — 25 ───
  {
    de: 'Das ist nicht mein Bier.',
    ru: 'Это не моё дело.',
    en: 'That\'s not my problem.',
    tr: 'Bu benim işim değil.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Da liegt der Hund begraben.',
    ru: 'Вот где собака зарыта.',
    en: 'That\'s where the shoe pinches.',
    tr: 'İşin sırrı burada.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Tomaten auf den Augen haben.',
    ru: 'Не замечать очевидного.',
    en: 'To be blind to the obvious.',
    tr: 'Gözlerinin önündekini görememek.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Das A und O.',
    ru: 'Альфа и омега. Самое главное.',
    en: 'The be-all and end-all.',
    tr: 'Her şeyin özü.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Den Nagel auf den Kopf treffen.',
    ru: 'Попасть в самую точку.',
    en: 'To hit the nail on the head.',
    tr: 'Çiviyi kafasına vurmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Ich verstehe nur Bahnhof.',
    ru: 'Я ничего не понимаю.',
    en: 'It\'s all Greek to me.',
    tr: 'Hiçbir şey anlamıyorum.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Das ist ein Katzensprung.',
    ru: 'Это в двух шагах.',
    en: 'It\'s a stone\'s throw away.',
    tr: 'Burası iki adım ötede.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Schwein haben.',
    ru: 'Повезло.',
    en: 'To be lucky.',
    tr: 'Şanslı olmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Auf dem Holzweg sein.',
    ru: 'Идти по ложному пути.',
    en: 'To be on the wrong track.',
    tr: 'Yanlış yolda olmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Die Daumen drücken.',
    ru: 'Держать кулачки.',
    en: 'To keep one\'s fingers crossed.',
    tr: 'Parmak tutmak (şans dilemek).',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Etwas auf die lange Bank schieben.',
    ru: 'Откладывать в долгий ящик.',
    en: 'To put something on the back burner.',
    tr: 'Bir işi ertelemek.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Das kommt mir spanisch vor.',
    ru: 'Это мне кажется странным.',
    en: 'That seems fishy to me.',
    tr: 'Bana tuhaf geliyor.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Das ist Schnee von gestern.',
    ru: 'Это вчерашние новости.',
    en: 'That\'s water under the bridge.',
    tr: 'Bu artık eski meseledir.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Ins kalte Wasser springen.',
    ru: 'Прыгнуть в воду с головой.',
    en: 'To jump into the deep end.',
    tr: 'Soğuk suya dalmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Über seinen Schatten springen.',
    ru: 'Перешагнуть через себя.',
    en: 'To step out of one\'s comfort zone.',
    tr: 'Kendini aşmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Zwei Fliegen mit einer Klappe schlagen.',
    ru: 'Убить двух зайцев одним выстрелом.',
    en: 'To kill two birds with one stone.',
    tr: 'Bir taşla iki kuş vurmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Die Katze im Sack kaufen.',
    ru: 'Купить кота в мешке.',
    en: 'To buy a pig in a poke.',
    tr: 'Torbadaki kediyi satın almak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Um den heißen Brei herumreden.',
    ru: 'Ходить вокруг да около.',
    en: 'To beat around the bush.',
    tr: 'Lafı dolandırmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Mit dem falschen Fuß aufstehen.',
    ru: 'Встать не с той ноги.',
    en: 'To get out of bed on the wrong side.',
    tr: 'Yanlış ayakla kalkmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Einen Frosch im Hals haben.',
    ru: 'Чувствовать ком в горле.',
    en: 'To have a frog in one\'s throat.',
    tr: 'Boğazında bir yumru olmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Das ist mir Wurst.',
    ru: 'Мне всё равно.',
    en: 'I don\'t care.',
    tr: 'Bana fark etmez.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Aus einer Mücke einen Elefanten machen.',
    ru: 'Делать из мухи слона.',
    en: 'To make a mountain out of a molehill.',
    tr: 'Pireyi deve yapmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Ins Fettnäpfchen treten.',
    ru: 'Попасть впросак.',
    en: 'To put one\'s foot in one\'s mouth.',
    tr: 'Çam devirmek.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Die Nase voll haben.',
    ru: 'Быть сытым по горло.',
    en: 'To be fed up.',
    tr: 'Bıkmak usanmak.',
    author: null,
    category: 'idiom',
  },
  {
    de: 'Auf Wolke sieben schweben.',
    ru: 'Быть на седьмом небе.',
    en: 'To be on cloud nine.',
    tr: 'Yedinci gökte uçmak.',
    author: null,
    category: 'idiom',
  },

  // ─── Цитаты немецких мыслителей — 20 ───
  {
    de: 'Wer fremde Sprachen nicht kennt, weiß nichts von seiner eigenen.',
    ru: 'Кто не знает иностранных языков, не знает ничего о своём.',
    en: 'He who knows no foreign languages knows nothing of his own.',
    tr: 'Yabancı dil bilmeyen, kendi dilini de bilmez.',
    author: 'Johann Wolfgang von Goethe',
    category: 'quote',
  },
  {
    de: 'Es ist nicht genug zu wissen, man muss auch anwenden.',
    ru: 'Недостаточно знать — нужно применять.',
    en: 'Knowing is not enough; we must apply.',
    tr: 'Bilmek yetmez, uygulamak gerekir.',
    author: 'Johann Wolfgang von Goethe',
    category: 'quote',
  },
  {
    de: 'Was man nicht aufgibt, hat man nie verloren.',
    ru: 'То, от чего не отказываешься, никогда не потеряно.',
    en: 'What you don\'t give up, you never lose.',
    tr: 'Vazgeçmediğin şeyi hiç kaybetmedin demektir.',
    author: 'Friedrich Schiller',
    category: 'quote',
  },
  {
    de: 'Die Grenzen meiner Sprache bedeuten die Grenzen meiner Welt.',
    ru: 'Границы моего языка — это границы моего мира.',
    en: 'The limits of my language mean the limits of my world.',
    tr: 'Dilimin sınırları, dünyamın sınırlarıdır.',
    author: 'Ludwig Wittgenstein',
    category: 'quote',
  },
  {
    de: 'Wer einen Berg besteigen will, muss unten anfangen.',
    ru: 'Кто хочет покорить гору, должен начать снизу.',
    en: 'He who wants to climb a mountain must start at the bottom.',
    tr: 'Dağa tırmanmak isteyen aşağıdan başlamalıdır.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Der Mensch ist, was er isst.',
    ru: 'Человек есть то, что он ест.',
    en: 'Man is what he eats.',
    tr: 'İnsan yediği şeyden ibarettir.',
    author: 'Ludwig Feuerbach',
    category: 'quote',
  },
  {
    de: 'Ich denke, also bin ich.',
    ru: 'Я мыслю, следовательно, существую.',
    en: 'I think, therefore I am.',
    tr: 'Düşünüyorum, öyleyse varım.',
    author: 'René Descartes',
    category: 'quote',
  },
  {
    de: 'Wer nicht von dreitausend Jahren sich weiß Rechenschaft zu geben, bleibt im Dunkeln unerfahren.',
    ru: 'Кто не может отчитаться перед тремя тысячами лет, остаётся в темноте.',
    en: 'He who cannot account for three thousand years remains inexperienced in the dark.',
    tr: 'Üç bin yılın hesabını veremeyen, karanlıkta tecrübesiz kalır.',
    author: 'Johann Wolfgang von Goethe',
    category: 'quote',
  },
  {
    de: 'Man reist nicht, um anzukommen, sondern um zu reisen.',
    ru: 'Путешествуют не ради прибытия, а ради самого пути.',
    en: 'One travels not to arrive, but to travel.',
    tr: 'Varmak için değil, yolculuk etmek için seyahat edilir.',
    author: 'Johann Wolfgang von Goethe',
    category: 'path',
  },
  {
    de: 'Der Weg ist das Ziel.',
    ru: 'Путь — это и есть цель.',
    en: 'The path is the goal.',
    tr: 'Yol, varılacak yerin kendisidir.',
    author: 'Konfuzius',
    category: 'path',
  },
  {
    de: 'Wer will, findet Wege. Wer nicht will, findet Gründe.',
    ru: 'Кто хочет — ищет способы. Кто не хочет — ищет причины.',
    en: 'Where there\'s a will, there\'s a way.',
    tr: 'İsteyen yol bulur, istemeyen bahane bulur.',
    author: 'Götz Werner',
    category: 'motivation',
  },
  {
    de: 'Man muss das Unmögliche versuchen, um das Mögliche zu erreichen.',
    ru: 'Нужно пытаться сделать невозможное, чтобы достичь возможного.',
    en: 'One must attempt the impossible to achieve the possible.',
    tr: 'Mümkün olanı başarmak için imkânsız olanı denemek gerekir.',
    author: 'Hermann Hesse',
    category: 'quote',
  },
  {
    de: 'Der Lernende weiß mehr als das Buch.',
    ru: 'Учащийся знает больше, чем книга.',
    en: 'The learner knows more than the book.',
    tr: 'Öğrenen, kitaptan daha çok şey bilir.',
    author: 'Friedrich Rückert',
    category: 'quote',
  },
  {
    de: 'Man lernt nie aus.',
    ru: 'Век живи — век учись.',
    en: 'You never stop learning.',
    tr: 'İnsan ömür boyu öğrenir.',
    author: null,
    category: 'proverb',
  },
  {
    de: 'Sprache ist der Schlüssel zur Welt.',
    ru: 'Язык — это ключ к миру.',
    en: 'Language is the key to the world.',
    tr: 'Dil, dünyaya açılan anahtardır.',
    author: 'Wilhelm von Humboldt',
    category: 'quote',
  },
  {
    de: 'Wer nichts weiß, muss alles glauben.',
    ru: 'Кто ничего не знает, должен всему верить.',
    en: 'He who knows nothing must believe everything.',
    tr: 'Hiçbir şey bilmeyen her şeye inanmak zorundadır.',
    author: 'Marie von Ebner-Eschenbach',
    category: 'quote',
  },
  {
    de: 'Mut steht am Anfang des Handelns, Glück am Ende.',
    ru: 'Мужество стоит в начале действия, удача — в конце.',
    en: 'Courage stands at the beginning of action, happiness at the end.',
    tr: 'Cesaret işin başında, mutluluk sonundadır.',
    author: 'Demokrit',
    category: 'quote',
  },
  {
    de: 'Bildung ist das, was übrig bleibt, wenn man alles vergessen hat, was man gelernt hat.',
    ru: 'Образование — это то, что остаётся, когда ты забыл всё, что учил.',
    en: 'Education is what remains after one has forgotten what one has learned.',
    tr: 'Eğitim, öğrendiklerini unuttuğunda geriye kalan şeydir.',
    author: 'Werner Heisenberg',
    category: 'quote',
  },
  {
    de: 'Das Schönste, was wir erleben können, ist das Geheimnisvolle.',
    ru: 'Самое прекрасное, что мы можем испытать — это тайна.',
    en: 'The most beautiful thing we can experience is the mysterious.',
    tr: 'Yaşayabileceğimiz en güzel şey, gizemli olandır.',
    author: 'Albert Einstein',
    category: 'quote',
  },
  {
    de: 'Phantasie ist wichtiger als Wissen.',
    ru: 'Воображение важнее знания.',
    en: 'Imagination is more important than knowledge.',
    tr: 'Hayal gücü, bilgiden daha önemlidir.',
    author: 'Albert Einstein',
    category: 'quote',
  },

  // ─── Мотивация про обучение и настойчивость — 15 ───
  {
    de: 'Jeder Meister war einmal ein Anfänger.',
    ru: 'Каждый мастер когда-то был новичком.',
    en: 'Every master was once a beginner.',
    tr: 'Her usta, bir zamanlar çıraktı.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Ein kleiner Schritt ist besser als ein großes Versprechen.',
    ru: 'Маленький шаг лучше большого обещания.',
    en: 'A small step is better than a grand promise.',
    tr: 'Küçük bir adım, büyük bir sözden iyidir.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Fehler sind die Pforten der Entdeckung.',
    ru: 'Ошибки — это врата к открытию.',
    en: 'Mistakes are the portals of discovery.',
    tr: 'Hatalar, keşfin kapılarıdır.',
    author: 'James Joyce',
    category: 'motivation',
  },
  {
    de: 'Jede Seite, die du verstehst, ist ein Sieg.',
    ru: 'Каждая понятая страница — это победа.',
    en: 'Every page you understand is a victory.',
    tr: 'Anladığın her sayfa bir zaferdir.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Wer heute lernt, spricht morgen.',
    ru: 'Кто учится сегодня — говорит завтра.',
    en: 'Who learns today speaks tomorrow.',
    tr: 'Bugün öğrenen, yarın konuşur.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Eine neue Sprache — ein neues Leben.',
    ru: 'Новый язык — новая жизнь.',
    en: 'A new language — a new life.',
    tr: 'Yeni bir dil — yeni bir hayat.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Die Zunge lernt, was das Ohr hört.',
    ru: 'Язык учится тому, что слышит ухо.',
    en: 'The tongue learns what the ear hears.',
    tr: 'Dil, kulağın duyduğunu öğrenir.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Wer Deutsch spricht, öffnet Türen in Europa.',
    ru: 'Кто говорит по-немецки, открывает двери в Европу.',
    en: 'Who speaks German opens doors in Europe.',
    tr: 'Almanca konuşan, Avrupa\'nın kapılarını açar.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Was man oft hört, bleibt im Kopf.',
    ru: 'Что слышишь часто — остаётся в голове.',
    en: 'What you hear often stays in the mind.',
    tr: 'Sık duyulan, akılda kalır.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Wer heute übt, kann morgen frei sprechen.',
    ru: 'Кто практикуется сегодня — говорит свободно завтра.',
    en: 'Who practices today speaks freely tomorrow.',
    tr: 'Bugün pratik yapan, yarın rahatça konuşur.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Nur wer selbst brennt, kann in anderen Feuer entfachen.',
    ru: 'Только тот, кто сам горит, может зажечь других.',
    en: 'Only he who burns himself can ignite others.',
    tr: 'Yalnız yanan, başkasını tutuşturabilir.',
    author: 'Augustinus',
    category: 'motivation',
  },
  {
    de: 'Das Gestern ist vergangen, das Morgen ist ungewiss — heute ist dein Tag.',
    ru: 'Вчера — прошло, завтра — неясно, сегодня — твой день.',
    en: 'Yesterday is gone, tomorrow is uncertain — today is your day.',
    tr: 'Dün geçti, yarın belirsiz — bugün senin günün.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Wer Fragen stellt, kann sich nicht verirren.',
    ru: 'Кто задаёт вопросы, не заблудится.',
    en: 'Who asks questions does not get lost.',
    tr: 'Soru soran yolunu kaybetmez.',
    author: null,
    category: 'motivation',
  },
  {
    de: 'Die schönste Reise ist die, die noch vor dir liegt.',
    ru: 'Самое красивое путешествие — то, что ещё впереди.',
    en: 'The most beautiful journey is the one still ahead of you.',
    tr: 'En güzel yolculuk, önünde olanıdır.',
    author: null,
    category: 'path',
  },
  {
    de: 'Deutsch ist keine Sprache — es ist ein Weg.',
    ru: 'Немецкий — это не язык, это путь.',
    en: 'German is not a language — it is a path.',
    tr: 'Almanca bir dil değil — bir yoldur.',
    author: null,
    category: 'path',
  },

  // ─── Fernweh / путь / дорога — 10 ───
  {
    de: 'Reisen erweitert den Horizont.',
    ru: 'Путешествия расширяют горизонты.',
    en: 'Travel broadens the mind.',
    tr: 'Seyahat ufku genişletir.',
    author: null,
    category: 'path',
  },
  {
    de: 'Wer reist, lernt die Welt und sich selbst kennen.',
    ru: 'Кто путешествует, узнаёт мир и себя.',
    en: 'Who travels learns the world and himself.',
    tr: 'Seyahat eden, dünyayı ve kendini tanır.',
    author: null,
    category: 'path',
  },
  {
    de: 'Der erste Schritt ist der wichtigste.',
    ru: 'Первый шаг — самый важный.',
    en: 'The first step is the most important.',
    tr: 'İlk adım en önemlisidir.',
    author: null,
    category: 'path',
  },
  {
    de: 'Tausend Meilen beginnen mit einem Schritt.',
    ru: 'Путь в тысячу миль начинается с одного шага.',
    en: 'A journey of a thousand miles begins with a single step.',
    tr: 'Bin millik yol, tek bir adımla başlar.',
    author: 'Laotse',
    category: 'path',
  },
  {
    de: 'Heimat ist nicht ein Ort, sondern ein Gefühl.',
    ru: 'Родина — это не место, а чувство.',
    en: 'Home is not a place, but a feeling.',
    tr: 'Yuva bir yer değil, bir duygudur.',
    author: null,
    category: 'path',
  },
  {
    de: 'Fremde Sprachen sind Brücken, nicht Mauern.',
    ru: 'Иностранные языки — это мосты, а не стены.',
    en: 'Foreign languages are bridges, not walls.',
    tr: 'Yabancı diller köprüdür, duvar değil.',
    author: null,
    category: 'path',
  },
  {
    de: 'Wohin du auch gehst, geh mit ganzem Herzen.',
    ru: 'Куда бы ты ни шёл — иди от всего сердца.',
    en: 'Wherever you go, go with all your heart.',
    tr: 'Nereye gidersen git, bütün kalbinle git.',
    author: 'Konfuzius',
    category: 'path',
  },
  {
    de: 'Nicht das Ziel macht den Reisenden, sondern der Weg.',
    ru: 'Путешественника делает не цель, а путь.',
    en: 'Not the destination makes the traveller, but the path.',
    tr: 'Yolcuyu hedef değil, yol yapar.',
    author: null,
    category: 'path',
  },
  {
    de: 'Wer eine Sprache lernt, gewinnt eine Seele.',
    ru: 'Кто учит язык — обретает душу.',
    en: 'Who learns a language gains a soul.',
    tr: 'Dil öğrenen, bir ruh kazanır.',
    author: null,
    category: 'path',
  },
  {
    de: 'Jeder Tag ist eine neue Seite in deinem Buch.',
    ru: 'Каждый день — это новая страница в твоей книге.',
    en: 'Every day is a new page in your book.',
    tr: 'Her gün, kitabındaki yeni bir sayfadır.',
    author: null,
    category: 'path',
  },
];

/**
 * Возвращает случайную фразу из набора.
 * Используется на /dashboard под приветствием — меняется при каждой загрузке страницы.
 *
 * Реализация через Math.random() устраивает для клиентского рендера.
 * Если в будущем понадобится seed-based (для SSR-консистентности или A/B-теста) —
 * заменить на параметризованную версию с seed.
 */
export function getRandomQuote(): MotivationalQuote {
  const index = Math.floor(Math.random() * motivationalQuotes.length);
  return motivationalQuotes[index];
}

/**
 * Возвращает перевод фразы на нужную локаль.
 * Fallback: если локали нет в enum — возвращает немецкий.
 */
export function getQuoteTranslation(
  quote: MotivationalQuote,
  locale: 'de' | 'ru' | 'en' | 'tr',
): string {
  return quote[locale] ?? quote.de;
}
