'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { useLocale, useTranslations } from 'next-intl'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'

/**
 * Landing · Hören mockup with a real, playable B1 sample.
 *
 * The waveform animates left-to-right based on `audio.currentTime / duration`
 * (no Web Audio FFT — overkill for a 22-second decorative clip; real progress
 * is enough). Pill "Click to listen" + pulsing ring around play call attention
 * to the fact this is interactive (other module mockups in this section are
 * decorative, so the user needs a hint).
 *
 * Both the pill and the pulsing ring disappear after the first play — once the
 * user has discovered the affordance, the chrome becomes silent.
 *
 * Audio file is generated by scripts/generate-hoeren-sample.ts and lives in
 * the `landing-assets` Supabase Storage bucket (migration 037). Same TTS
 * pipeline as the real Hören module, so what users hear here is what they
 * hear on the exam.
 *
 * `prefers-reduced-motion: reduce` — wave stays static, pulsing ring is
 * not rendered. Audio still works. Pill remains (it's information, not motion).
 */

const BUCKET = 'landing-assets'
const FILE_PATH = 'hoeren-sample-b1.mp3'
const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? 'https://hnzyonehjzzgyavmlssf.supabase.co'
const SAMPLE_URL = `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${FILE_PATH}`

// Deterministic bar heights — server-render stable, no random per render.
const HEIGHTS = [
  14, 22, 9, 26, 18, 30, 12, 20, 28, 16, 24, 11, 19, 27, 13, 21, 10, 25, 17, 23,
  15, 29, 12, 18, 26, 14, 20, 16,
]

// Shared mock-chrome class strings — duplicated from ModulesDetailSection so this
// file stands on its own as a client component.
const MOCK_CARD =
  'rounded-rad border border-accent/25 bg-card p-4 shadow-lift ring-1 ring-accent/10 sm:p-5'
const MOCK_INNER = 'rounded-rad-sm border border-line bg-card'
const MOCK_EYEBROW = 'font-mono text-[10px] uppercase tracking-wider text-muted'

function formatTime(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds < 0) return '0:00'
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

function trackPlay(locale: string) {
  if (typeof window === 'undefined') return
  const w = window as Window & {
    umami?: { track: (event: string, data?: Record<string, unknown>) => void }
  }
  w.umami?.track('landing_hoeren_sample_played', { locale })
}

export function HoerenSampleMock() {
  const t = useTranslations('landing.modulesDetail.items.horen.sample')
  const locale = useLocale()
  const reducedMotion = useReducedMotion() ?? false

  const audioRef = useRef<HTMLAudioElement | null>(null)
  const [isPlaying, setIsPlaying] = useState(false)
  const [currentTime, setCurrentTime] = useState(0)
  const [duration, setDuration] = useState(0)
  const [hasPlayedOnce, setHasPlayedOnce] = useState(false)
  const [hasError, setHasError] = useState(false)

  // Set initial volume once metadata is available.
  useEffect(() => {
    const audio = audioRef.current
    if (!audio) return
    audio.volume = 0.7
  }, [])

  const playedBars = useMemo(() => {
    if (reducedMotion || !duration || duration === 0) return 0
    const ratio = Math.max(0, Math.min(1, currentTime / duration))
    return Math.floor(ratio * HEIGHTS.length)
  }, [currentTime, duration, reducedMotion])

  const handleToggle = () => {
    const audio = audioRef.current
    if (!audio || hasError) return
    if (audio.paused) {
      const playPromise = audio.play()
      if (playPromise && typeof playPromise.catch === 'function') {
        playPromise.catch(() => {
          setHasError(true)
        })
      }
      if (!hasPlayedOnce) {
        setHasPlayedOnce(true)
        trackPlay(locale)
      }
    } else {
      audio.pause()
    }
  }

  return (
    <div className={MOCK_CARD}>
      <div className="flex items-center justify-between border-b border-line pb-3">
        <span className={MOCK_EYEBROW}>МОДУЛЬ · HÖREN · 40 МИН · 4 ЧАСТИ</span>
        <span className="font-mono text-xs tabular-nums text-ink-soft">32:08</span>
      </div>

      <div className="mt-3 flex gap-1">
        {[0, 1, 2, 3].map((i) => (
          <span
            key={i}
            className={`flex-1 rounded-rad-sm px-2 py-1.5 text-center font-mono text-[10px] uppercase tracking-wider transition ${
              i === 1 ? 'bg-ink text-card' : 'bg-surface text-muted'
            }`}
          >
            Teil {i + 1}
          </span>
        ))}
      </div>

      {/* Pill — "Click to listen". Visible until the first play, then fades out. */}
      <div className="mt-4 h-5">
        <AnimatePresence>
          {!hasPlayedOnce && !hasError && (
            <motion.span
              initial={{ opacity: 0, y: -4 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -4 }}
              transition={{ duration: 0.3, ease: 'easeOut' }}
              className="inline-flex items-center gap-1 rounded-rad-pill border border-accent/40 bg-accent-soft px-2 py-0.5 font-mono text-[9px] uppercase tracking-wider text-accent-ink"
            >
              ► {t('pill')}
            </motion.span>
          )}
        </AnimatePresence>
      </div>

      {/* Audio player row */}
      <div className={`${MOCK_INNER} mt-2 flex items-center gap-3 p-3`}>
        <button
          type="button"
          onClick={handleToggle}
          disabled={hasError}
          aria-label={isPlaying ? 'Pause' : 'Play'}
          className="relative inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-ink text-card transition-opacity hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-card disabled:cursor-not-allowed disabled:opacity-50"
        >
          {isPlaying ? (
            <svg width="11" height="11" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
              <rect x="6" y="5" width="4" height="14" rx="1" />
              <rect x="14" y="5" width="4" height="14" rx="1" />
            </svg>
          ) : (
            <svg width="11" height="11" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
              <path d="M8 5v14l11-7z" />
            </svg>
          )}

          {/* Pulsing ring — until first play, motion-respecting. */}
          {!hasPlayedOnce && !reducedMotion && !hasError && (
            <span
              aria-hidden
              className="pointer-events-none absolute -inset-1 animate-live-pulse rounded-full ring-2 ring-accent/40"
            />
          )}
        </button>

        {/* Waveform — bars before playedBars are cobalt, after are muted. */}
        <div className="flex h-8 flex-1 items-center gap-[2px]">
          {HEIGHTS.map((h, i) => (
            <span
              key={i}
              aria-hidden
              className="block w-[3px] rounded-full transition-colors duration-100"
              style={{
                height: `${h}px`,
                background: i < playedBars ? 'var(--accent)' : 'var(--line)',
              }}
            />
          ))}
        </div>

        <span className="font-mono text-[10px] tabular-nums text-muted">
          {hasError ? '—' : `${formatTime(currentTime)} / ${formatTime(duration)}`}
        </span>
      </div>

      {/* Decorative R/F tasks — kept identical to the static mockup. */}
      <div className="mt-3 space-y-1.5">
        {[
          { id: 6, q: 'Die Frau kommt aus München.', a: 'richtig' as const },
          { id: 7, q: 'Sie arbeitet seit drei Jahren.', a: 'falsch' as const },
          {
            id: 8,
            q: 'Das Treffen ist am Freitag.',
            a: null as 'richtig' | 'falsch' | null,
          },
        ].map((row) => (
          <div
            key={row.id}
            className="flex items-center justify-between gap-2 border-l-2 border-accent/40 py-1.5 pl-2.5"
          >
            <span className="text-[10px] leading-tight text-ink-soft">
              <span className="mr-1.5 font-mono text-[9px] text-muted">{row.id}</span>
              {row.q}
            </span>
            <div className="flex shrink-0 gap-1">
              <span
                className={`rounded-rad-sm border px-1.5 py-0.5 font-mono text-[9px] uppercase ${
                  row.a === 'richtig'
                    ? 'border-accent/60 bg-accent-soft text-accent-ink'
                    : 'border-line text-muted'
                }`}
              >
                R
              </span>
              <span
                className={`rounded-rad-sm border px-1.5 py-0.5 font-mono text-[9px] uppercase ${
                  row.a === 'falsch'
                    ? 'border-accent/60 bg-accent-soft text-accent-ink'
                    : 'border-line text-muted'
                }`}
              >
                F
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Hidden audio element — preload metadata only so the duration appears in
          the timer without downloading the full clip; full audio fetched on play. */}
      <audio
        ref={audioRef}
        src={SAMPLE_URL}
        preload="metadata"
        onLoadedMetadata={(e) => setDuration(e.currentTarget.duration)}
        onTimeUpdate={(e) => setCurrentTime(e.currentTarget.currentTime)}
        onPlay={() => setIsPlaying(true)}
        onPause={() => setIsPlaying(false)}
        onEnded={() => {
          setIsPlaying(false)
          setCurrentTime(0)
        }}
        onError={() => setHasError(true)}
      />
    </div>
  )
}
