-- 037_landing_assets_bucket — public CDN bucket for static landing assets
--
-- Used by: components/landing/ModulesDetailSection.tsx (Hören sample player)
-- Files:   hoeren-sample-b1.mp3  — generated by scripts/generate-hoeren-sample.ts
-- Permissions: public read, service-role write only (anon/authenticated cannot upload)

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'landing-assets',
  'landing-assets',
  true,
  5242880,
  ARRAY['audio/mpeg', 'image/png', 'image/svg+xml', 'image/webp']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Public read for anon + authenticated (everyone can GET via CDN URL).
-- Service role bypasses RLS, so writes from scripts/generate-hoeren-sample.ts work.
DROP POLICY IF EXISTS "landing_assets_public_read" ON storage.objects;
CREATE POLICY "landing_assets_public_read"
  ON storage.objects
  FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'landing-assets');

-- We rely on the absence of an INSERT/UPDATE/DELETE policy for anon/authenticated;
-- with RLS enabled and no permissive policy, those operations are rejected.

NOTIFY pgrst, 'reload schema';
